//! # Trimmer Miniapp — Trim Away Elements by Attribute
//!
//! 1:1 port of MFEM `miniapps/meshing/trimmer.cpp` (MFEM 4.10).
//!
//! Creates a new mesh consisting of all elements NOT possessing a given set
//! of attribute numbers. New boundary elements are created at the cut faces.
//!
//! # Round 64 (D659) — unblock status
//!
//! * MFEM's default input `data/beam-tet.vtk` is a **VTK** file.  fem-rs has
//!   no VTK reader yet (fem-io only parses the MFEM mesh format), so the
//!   `.vtk` path is an honest, declared `exit(3)` with a gap note instead of
//!   a crash — the VTK reader itself is registered as debt **D675**.  The
//!   MFEM-format twin of the same mesh is byte-verified against the C++
//!   trimmer: `-m data/beam-tet.mesh -a 1` reproduces
//!   `48 -> 24` elements / `68 -> 36` boundary elements and the C++
//!   `trimmer.mesh` to 82/83 content lines; the single residual line is one
//!   cut triangle written as the same *oriented* triangle under a cyclic
//!   rotation of its vertex cycle (identical geometry and normal): fem-rs's
//!   write path MarkEdge-canonicalizes boundary cycles for AMR readiness
//!   (`mark_tet_mesh_for_refinement`), MFEM's trimmer preserves the
//!   post-`Finalize` cycle start.  Registered as debt **D676** (writer-level
//!   byte parity, not a trimmer-logic issue).
//! * The previous port only iterated the mesh's *boundary* faces, so the new
//!   boundary elements at the cut faces were never created (C++ prints
//!   `68 -> 36`, the old port counted 34 and wrote a mesh without the two cut
//!   triangles).  This port replicates MFEM `Mesh::GenerateFaces`: elements
//!   are scanned in order, local faces in `Geometry::Constants<T>::FaceVert`
//!   order (fem/geom.cpp:987 tet / 1032 hex / 1061 prism — outward-oriented
//!   cycles), first encounter owns the global face index and orientation.
//! * C++'s default `-m` value `../../data/beam-tet.vtk` assumes
//!   `cwd = miniapps/meshing`; here the default is repo-root relative
//!   (`data/beam-tet.vtk`) like every other example.

use std::collections::HashMap;

use fem_io::mfem::{read_mfem_file, write_mfem_file_3d};
use fem_mesh::{Mesh, element_type::ElementType};

/// MFEM `Geometry::Constants<T>::FaceVert` — the per-element-type local face
/// vertex tables `Mesh::GenerateFaces` scans (fem/geom.cpp: tet 987,
/// hex 1032, prism 1061; `-1` padding of prisms dropped).  Cycles point at
/// local vertices and are oriented outward for positively-oriented cells.
/// Element types without an entry are rejected with an honest message.
fn mfem_face_verts(et: ElementType) -> Vec<Vec<usize>> {
    match et {
        ElementType::Tet4 => vec![
            vec![1, 2, 3],
            vec![0, 3, 2],
            vec![0, 1, 3],
            vec![0, 2, 1],
        ],
        ElementType::Hex8 => vec![
            vec![3, 2, 1, 0],
            vec![0, 1, 5, 4],
            vec![1, 2, 6, 5],
            vec![2, 3, 7, 6],
            vec![3, 0, 4, 7],
            vec![4, 5, 6, 7],
        ],
        ElementType::Prism6 => vec![
            vec![0, 2, 1],
            vec![3, 4, 5],
            vec![0, 1, 4, 3],
            vec![1, 2, 5, 4],
            vec![2, 0, 3, 5],
        ],
        _ => vec![],
    }
}

/// One entry of MFEM's global face table (first-encounter orientation).
struct GlobFace {
    /// Vertex cycle as generated by `GenerateFaces` (owner's local table).
    verts: Vec<u32>,
    /// First-adjacent element (the "owner" = orientation donor).
    e1: u32,
    /// Second adjacent element, `None` on the mesh boundary.
    e2: Option<u32>,
}

/// MFEM `Mesh::Finalize(fix_orientation)` parity: reverse `cycle` iff it runs
/// opposite to the FaceVert cycle that element `adj` contributes for the same
/// face (the cycle start is preserved — a rotation never flips normals).
fn fixup_orientation(
    cycle: Vec<u32>,
    adj: u32,
    mesh: &Mesh<3>,
    face_table: &[Vec<usize>],
) -> Vec<u32> {
    let enodes = mesh.elem_nodes(adj);
    // The reference cycle of `adj`'s local face with the same vertex set.
    let mut reference: Option<Vec<u32>> = None;
    for fv in face_table {
        let cyc: Vec<u32> = fv.iter().map(|&i| enodes[i]).collect();
        let mut a = cyc.clone();
        let mut b = cycle.clone();
        a.sort_unstable();
        b.sort_unstable();
        if a == b {
            reference = Some(cyc);
            break;
        }
    }
    let Some(reference) = reference else { return cycle };
    // Rotate the reference so it starts at cycle[0], then compare the second
    // vertices: equal → same orientation, otherwise → reversed.
    let start = reference.iter().position(|&v| v == cycle[0]);
    let Some(start) = start else { return cycle };
    let n = reference.len();
    let same = reference[(start + 1) % n] == cycle[1 % n];
    if same { cycle } else { cycle.into_iter().rev().collect() }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    let mut mesh_file = "data/beam-tet.vtk".to_string();
    let mut attr: Vec<i32> = Vec::new();
    let mut bdr_attr: Vec<i32> = Vec::new();

    let mut it = args.iter().skip(1);
    while let Some(arg) = it.next() {
        match arg.as_str() {
            "-m" | "--mesh" => {
                if let Some(v) = it.next() { mesh_file = v.clone(); }
            }
            "-a" | "--attr" => {
                if let Some(v) = it.next() {
                    attr = v.split(',').filter_map(|s| s.trim().parse().ok()).collect();
                }
            }
            "-b" | "--bdr-attr" => {
                if let Some(v) = it.next() {
                    bdr_attr = v.split(',').filter_map(|s| s.trim().parse().ok()).collect();
                }
            }
            "-no-vis" | "--no-visualization" => {}
            _ => {}
        }
    }

    // D659: honest exit(3) on the VTK default — fem-rs has no VTK reader yet
    // (debt D675); MFEM's Mesh() constructor reads VTK natively.
    if mesh_file.to_ascii_lowercase().ends_with(".vtk") {
        eprintln!(
            "trimmer (D659 honest exit 3): '{}' is a VTK file but fem-rs has \
             no VTK reader yet (fem-io parses the MFEM mesh format only; \
             MFEM's Mesh() reads VTK natively).  Registered debt: D675.  \
             Run the MFEM-format twin of the same mesh instead: \
             -m data/beam-tet.mesh (byte-verified against the C++ trimmer).",
            mesh_file
        );
        std::process::exit(3);
    }

    // Read mesh
    let mesh = match read_mfem_file(&mesh_file) {
        Ok(m) => {
            if let Some(m3) = m.mesh3d { m3 }
            else if let Some(_m2) = m.mesh2d {
                eprintln!("Expected 3D mesh"); std::process::exit(1);
            }
            else { eprintln!("No mesh found"); std::process::exit(1); }
        }
        Err(e) => { eprintln!("Error reading mesh: {e}"); std::process::exit(1); }
    };

    let face_table = mfem_face_verts(mesh.elem_type);
    if face_table.is_empty() {
        eprintln!(
            "trimmer (D659): element type {:?} has no FaceVert table in this \
             port yet (tet/hex/prism are implemented, matching MFEM \
             `Geometry::Constants<T>::FaceVert`).",
            mesh.elem_type
        );
        std::process::exit(1);
    }

    let ne = mesh.n_elems();
    let nf = mesh.n_faces();
    let npf = mesh.face_type.nodes_per_element();

    // Find max attribute
    let max_attr = mesh.elem_tags.iter().copied().max().unwrap_or(0);
    let max_bdr_attr = mesh.face_tags.iter().copied().max().unwrap_or(0);

    if bdr_attr.is_empty() {
        bdr_attr = attr.iter().map(|&a| max_bdr_attr + a).collect();
    }
    assert_eq!(attr.len(), bdr_attr.len(), "Size mismatch in attribute arguments");

    // Build marker and inverse maps
    let mut marker = vec![false; (max_attr + 1) as usize];
    let mut attr_inv = vec![0usize; (max_attr + 1) as usize];
    for (i, &a) in attr.iter().enumerate() {
        if (a as usize) < marker.len() {
            marker[a as usize] = true;
            attr_inv[a as usize] = i;
        }
    }

    // ── MFEM `Mesh::GenerateFaces` replica ─────────────────────────────────
    // Elements scanned in order, local faces in FaceVert order; the first
    // encounter assigns the global face index and its vertex cycle.
    let mut faces: Vec<GlobFace> = Vec::new();
    let mut face_lookup: HashMap<Vec<u32>, usize> = HashMap::new();
    for e in 0..ne {
        let enodes = mesh.elem_nodes(e as u32);
        for fv in &face_table {
            let cyc: Vec<u32> = fv.iter().map(|&i| enodes[i]).collect();
            let mut key = cyc.clone();
            key.sort_unstable();
            match face_lookup.get(&key) {
                Some(&f) => faces[f].e2 = Some(e as u32),
                None => {
                    face_lookup.insert(key, faces.len());
                    faces.push(GlobFace { verts: cyc, e1: e as u32, e2: None });
                }
            }
        }
    }

    let elem_attr = |e: u32| mesh.element_attribute(e);

    // Count elements in final mesh
    let mut num_elements = 0;
    for e in 0..ne {
        if !marker[elem_attr(e as u32) as usize] { num_elements += 1; }
    }

    // Count boundary elements in final mesh (C++ trimmer.cpp, `num_bdr`):
    // original boundary faces whose adjacent element survives, plus the cut
    // faces where the two adjacent attributes differ in their marker bit.
    let mut num_bdr_elements = 0;
    for f in &faces {
        match f.e2 {
            None => {
                if !marker[elem_attr(f.e1) as usize] { num_bdr_elements += 1; }
            }
            Some(e2) => {
                let m1 = marker[elem_attr(f.e1) as usize];
                let m2 = marker[elem_attr(e2) as usize];
                if m1 != m2 { num_bdr_elements += 1; }
            }
        }
    }

    println!("Number of Elements:          {ne} -> {num_elements}");
    println!("Number of Boundary Elements: {nf} -> {num_bdr_elements}");

    // Build trimmed mesh
    // Copy vertices (all vertices are kept; unused ones are removed below)
    let trimmed_coords = mesh.coords.clone();

    // Copy elements that are not marked
    let mut trimmed_conn = Vec::new();
    let mut trimmed_elem_tags = Vec::new();
    for e in 0..ne {
        let a = elem_attr(e as u32);
        if !marker[a as usize] {
            let nodes = mesh.elem_nodes(e as u32);
            for &n in nodes { trimmed_conn.push(n); }
            trimmed_elem_tags.push(a);
        }
    }

    // Boundary of the trimmed mesh, in the C++ order: the surviving ORIGINAL
    // boundary elements first (in file order, original attributes), then the
    // new cut faces (in global-face order, attributes `bdr_attr[attr_inv]`).
    //
    // C++'s `trimmed_mesh.Finalize()` (fix_orientation) aligns every boundary
    // triangle with the FaceVert cycle of its surviving adjacent element
    // (reversal only — the cycle start is preserved).  The duplicated cut
    // faces inherit the *owner* (= first-encounter) orientation, which for
    // beam-tet is the REMOVED side, so without this alignment the two files
    // differ by exactly the two cut triangles' orientation (round-64 diff:
    // `4 2 10 15 0` vs `4 2 0 15 10`).  `fixup_orientation` replicates it.
    let mut trimmed_face_conn = Vec::new();
    let mut trimmed_face_tags = Vec::new();
    for f in 0..nf {
        let fnodes = &mesh.face_conn[f * npf..f * npf + npf];
        let mut key = fnodes.to_vec();
        key.sort_unstable();
        if let Some(&g) = face_lookup.get(&key) {
            if faces[g].e2.is_none() && !marker[elem_attr(faces[g].e1) as usize] {
                let cyc = fixup_orientation(fnodes.to_vec(), faces[g].e1, &mesh, &face_table);
                trimmed_face_conn.extend_from_slice(&cyc);
                trimmed_face_tags.push(mesh.face_tags[f]);
            }
        }
    }
    for f in &faces {
        if let Some(e2) = f.e2 {
            let a1 = elem_attr(f.e1) as usize;
            let a2 = elem_attr(e2) as usize;
            let (m1, m2) = (marker[a1], marker[a2]);
            if m1 != m2 {
                let a = if m1 { a1 } else { a2 };
                let new_attr = bdr_attr[attr_inv[a]];
                let survivor = if m1 { e2 } else { f.e1 };
                let cyc = fixup_orientation(f.verts.clone(), survivor, &mesh, &face_table);
                trimmed_face_conn.extend_from_slice(&cyc);
                trimmed_face_tags.push(new_attr);
            }
        }
    }

    let mut trimmed = Mesh::<3> {
        coords: trimmed_coords,
        conn: trimmed_conn,
        elem_tags: trimmed_elem_tags,
        elem_type: mesh.elem_type,
        face_conn: trimmed_face_conn,
        face_tags: trimmed_face_tags,
        face_type: mesh.face_type,
        elem_types: mesh.elem_types,
        elem_offsets: mesh.elem_offsets,
        face_types: mesh.face_types,
        face_offsets: mesh.face_offsets,
        face_to_elem: mesh.face_to_elem,
        edge_conn: mesh.edge_conn,
        edge_to_elem: mesh.edge_to_elem,
        geometry: mesh.geometry,
        nc_vertex_view: mesh.nc_vertex_view,
        vertex_parents: vec![],
    };

    // Remove unused vertices (C++: FinalizeTopology/Finalize/RemoveUnusedVertices)
    trimmed.remove_unused_vertices();

    write_mfem_file_3d("trimmer.mesh", &trimmed).expect("write mesh");
    println!("Wrote trimmer.mesh ({} elements, {} nodes).", trimmed.n_elems(), trimmed.n_nodes());
}

// TEMP-DEBUG D659: removed before final report
#[allow(dead_code)]
fn temp_debug() {
    let _ = std::collections::HashMap::<u32, u32>::new();
}
