[package]
name    = "fem-linalg"
version = "0.1.0"
edition = "2021"

[dependencies]
fem-core   = { path = "../core" }
num-traits = { workspace = true }
bytemuck   = { workspace = true }
linlvo     = { git = "https://github.com/rem-rs/linlvo.git", optional = true }
parking_lot = "0.12"
thiserror  = { workspace = true }  # Thread-safe pool for COO buffers

[dev-dependencies]
proptest = "1"


[features]
default  = []
parallel = ["dep:rayon"]
direct   = ["dep:linlvo"]

[dependencies.rayon]
workspace = true
optional  = true
