//! Round-102 regression pins for the TMOP metric zoo.
//!
//! Every row pins values produced by the MFEM 4.10 C++ oracle
//! (`tmp/d102tmop/d102_dump_metric.cpp`, built against mfem410_ser) on the
//! deterministic synthetic Jacobians generated by [`sample_jpt`] below — the
//! same generator the C++ oracle uses, so the pins reproduce exactly.
//!
//! Per id: (id, EvalW of synthetic record 0, EvalW of record 1, EvalP[0] of
//! record 0, AssembleH[0] of record 0). Records 0/1 use W = I and W =
//! R(0.7)·diag(1.3, 0.9) (2D) / R(0.4)·R(0.9)·diag(1.2, 0.8, 1.1) (3D)
//! respectively, exercising the target-dependent A-metrics.
//!
//! Metrics 211/313 have no C++ derivative path (MFEM aborts in EvalP/
//! AssembleH); their EP/EH pins are empty and the fem-rs analytic derivatives
//! are instead verified against finite differences of their own EvalW /
//! EvalP in [`d102_no_cpp_deriv_metrics_are_fd_consistent`].
//!
//! Driver parameter conventions (mesh-optimizer / tmop-check-metric):
//! gamma = 0.5 (66/80/332/333/334/347) / 0.9 (49/126), eps = 1e-4 (211/311),
//! tauval = min_det = -0.1 (22/252/313/352).

use fem_mesh::tmop::{
    TmopAMetric011, TmopAMetric036, TmopAMetric049, TmopAMetric051, TmopAMetric107,
    TmopAMetric126, TmopMetric000, TmopMetric001, TmopMetric002, TmopMetric004, TmopMetric007,
    TmopMetric009, TmopMetric014, TmopMetric022, TmopMetric050, TmopMetric055, TmopMetric056,
    TmopMetric058, TmopMetric066, TmopMetric077, TmopMetric080, TmopMetric085, TmopMetric090,
    TmopMetric094, TmopMetric098, TmopMetric211, TmopMetric252, TmopMetric301, TmopMetric302,
    TmopMetric303, TmopMetric304, TmopMetric311, TmopMetric313, TmopMetric315, TmopMetric316,
    TmopMetric318, TmopMetric321, TmopMetric322, TmopMetric323, TmopMetric328, TmopMetric332,
    TmopMetric333, TmopMetric334, TmopMetric338, TmopMetric342, TmopMetric347, TmopMetric352,
    TmopMetric360, TmopQualityMetric, TmopQualityMetric3D,
};

const PINS: &[(i32, &str, &str, &str, &str, &str)] = &[
    (0, "0", "0", "0", "0", "0"),
    (1, "2.4813643052250001", "3.4528120767434025", "0.47584901286339454", "1.4694875286306992", "0.011425000000000003"),
    (2, "0.0732665268835202", "0.15821728734538532", "0.17064983140862688", "-0.083849695618935655", "0.0049657254187134127"),
    (4, "0.16939030522499987", "0.47166845674340241", "0.069366220062056227", "-0.080310031570404838", "0.011425000000000003"),
    (7, "0.33824769039026581", "1.0068697606135748", "7.9956461815544948", "0.079682919070713343", "0.025298545104436295"),
    (9, "0.39100993287117247", "1.5008116815120429", "1.6250462950648135", "0.35422014122304318", "0.0311697255996463"),
    (11, "0.073266526883520228", "0.27723293510349184", "0.17064983140862697", "-0.083849695618935627", "0.0049657254187134119"),
    (14, "1.4620792163931964", "2.923259380134382", "0.599697409686613", "-0.5305124713693008", "0.011425000000000003"),
    (22, "0.067433144302050829", "0.14827009185564605", "0.1143745888348362", "-0.073574708212112094", "0.0045546517656298077"),
    (36, "1.264788632046205", "2.3951644923182966", "2.9506656631327819", "-1.3067583281013981", "0.017093769511271433"),
    (49, "0.045671072397874136", "0.017905666528700365", "0.080589331234998396", "-0.18827732281621182", "0.0029835176254737038"),
    (50, "0.30380207545722815", "0.68293456941140551", "0.7408420555540931", "-0.35997228638870155", "0.021318597750978153"),
    (51, "0.053577613976035408", "0.083230054168663109", "1.7425643948024867", "-0.10032088690227177", "0.0039418184689279032"),
    (55, "0.02433194416900003", "0.24066070076667614", "0.63482427240955552", "0.24174827202308977", "0.0037713971309634034"),
    (56, "0.010524315657961525", "0.080727643965934126", "1.5617494360205684", "0.097508758010944177", "0.001220712580336615"),
    (58, "0.31453804338037517", "0.73299998944127021", "0.79908478547367867", "-0.38454579030166047", "0.022774293827102648"),
    (66, "0.096861124696999951", "0.35616457875503926", "0.3520952462358059", "0.080719120226342464", "0.0075981985654817036"),
    (77, "0.042318785071983056", "0.33594448086431794", "11.125120345903401", "0.39413988383866849", "0.0050536734138232888"),
    (80, "0.057792655977751628", "0.24708088410485163", "5.6478850886560137", "0.15514509410986643", "0.0050096994162683508"),
    (85, "1.5996703602060953", "3.5819747606625651", "0.036558070161296807", "-0.28456072676312927", "0.01011147096869312"),
    (90, "0.40959903813718579", "1.5227957715722003", "28.553642920312594", "0.62537742320796963", "0.033952781285536374"),
    (94, "0.089053000370462487", "0.2793087532942865", "2.5132739854394797", "0.062413441397480618", "0.0067967942892183351"),
    (98, "1.264788632046205", "1.9611664198415117", "2.9506656631327819", "-1.3067583281013979", "0.017093769511271433"),
    (107, "0.69190672568380751", "1.5220888647484099", "0.089937559003054668", "-0.58689071854381958", "0.0077275064048939789"),
    (126, "0.016798536780517404", "0.10037817307968981", "1.4226394755593736", "0.079372912647956095", "0.0015952138641742955"),
    (211, "0.024375196441404734", "0.24069424456313837", "0.63507013657055866", "", ""),
    (252, "0.0096863837639243194", "0.075652258908912806", "1.0467308882372544", "0.090262215332876941", "0.0011516014635073453"),
    (301, "0.064413242960539074", "0.058578247109116965", "0.038576191231984636", "0.19987911010144893", "0.0023371980031760011"),
    (302, "0.13297555178977172", "0.12058790525261065", "0.0786405049939356", "0.42550794356629973", "0.0050054547892223536"),
    (303, "0.067259007987612085", "0.057287768651064441", "0.036113131412418786", "0.2205314914863003", "0.0024098691697657104"),
    (304, "0.10256637486879971", "0.087150855829017715", "0.05465585204706902", "0.34174076577381585", "0.0037530556481549238"),
    (311, "0.0045584876694517718", "0.097104101578819213", "0.015544973510203564", "-0.076654844543532219", "0.0037045206902503185"),
    (313, "0.99721120689018539", "1.0067438756730269", "0.97890597659267087", "", ""),
    (315, "0.0045048918341170814", "0.097065979421302059", "0.01550051022426248", "-0.076622053048768402", "0.0037042925925104934"),
    (316, "0.002414503766371201", "0.037004183352100428", "0.0068921724404695794", "-0.042544757725184658", "0.0022813705604357347"),
    (318, "0.0096696747223603552", "0.15075535257951334", "0.027663693843776871", "-0.17058992881180593", "0.0091886746927112312"),
    (321, "0.39256403778811766", "0.45416920276245065", "0.24939211754585422", "1.0814169948769798", "0.020845642906698929"),
    (322, "0.064768317941330089", "0.06302472357273281", "0.039470126010538564", "0.19485618744595565", "0.0025726979531166738"),
    (323, "0.5094353029289449", "0.80355589396148552", "0.35657133822056242", "1.7473662984287106", "0.032765531899230885"),
    (328, "0.050724435986775507", "0.080937868683938152", "0.035824315864458056", "0.10736457485090203", "0.0040342690628177354"),
    (332, "0.068740221811944405", "0.10882694233695636", "0.04707050760909904", "0.17444294525876566", "0.0043548736908664235"),
    (333, "0.067695027778071459", "0.078796044302355539", "0.04276633871720259", "0.19148159292055753", "0.0036434126748290442"),
    (334, "0.034836755876991643", "0.047145976001582435", "0.021502651926444183", "0.088993366880557825", "0.0023456198651007226"),
    (338, "0.14962888047828121", "0.38022212358399476", "0.12628353328044023", "0.13171417727930063", "0.020830394537780586"),
    (342, "1.1694217970034038", "1.9976944800960643", "0.063497521645446225", "-0.48348460563433704", "0.0076475311378650379"),
    (347, "0.052490439317585458", "0.062077519590559072", "0.0307740122437693", "0.14959800402431558", "0.0030172131042953292"),
    (352, "0.0021807398984606476", "0.034382662687866494", "0.0063293168620116363", "-0.038296538132547742", "0.0020338042475060605"),
    (360, "0.095682274560265679", "0.11430306538528323", "0.061460562746282976", "0.37734820997260066", "0.0041774811430466095"),
];

fn frac(x: f64) -> f64 {
    x - x.floor()
}

/// Deterministic synthetic Jacobian (column-major flat), record `s` — the same
/// formula as the C++ oracle's synthetic mode (det > 0 by construction).
fn sample_jpt(id: i32, s: usize) -> Vec<f64> {
    let a = 0.6 + 0.9 * frac(0.103 * s as f64 + 0.71);
    let b = 0.6 + 0.9 * frac(0.207 * s as f64 + 0.37);
    if id < 300 {
        let th = 0.3 + 1.2 * frac(0.311 * s as f64 + 0.53);
        let sh = 0.15 + 0.5 * frac(0.577 * s as f64 + 0.29);
        let (c, sn) = (th.cos(), th.sin());
        // J = R(th) [[1,sh],[0,1]] diag(a,b)
        vec![c * a, sn * a, (c * sh - sn) * b, (sn * sh + c) * b]
    } else {
        let c = 0.6 + 0.9 * frac(0.081 * s as f64 + 0.23);
        let t1 = 0.2 + frac(0.131 * s as f64 + 0.19);
        let t2 = 0.2 + frac(0.277 * s as f64 + 0.41);
        let (c1, s1, c2, s2) = (t1.cos(), t1.sin(), t2.cos(), t2.sin());
        // J = G1(t1) G2(t2) diag(a, b, c)
        let g = [c1 * c2, -s1, -c1 * s2, s1 * c2, c1, -s1 * s2, s2, 0.0, c2];
        vec![
            g[0] * a, g[3] * a, g[6] * a, //
            g[1] * b, g[4] * b, g[7] * b, //
            g[2] * c, g[5] * c, g[8] * c,
        ]
    }
}

/// Target Jacobian for record `s` (even: identity; odd: fixed non-trivial W).
fn sample_w(id: i32, s: usize) -> Vec<f64> {
    if s % 2 == 0 {
        // The oracle fills W with the identity on even records.
        return if id < 300 {
            vec![1.0, 0.0, 0.0, 1.0]
        } else {
            vec![1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
        };
    }
    if id < 300 {
        let (c, sn) = (0.7f64.cos(), 0.7f64.sin());
        vec![c * 1.3, sn * 1.3, -sn * 0.9, c * 0.9]
    } else {
        let (c3, s3, c4, s4) = (0.4f64.cos(), 0.4f64.sin(), 0.9f64.cos(), 0.9f64.sin());
        let g = [c3 * c4, -s3, -c3 * s4, s3 * c4, c3, -s3 * s4, s4, 0.0, c4];
        vec![
            g[0] * 1.2, g[3] * 1.2, g[6] * 1.2, //
            g[1] * 0.8, g[4] * 0.8, g[7] * 0.8, //
            g[2] * 1.1, g[5] * 1.1, g[8] * 1.1,
        ]
    }
}

/// Deterministic DS (nd x dim, column-major) and quadrature weight for the
/// AssembleH pin — identical to the C++ oracle's synthetic mode.
fn sample_ds_weight(id: i32, s: usize) -> (Vec<f64>, f64) {
    let (nd, dim) = if id < 300 { (4usize, 2usize) } else { (8usize, 3usize) };
    let mut ds = vec![0.0; nd * dim];
    for i in 0..nd {
        for d in 0..dim {
            // The oracle uses different coefficient triples per dimension.
            let v = if id < 300 {
                frac(0.61 * i as f64 + 0.17 * d as f64 + 0.29) - 0.5
            } else {
                frac(0.53 * i as f64 + 0.11 * d as f64 + 0.37) - 0.5
            };
            ds[i + d * nd] = v;
        }
    }
    (ds, 0.125 + frac(0.23 * s as f64))
}

/// Engineering-tolerance comparison against a pinned %.17g value: the
/// absolute difference must be at most 1e-12 or the relative difference at
/// most 1e-10 (same policy as the -dump comparison mode of tmop-check-metric).
fn close(a: f64, pin: &str) -> bool {
    let p: f64 = pin.parse().unwrap();
    let d = (a - p).abs();
    d <= 1e-12 || d <= 1e-10 * p.abs()
}

fn metric_2d(id: i32) -> Box<dyn TmopQualityMetric> {
    match id {
        0 => Box::new(TmopMetric000),
        1 => Box::new(TmopMetric001),
        2 => Box::new(TmopMetric002),
        4 => Box::new(TmopMetric004),
        7 => Box::new(TmopMetric007),
        9 => Box::new(TmopMetric009),
        11 => Box::new(TmopAMetric011::new()),
        14 => Box::new(TmopMetric014),
        22 => Box::new(TmopMetric022 { min_det_t: -0.1 }),
        36 => Box::new(TmopAMetric036::new()),
        49 => Box::new(TmopAMetric049::new(0.9)),
        50 => Box::new(TmopMetric050),
        51 => Box::new(TmopAMetric051::new()),
        55 => Box::new(TmopMetric055),
        56 => Box::new(TmopMetric056),
        58 => Box::new(TmopMetric058),
        66 => Box::new(TmopMetric066::new(0.5)),
        77 => Box::new(TmopMetric077),
        80 => Box::new(TmopMetric080::new(0.5)),
        85 => Box::new(TmopMetric085),
        90 => Box::new(TmopMetric090::new()),
        94 => Box::new(TmopMetric094::new()),
        98 => Box::new(TmopMetric098),
        107 => Box::new(TmopAMetric107::new()),
        126 => Box::new(TmopAMetric126::new(0.9)),
        211 => Box::new(TmopMetric211 { eps: 1e-4 }),
        252 => Box::new(TmopMetric252 { tau0: -0.1 }),
        other => panic!("no 2D metric {other}"),
    }
}

fn metric_3d(id: i32) -> Box<dyn TmopQualityMetric3D> {
    match id {
        301 => Box::new(TmopMetric301),
        302 => Box::new(TmopMetric302),
        303 => Box::new(TmopMetric303),
        304 => Box::new(TmopMetric304),
        311 => Box::new(TmopMetric311 { eps: 1e-4 }),
        313 => Box::new(TmopMetric313 { min_det_t: -0.1 }),
        315 => Box::new(TmopMetric315),
        316 => Box::new(TmopMetric316),
        318 => Box::new(TmopMetric318),
        321 => Box::new(TmopMetric321),
        322 => Box::new(TmopMetric322),
        323 => Box::new(TmopMetric323),
        328 => Box::new(TmopMetric328::new()),
        332 => Box::new(TmopMetric332::new(0.5)),
        333 => Box::new(TmopMetric333::new(0.5)),
        334 => Box::new(TmopMetric334::new(0.5)),
        338 => Box::new(TmopMetric338::new()),
        342 => Box::new(TmopMetric342),
        347 => Box::new(TmopMetric347::new(0.5)),
        352 => Box::new(TmopMetric352 { tau0: -0.1 }),
        360 => Box::new(TmopMetric360),
        other => panic!("no 3D metric {other}"),
    }
}

#[test]
fn d102_pins_eval_w() {
    for row in PINS {
        let (id, ew0, ew1) = (row.0, row.1, row.2);
        // Per-record W: identity for record 0, the fixed non-trivial W for
        // record 1 (MFEM SetTargetJacobian per quadrature record).
        let w0 = sample_w(id, 0);
        let w1 = sample_w(id, 1);
        if id < 300 {
            let m = metric_2d(id);
            let j0 = sample_jpt(id, 0);
            let j1 = sample_jpt(id, 1);
            m.set_target_jacobian(&[[w0[0], w0[2]], [w0[1], w0[3]]]);
            let v0 = m.eval_w(&[[j0[0], j0[2]], [j0[1], j0[3]]]);
            m.set_target_jacobian(&[[w1[0], w1[2]], [w1[1], w1[3]]]);
            let v1 = m.eval_w(&[[j1[0], j1[2]], [j1[1], j1[3]]]);
            assert!(close(v0, ew0), "id {id}: EvalW(rec0) {v0} vs pin {ew0}");
            assert!(close(v1, ew1), "id {id}: EvalW(rec1) {v1} vs pin {ew1}");
        } else {
            // No 3D A-metrics exist in MFEM, so the 3D trait carries no
            // set_target_jacobian hook; the W samples are irrelevant here.
            let m = metric_3d(id);
            let pick =
                |v: &Vec<f64>| [[v[0], v[3], v[6]], [v[1], v[4], v[7]], [v[2], v[5], v[8]]];
            let v0 = m.eval_w(&pick(&sample_jpt(id, 0)));
            let v1 = m.eval_w(&pick(&sample_jpt(id, 1)));
            assert!(close(v0, ew0), "id {id}: EvalW(rec0) {v0} vs pin {ew0}");
            assert!(close(v1, ew1), "id {id}: EvalW(rec1) {v1} vs pin {ew1}");
        }
    }
}

#[test]
fn d102_pins_eval_p_and_h() {
    for row in PINS {
        let (id, ep0, eh0) = (row.0, row.4, row.5);
        if ep0.is_empty() {
            // 211/313: no C++ reference path — covered by the FD test below.
            continue;
        }
        let j0 = sample_jpt(id, 0);
        let (ds, weight) = sample_ds_weight(id, 0);
        if id < 300 {
            let m = metric_2d(id);
            let jpt = [[j0[0], j0[2]], [j0[1], j0[3]]];
            let mut p = [[0.0f64; 2]; 2];
            m.eval_p(&jpt, &mut p);
            assert!(close(p[0][0], ep0), "id {id}: EvalP[0] {} vs pin {ep0}", p[0][0]);
            let ds_rows: Vec<[f64; 2]> = (0..4).map(|i| [ds[i], ds[i + 4]]).collect();
            let mut a = vec![0.0f64; 64];
            m.assemble_h(&jpt, &ds_rows, weight, &mut a);
            assert!(close(a[0], eh0), "id {id}: AssembleH[0] {} vs pin {eh0}", a[0]);
        } else {
            let m = metric_3d(id);
            let jpt = [[j0[0], j0[3], j0[6]], [j0[1], j0[4], j0[7]], [j0[2], j0[5], j0[8]]];
            let mut p = [[0.0f64; 3]; 3];
            m.eval_p(&jpt, &mut p);
            assert!(close(p[0][0], ep0), "id {id}: EvalP[0] {} vs pin {ep0}", p[0][0]);
            let ds_rows: Vec<[f64; 3]> =
                (0..8).map(|i| [ds[i], ds[i + 8], ds[i + 16]]).collect();
            let mut a = vec![0.0f64; 24 * 24];
            m.assemble_h(&jpt, &ds_rows, weight, &mut a);
            assert!(close(a[0], eh0), "id {id}: AssembleH[0] {} vs pin {eh0}", a[0]);
        }
    }
}

/// Metrics 211 (2D) and 313 (3D): MFEM 4.10 implements only EvalW (EvalP and
/// AssembleH abort). fem-rs completes them analytically; verify their
/// derivatives against central finite differences of their own EvalW / EvalP.
#[test]
fn d102_no_cpp_deriv_metrics_are_fd_consistent() {
    let h = 1e-6;

    // 211 in 2D.
    {
        let m = metric_2d(211);
        let jpt = [[0.8, 0.3], [-0.2, 1.15]];
        let mut p = [[0.0f64; 2]; 2];
        m.eval_p(&jpt, &mut p);
        for r in 0..2 {
            for c in 0..2 {
                let mut jp = jpt;
                let mut jm = jpt;
                jp[r][c] += h;
                jm[r][c] -= h;
                let fd = (m.eval_w(&jp) - m.eval_w(&jm)) / (2.0 * h);
                assert!(
                    (p[r][c] - fd).abs() <= 1e-5 * (1.0 + fd.abs()),
                    "211 P[{r}][{c}] {} vs fd {fd}",
                    p[r][c]
                );
            }
        }
        // AssembleH vs the central-FD Hessian of P, contracted like
        // DefaultAssembleH.
        let ds = [[0.3, -0.2], [0.1, 0.4], [-0.35, 0.15], [0.22, 0.31]];
        let weight = 0.7;
        let mut a = vec![0.0f64; 64];
        m.assemble_h(&jpt, &ds, weight, &mut a);
        let mut dp = vec![[0.0f64; 4]; 4]; // dp[je][pe] = dP_pe/dJ_je (flat)
        for je in 0..4 {
            let (r, c) = (je % 2, je / 2);
            let mut jp = jpt;
            let mut jm = jpt;
            jp[r][c] += h;
            jm[r][c] -= h;
            let mut pp = [[0.0f64; 2]; 2];
            let mut pm = [[0.0f64; 2]; 2];
            m.eval_p(&jp, &mut pp);
            m.eval_p(&jm, &mut pm);
            for s in 0..4 {
                let (sr, sc) = (s % 2, s / 2);
                dp[je][s] = (pp[sr][sc] - pm[sr][sc]) / (2.0 * h);
            }
        }
        // Contraction reference (MFEM DefaultAssembleH convention):
        // A(i + pr*2, j + jr*2) += w * DS(i, pc) * DS(j, jc) * dP_prpc/dJ_jrjc.
        let mut a_ref = vec![0.0f64; 64];
        for pr in 0..2 {
            for pc in 0..2 {
                for jr in 0..2 {
                    for jc in 0..2 {
                        let je = jr + jc * 2;
                        let pe = pr + pc * 2;
                        for i in 0..4usize {
                            for j in 0..4usize {
                                a_ref[i + pr * 4 + (j + jr * 4) * 8] +=
                                    weight * ds[i][pc] * ds[j][jc] * dp[je][pe];
                            }
                        }
                    }
                }
            }
        }
        for k in 0..a.len() {
            assert!(
                (a[k] - a_ref[k]).abs() <= 1e-5 * (1.0 + a_ref[k].abs()),
                "211 A[{k}] {} vs fd {}",
                a[k],
                a_ref[k]
            );
        }
    }

    // 313 in 3D (same structure).
    {
        let m = metric_3d(313);
        let jpt = [[1.05, 0.22, -0.12], [0.31, 0.94, 0.4], [-0.06, 0.18, 1.2]];
        let mut p = [[0.0f64; 3]; 3];
        m.eval_p(&jpt, &mut p);
        for r in 0..3 {
            for c in 0..3 {
                let mut jp = jpt;
                let mut jm = jpt;
                jp[r][c] += h;
                jm[r][c] -= h;
                let fd = (m.eval_w(&jp) - m.eval_w(&jm)) / (2.0 * h);
                assert!(
                    (p[r][c] - fd).abs() <= 1e-5 * (1.0 + fd.abs()),
                    "313 P[{r}][{c}] {} vs fd {fd}",
                    p[r][c]
                );
            }
        }
        let nd = 8usize;
        let mut ds = vec![0.0f64; nd * 3];
        for i in 0..nd {
            for d in 0..3 {
                ds[i + d * nd] = frac(0.61 * i as f64 + 0.17 * d as f64 + 0.29) - 0.5;
            }
        }
        let ds_rows: Vec<[f64; 3]> =
            (0..nd).map(|i| [ds[i], ds[i + nd], ds[i + 2 * nd]]).collect();
        let weight = 0.9;
        let mut a = vec![0.0f64; nd * 3 * nd * 3];
        m.assemble_h(&jpt, &ds_rows, weight, &mut a);
        let mut dp = vec![[0.0f64; 9]; 9]; // dp[je][pe] = dP_pe/dJ_je (flat)
        for je in 0..9 {
            let (r, c) = (je % 3, je / 3);
            let mut jp = jpt;
            let mut jm = jpt;
            jp[r][c] += h;
            jm[r][c] -= h;
            let mut pp = [[0.0f64; 3]; 3];
            let mut pm = [[0.0f64; 3]; 3];
            m.eval_p(&jp, &mut pp);
            m.eval_p(&jm, &mut pm);
            for s in 0..9 {
                let (sr, sc) = (s % 3, s / 3);
                dp[je][s] = (pp[sr][sc] - pm[sr][sc]) / (2.0 * h);
            }
        }
        let mut a_ref = vec![0.0f64; nd * 3 * nd * 3];
        for pr in 0..3 {
            for pc in 0..3 {
                for jr in 0..3 {
                    for jc in 0..3 {
                        let je = jr + jc * 3;
                        let pe = pr + pc * 3;
                        for i in 0..nd {
                            for j in 0..nd {
                                a_ref[i + pr * nd + (j + jr * nd) * nd * 3] +=
                                    weight * ds_rows[i][pc] * ds_rows[j][jc] * dp[je][pe];
                            }
                        }
                    }
                }
            }
        }
        for k in 0..a.len() {
            assert!(
                (a[k] - a_ref[k]).abs() <= 1e-5 * (1.0 + a_ref[k].abs()),
                "313 A[{k}] {} vs fd {}",
                a[k],
                a_ref[k]
            );
        }
    }
}
