//! D787 — `fem_mesh::transformation::element_jacobian_at` on **curved
//! simplices** (`Tet4/Tet10`, `Prism6/Prism15/Prism18`) and the curved 2-D
//! families (`Tri3/Tri6`, `Quad4/Quad8/Quad9`).
//!
//! # The defect
//!
//! `element_jacobian_at` had isoparametric branches for **hexes only** (D715)
//! and **pyramids only** (D334).  Every other cell fell into the `(None, None)`
//! arm, which pairs `et.ref_elem(1)` (the P1 basis) with
//! [`raw_geometry_nodes`]-selected nodes — a table only when it is *P1-sized*.
//! A curved cell's geometry table is never P1-sized (10 nodes for a tet, 18 for
//! a prism, 9 for a quad, 6 for a triangle), so the helper silently dropped it
//! and integrated the **straight** map spanned by the element's corner nodes:
//! `Mesh::element_jacobian` (the assembly-side map) and
//! `ElementTransformation::Weight()` in MFEM both evaluate the order-`g`
//! `nodes` map instead.  Measured on the fixture below (g3-warped unit tet):
//! `element_jacobian_at` reported `∫|det J| = 2.0e-1` (the warped *corners*'
//! tetrahedron) against MFEM's `1.829847222222222e-1` — **9.3 % off** — and the
//! consumers that route through it (`DGMassInverse`, `complex::compute_l2_error`,
//! `physics::topology_optimization`, `compute_l2_error_{hcurl,hdiv,l2}` for
//! tets, `flux_recovery`'s pyramid arm) inherited the error.  See
//! `tmp/d787/README.md` for the per-consumer audit (which of the registered
//! consumers really routed through this entry point and which had their own
//! geometry path).
//!
//! # The fix (what these tests pin)
//!
//! `curved_geometry` generalises the D715 hex arm into one family-aware
//! dispatch that mirrors `Mesh::element_jacobian`'s family table:
//!
//! | cell | geometry element (order `g`) | reference frame |
//! |------|------------------------------|-----------------|
//! | `Tet4/Tet10` | `H1TetPk(g)` (closed GLL) | unit simplex |
//! | `Prism6/15/18` | `PrismPk(g)` (GLL lattice, layer-major) | `(ξ=extrusion, η, ζ)` |
//! | `Tri3/Tri6` | `H1TriPk(g)` (closed GLL) | unit triangle |
//! | `Quad4/Quad8/Quad9` | `QuadQk(g)` (closed GLL) | `[0,1]²` |
//! | `Hex*` | `HexQk(g)` (D715 arm, unchanged) | `[0,1]³` |
//!
//! gated on `geom_order >= 2` **and** a table-length match, so straight meshes
//! (including geometrically periodic ones with P1-sized tables) keep the exact
//! previous code path.  The family choice is not cosmetic: at `g = 3` the
//! equispaced `TetPk(3)`/`TriPk(3)` lattices are *not* the stored GLL one, so a
//! same-order-but-wrong-family element reads every interior node from the wrong
//! reference point (the `tet P3`/`prism P3` cases below pin that).
//!
//! # MFEM truth
//!
//! `tmp/d787/d787_probe.cpp` (MFEM 4.10 serial, `$HOME/work/d787/d787_probe`)
//! builds the same physical cell — unit cell, `SetCurvature(g)`, then the D319
//! quadratic warp `g3` applied to every geometry dof *and* every vertex, i.e.
//! exactly what `curved_unit_*` does on the fem-rs side via
//! `Mesh::set_curvature(g)` + the same warp — and dumps `Weight()`,
//! `Jacobian()`, `Transform()` at the reference points below plus
//! `Σ_q w_q |Weight()|` for an order-8 rule.  The pinned numbers were generated
//! from `tmp/d787/mfem_truth_*.txt` by `tmp/d787/gen_pins.py`
//! (`tmp/d787/pins_generated.rs`); regenerate with
//!
//! ```text
//! wsl -e bash -lc 'cd $HOME/work/d787 && ./d787_probe {tet,prism,quad,tri} 2'
//! uv run --no-project python tmp/d787/gen_pins.py
//! ```
//!
//! Reference frames: MFEM's wedge reference is the cyclic relabeling
//! `(tri-x, tri-y, extrusion)` of fem-rs' `PrismPk` frame `(extrusion, tri-x,
//! tri-y)`, so the generator rewrites every prism sample into the fem-rs frame
//! (`xi_femrs = (z, x, y)`, Jacobian columns `(c2, c0, c1)` — a 3-cycle, so
//! `det J` is frame-independent).  Tet/triangle/square reference frames are
//! identical in both codes.

use fem_element::quadrature::{prism_rule, quad_rule_01, tet_rule, tri_rule};
use fem_element::QuadratureRule;
use fem_mesh::element_type::ElementType;
use fem_mesh::transformation::element_jacobian_at;
use fem_mesh::{Mesh, MeshTopology};

/// Relative tolerance: both sides evaluate the same order-`g` interpolant, so
/// agreement is at roundoff (~1e-15 measured; the `P3` truth carries ~4e-15 of
/// MFEM-side basis-sum noise).
const TOL: f64 = 1e-13;

// ─── MFEM 4.10 truth (generated by tmp/d787/gen_pins.py) ────────────────────
#[derive(Clone, Copy)]
struct Sample {
    /// Reference point in the fem-rs frame (2-D: `xi[2] == 0`).
    xi: [f64; 3],
    /// MFEM `ElementTransformation::Weight()` = det J (signed).
    det: f64,
    /// MFEM `Jacobian()` (2-D: third row/column zero).
    jac: [[f64; 3]; 3],
    /// MFEM `Transform()` — the physical image of `xi`.
    xp: [f64; 3],
}

/// MFEM 4.10 truth for the curved unit tet (P2 geometry):
/// `mfem_truth_tet.txt` — Σ w|Weight()| / order-8 rule.
const MFEM_TET_P2_VOL: f64 = 0.1829847222222222;
const MFEM_TET_P2_VOL_P3_RULE: f64 = 0.18298472222222223;
const MFEM_TET_P2_SAMPLES: &[Sample] = &[
    Sample { xi: [0.25, 0.25, 0.25], det: 1.098734375,
        jac: [[1.1, 0.025, 0.025], [0.0125, 1.0, 0.012500000000000011], [0.025000000000000022, 0.025000000000000022, 1.0]], xp: [0.26875000000000004, 0.253125, 0.25625] },
    Sample { xi: [0.1, 0.2, 0.3], det: 1.039104,
        jac: [[1.0400000000000003, 0.03, 0.02000000000000017], [0.01500000000000017, 1.0, 0.0050000000000000044], [0.02000000000000013, 0.010000000000000009, 0.9999999999999999]], xp: [0.10800000000000004, 0.20150000000000007, 0.30200000000000005] },
    Sample { xi: [0.5, 0.25, 0.1], det: 1.1978374999999997,
        jac: [[1.1999999999999995, 0.009999999999999882, 0.025], [0.004999999999999558, 0.9999999999999999, 0.025000000000000022], [0.024999999999999883, 0.04999999999999971, 1.0]], xp: [0.5525, 0.25249999999999995, 0.11249999999999995] },
    Sample { xi: [0.05, 0.05, 0.05], det: 1.0199498750000004,
        jac: [[1.0200000000000005, 0.0049999999999999194, 0.0050000000000000044], [0.0024999999999999484, 1.0, 0.0025000000000000022], [0.004999999999999949, 0.004999999999999921, 1.0]], xp: [0.05075000000000017, 0.05012500000000014, 0.05025000000000017] },
    Sample { xi: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333], det: 1.1310740740740726,
        jac: [[1.1333333333333329, 0.033333333333333326, 0.033333333333333215], [0.016666666666666663, 0.9999999999999996, 0.016666666666666607], [0.033333333333333326, 0.033333333333333326, 0.9999999999999994]], xp: [0.3666666666666666, 0.3388888888888888, 0.34444444444444433] },
];

/// MFEM 4.10 truth for the curved unit prism (P2 geometry):
/// `mfem_truth_prism.txt` — Σ w|Weight()| / order-8 rule.
const MFEM_PRISM_P2_VOL: f64 = 0.5976874999999998;
const MFEM_PRISM_P2_VOL_P3_RULE: f64 = 0.5976875000000001;
const MFEM_PRISM_P2_SAMPLES: &[Sample] = &[
    Sample { xi: [0.6, 0.3, 0.2], det: 1.2367039999999987,
        jac: [[1.2399999999999987, 0.02000000000000013, 0.029999999999999916], [0.009999999999999901, 0.9999999999999998, 0.029999999999999943], [0.029999999999999888, 0.06000000000000005, 1.0000000000000002]], xp: [0.6779999999999996, 0.3059999999999998, 0.21799999999999983] },
    Sample { xi: [0.5, 0.25, 0.25], det: 1.1975937499999998,
        jac: [[1.2, 0.025000000000000022, 0.025000000000000022], [0.012500000000000028, 1.0, 0.024999999999999956], [0.025000000000000022, 0.050000000000000044, 1.0]], xp: [0.55625, 0.25625, 0.2625] },
    Sample { xi: [0.7, 0.05, 0.1], det: 1.2767924999999982,
        jac: [[1.279999999999999, 0.00999999999999851, 0.0050000000000001155], [0.0049999999999999645, 0.9999999999999993, 0.034999999999999996], [0.004999999999999949, 0.06999999999999976, 1.0]], xp: [0.7984999999999993, 0.05349999999999972, 0.10349999999999965] },
    Sample { xi: [0.25, 0.5, 0.25], det: 1.096875,
        jac: [[1.1, 0.025000000000000022, 0.050000000000000044], [0.012499999999999867, 0.9999999999999999, 0.012499999999999956], [0.050000000000000044, 0.025000000000000022, 1.0]], xp: [0.275, 0.5031249999999999, 0.2625] },
    Sample { xi: [0.1, 0.4, 0.5], det: 1.0371180000000007,
        jac: [[1.0400000000000003, 0.050000000000000044, 0.03999999999999987], [0.024999999999999682, 1.0000000000000004, 0.004999999999999485], [0.03999999999999987, 0.009999999999999953, 0.9999999999999999]], xp: [0.12200000000000001, 0.40249999999999997, 0.504] },
];

/// MFEM 4.10 truth for the curved unit quad (P2 geometry):
/// `mfem_truth_quad.txt` — Σ w|Weight()| / order-8 rule.
const MFEM_QUAD_P2_VOL: f64 = 1.2816666666666667;
const MFEM_QUAD_P2_VOL_P3_RULE: f64 = 1.2816666666666663;
const MFEM_QUAD_P2_SAMPLES: &[Sample] = &[
    Sample { xi: [0.3, 0.7, 0.0], det: 1.2067999999999999,
        jac: [[1.1900000000000002, 0.029999999999999916, 0.0], [0.0349999999999997, 1.0149999999999997, 0.0], [0.0, 0.0, 0.0]], xp: [0.33899999999999997, 0.7104999999999999, 0.0] },
    Sample { xi: [0.5, 0.5, 0.0], det: 1.28,
        jac: [[1.25, 0.050000000000000044, 0.0], [0.025000000000000022, 1.025, 0.0], [0.0, 0.0, 0.0]], xp: [0.5750000000000001, 0.5125, 0.0] },
    Sample { xi: [0.1, 0.9, 0.0], det: 1.135200000000001,
        jac: [[1.1300000000000008, 0.010000000000000009, 0.0], [0.04500000000000004, 1.0050000000000003, 0.0], [0.0, 0.0, 0.0]], xp: [0.11100000000000004, 0.9045000000000002, 0.0] },
];

/// MFEM 4.10 truth for the curved unit tri (P2 geometry):
/// `mfem_truth_tri.txt` — Σ w|Weight()| / order-8 rule.
const MFEM_TRI_P2_VOL: f64 = 0.5933333333333333;
const MFEM_TRI_P2_VOL_P3_RULE: f64 = 0.5933333333333336;
const MFEM_TRI_P2_SAMPLES: &[Sample] = &[
    Sample { xi: [0.25, 0.25, 0.0], det: 1.13875,
        jac: [[1.125, 0.025000000000000022, 0.0], [0.012499999999999956, 1.0125, 0.0], [0.0, 0.0, 0.0]], xp: [0.26875000000000004, 0.253125, 0.0] },
    Sample { xi: [0.1, 0.2, 0.0], det: 1.0652000000000001,
        jac: [[1.06, 0.010000000000000009, 0.0], [0.009999999999999953, 1.0050000000000001, 0.0], [0.0, 0.0, 0.0]], xp: [0.10399999999999968, 0.20099999999999985, 0.0] },
    Sample { xi: [0.5, 0.25, 0.0], det: 1.255,
        jac: [[1.225, 0.050000000000000044, 0.0], [0.012499999999999956, 1.025, 0.0], [0.0, 0.0, 0.0]], xp: [0.5625, 0.25625, 0.0] },
];

/// MFEM 4.10 truth for the curved unit tet (P3 geometry):
/// `mfem_truth_tet_p3.txt` — Σ w|Weight()| / order-8 rule.
const MFEM_TET_P3_VOL: f64 = 0.18298472222222228;
const MFEM_TET_P3_VOL_P3_RULE: f64 = 0.1829847222222225;
const MFEM_TET_P3_SAMPLES: &[Sample] = &[
    Sample { xi: [0.25, 0.25, 0.25], det: 1.0987343750000016,
        jac: [[1.1000000000000003, 0.024999999999999963, 0.02500000000000202], [0.012499999999999567, 1.0000000000000002, 0.01250000000000051], [0.024999999999999828, 0.025000000000000456, 1.0000000000000009]], xp: [0.2687499999999996, 0.25312500000000004, 0.2562499999999998] },
    Sample { xi: [0.1, 0.2, 0.3], det: 1.039104000000003,
        jac: [[1.0400000000000014, 0.03000000000000047, 0.0200000000000006], [0.015000000000001457, 1.0000000000000007, 0.004999999999999866], [0.020000000000001357, 0.010000000000000116, 1.0000000000000009]], xp: [0.10799999999999982, 0.20149999999999968, 0.30199999999999977] },
    Sample { xi: [0.5, 0.25, 0.1], det: 1.1978375,
        jac: [[1.1999999999999993, 0.010000000000002118, 0.024999999999999023], [0.004999999999997118, 1.0000000000000009, 0.025000000000000355], [0.024999999999997555, 0.05000000000000149, 0.9999999999999999]], xp: [0.5524999999999997, 0.25249999999999984, 0.11249999999999975] },
    Sample { xi: [0.05, 0.05, 0.05], det: 1.019949875000001,
        jac: [[1.0200000000000018, 0.004999999999999505, 0.005000000000000782], [0.0025000000000003353, 0.9999999999999989, 0.0024999999999977505], [0.005000000000001458, 0.004999999999997392, 1.0000000000000002]], xp: [0.05074999999999988, 0.05012500000000012, 0.05024999999999994] },
    Sample { xi: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333], det: 1.1310740740740757,
        jac: [[1.1333333333333324, 0.0333333333333341, 0.03333333333333921], [0.016666666666664165, 1.0000000000000018, 0.016666666666666052], [0.03333333333333084, 0.03333333333333496, 1.0000000000000004]], xp: [0.36666666666666664, 0.33888888888888885, 0.34444444444444444] },
];

/// MFEM 4.10 truth for the curved unit prism (P3 geometry):
/// `mfem_truth_prism_p3.txt` — Σ w|Weight()| / order-8 rule.
const MFEM_PRISM_P3_VOL: f64 = 0.5976874999999998;
const MFEM_PRISM_P3_VOL_P3_RULE: f64 = 0.5976874999999993;
const MFEM_PRISM_P3_SAMPLES: &[Sample] = &[
    Sample { xi: [0.6, 0.3, 0.2], det: 1.236704000000004,
        jac: [[1.2400000000000009, 0.01999999999999924, 0.029999999999999583], [0.009999999999999898, 1.000000000000001, 0.030000000000000804], [0.030000000000000027, 0.06000000000000005, 1.0000000000000013]], xp: [0.6780000000000005, 0.30600000000000027, 0.21800000000000003] },
    Sample { xi: [0.5, 0.25, 0.25], det: 1.1975937500000011,
        jac: [[1.2000000000000006, 0.02499999999999858, 0.024999999999999023], [0.012499999999999956, 1.0000000000000004, 0.0249999999999998], [0.025000000000000022, 0.04999999999999882, 0.9999999999999999]], xp: [0.5562500000000001, 0.25625000000000014, 0.26249999999999996] },
    Sample { xi: [0.7, 0.05, 0.1], det: 1.276792500000003,
        jac: [[1.2800000000000007, 0.0099999999999969, 0.004999999999999338], [0.004999999999999949, 1.0000000000000004, 0.034999999999999476], [0.004999999999999963, 0.06999999999999729, 1.0000000000000013]], xp: [0.7985000000000003, 0.0534999999999998, 0.10349999999999965] },
    Sample { xi: [0.25, 0.5, 0.25], det: 1.0968749999999978,
        jac: [[1.0999999999999992, 0.024999999999999772, 0.049999999999999545], [0.012499999999999956, 0.9999999999999994, 0.012499999999998885], [0.050000000000000044, 0.024999999999999252, 0.9999999999999991]], xp: [0.2749999999999998, 0.5031249999999999, 0.26249999999999957] },
    Sample { xi: [0.1, 0.4, 0.5], det: 1.0371180000000044,
        jac: [[1.0399999999999998, 0.050000000000000155, 0.04000000000000026], [0.025000000000000244, 1.0000000000000029, 0.004999999999999005], [0.04000000000000027, 0.0099999999999974, 1.0000000000000016]], xp: [0.122, 0.4025, 0.5040000000000001] },
];

// ─── fixture ────────────────────────────────────────────────────────────────

/// The D319/D341 quadratic warp (3-D) — the map every geometry node (and
/// vertex) of the fixture is pushed through.
fn g3(x: [f64; 3]) -> [f64; 3] {
    [
        x[0] + 0.1 * x[1] * x[2] + 0.2 * x[0] * x[0],
        x[1] + 0.05 * x[0] * x[2],
        x[2] + 0.1 * x[0] * x[1],
    ]
}

/// Its 2-D variant (the D113 `g2`).
fn g2(x: [f64; 2]) -> [f64; 2] {
    [
        x[0] + 0.2 * x[0] * x[0] + 0.1 * x[0] * x[1],
        x[1] + 0.05 * x[0] * x[1],
    ]
}

/// A single-element 3-D mesh (cells + their boundary faces).
fn mesh_3d(
    coords: &[[f64; 3]],
    conn: &[u32],
    et: ElementType,
    faces: &[u32],
    face_et: ElementType,
) -> Mesh<3> {
    Mesh::<3>::uniform(
        coords.iter().flatten().copied().collect(),
        conn.to_vec(),
        vec![1],
        et,
        faces.to_vec(),
        vec![1; faces.len() / face_et.nodes_per_element()],
        face_et,
    )
}

/// A single-element 2-D mesh.
fn mesh_2d(
    coords: &[[f64; 2]],
    conn: &[u32],
    et: ElementType,
    edges: &[u32],
) -> Mesh<2> {
    Mesh::<2>::uniform(
        coords.iter().flatten().copied().collect(),
        conn.to_vec(),
        vec![1],
        et,
        edges.to_vec(),
        vec![1; edges.len() / 2],
        ElementType::Line2,
    )
}

/// The unit tet (0,0,0) (1,0,0) (0,1,0) (0,0,1) with its four Tri3 faces.
fn unit_tet() -> Mesh<3> {
    mesh_3d(
        &[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
        &[0, 1, 2, 3],
        ElementType::Tet4,
        &[0, 1, 2, 0, 1, 3, 0, 2, 3, 1, 2, 3],
        ElementType::Tri3,
    )
}

/// The unit wedge in the `PrismPk` frame (extrusion first) with its two Tri3
/// end caps.
fn unit_prism() -> Mesh<3> {
    mesh_3d(
        &[
            [0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [1.0, 1.0, 0.0],
            [1.0, 0.0, 1.0],
        ],
        &[0, 1, 2, 3, 4, 5],
        ElementType::Prism6,
        &[0, 1, 2, 3, 4, 5],
        ElementType::Tri3,
    )
}

/// The unit square with its four Line2 edges.
fn unit_quad() -> Mesh<2> {
    mesh_2d(
        &[[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]],
        &[0, 1, 2, 3],
        ElementType::Quad4,
        &[0, 1, 1, 2, 2, 3, 3, 0],
    )
}

/// The unit triangle with its three Line2 edges.
fn unit_tri() -> Mesh<2> {
    mesh_2d(
        &[[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]],
        &[0, 1, 2],
        ElementType::Tri3,
        &[0, 1, 1, 2, 2, 0],
    )
}

/// Warp every geometry node **and** every vertex by `f` — the physical mesh
/// MFEM's `SetCurvature(g)` + warp produces (the io layer's `nodes` values).
fn warp_mesh<const D: usize>(mesh: &mut Mesh<D>, f: fn([f64; D]) -> [f64; D]) {
    let n_geom = mesh.geometry.as_ref().expect("curved mesh keeps a table").coords.len() / D;
    {
        let geo = mesh.geometry.as_mut().expect("curved mesh keeps a table");
        for k in 0..n_geom {
            let mut x = [0.0_f64; D];
            x.copy_from_slice(&geo.coords[k * D..(k + 1) * D]);
            let y = f(x);
            geo.coords[k * D..(k + 1) * D].copy_from_slice(&y);
        }
    }
    for k in 0..mesh.n_nodes() {
        let mut x = [0.0_f64; D];
        x.copy_from_slice(&mesh.coords[k * D..(k + 1) * D]);
        let y = f(x);
        mesh.coords[k * D..(k + 1) * D].copy_from_slice(&y);
    }
}

/// `set_curvature(order)` + the quadratic warp: the D787 fixture.
fn curved_unit_tet(order: u8) -> Mesh<3> {
    let mut m = unit_tet();
    m.set_curvature(order);
    warp_mesh(&mut m, g3);
    m
}

fn curved_unit_prism(order: u8) -> Mesh<3> {
    let mut m = unit_prism();
    m.set_curvature(order);
    warp_mesh(&mut m, g3);
    m
}

fn curved_unit_quad(order: u8) -> Mesh<2> {
    let mut m = unit_quad();
    m.set_curvature(order);
    warp_mesh(&mut m, g2);
    m
}

fn curved_unit_tri(order: u8) -> Mesh<2> {
    let mut m = unit_tri();
    m.set_curvature(order);
    warp_mesh(&mut m, g2);
    m
}

// ─── helpers ────────────────────────────────────────────────────────────────

fn assert_close(got: f64, want: f64, tol: f64, what: &str) {
    let scale = want.abs().max(1.0);
    let err = (got - want).abs();
    assert!(
        err <= tol * scale,
        "{what}: got {got:.17e}, MFEM {want:.17e} (|Δ| = {err:.3e}, tol {tol:.1e} rel)"
    );
}

/// `∫|det J| dξ` over `rule` — the same `Σ_q w_q |Weight()|` MFEM's side
/// computes (assertion-safe: reports the fem-rs number before comparing).
fn volume<M: MeshTopology + ?Sized>(
    mesh: &M,
    e: u32,
    dim: usize,
    rule: &QuadratureRule,
    label: &str,
) -> f64 {
    let mut v = 0.0;
    for (xi, w) in rule.points.iter().zip(rule.weights.iter()) {
        let (jac, _xp) = element_jacobian_at(mesh, e, xi, dim);
        v += w * jac.determinant().abs();
    }
    eprintln!("{label}: ∫|det J| = {v:.17e}");
    v
}

/// One MFEM sample: `J`, `det J` and `x(ξ)` from `element_jacobian_at`.
fn check_sample<M: MeshTopology + ?Sized>(
    mesh: &M,
    dim: usize,
    e: u32,
    s: &Sample,
    label: &str,
) {
    let xi = &s.xi[..dim];
    let (jac, xp) = element_jacobian_at(mesh, e, xi, dim);
    let det = jac.determinant();
    eprintln!(
        "{label} at {xi:?}: det = {det:.17e} (MFEM {:.17e}); x = {xp:?} (MFEM {:?})",
        s.det,
        &s.xp[..dim]
    );
    assert_close(det, s.det, TOL, &format!("{label}: det J at {xi:?}"));
    for i in 0..dim {
        for j in 0..dim {
            assert_close(
                jac[(i, j)],
                s.jac[i][j],
                TOL,
                &format!("{label}: J[{i}][{j}] at {xi:?}"),
            );
        }
        assert_close(xp[i], s.xp[i], TOL, &format!("{label}: x[{i}] at {xi:?}"));
    }
}

/// The same map through both mesh-crate entries:
/// `element_jacobian_at` (dyn `MeshTopology`) vs `Mesh::element_jacobian`
/// (the assembly-side accessor, D708/D113-verified against MFEM).
fn check_agrees_with_mesh_entry<const D: usize>(
    mesh: &Mesh<D>,
    dim: usize,
    rule: &QuadratureRule,
    label: &str,
) {
    let mut worst = 0.0_f64;
    for (xi, _w) in rule.points.iter().zip(rule.weights.iter()) {
        let (j_dyn, xp_dyn) = element_jacobian_at(mesh, 0, xi, dim);
        let (j_mesh, det_mesh, xp_mesh) = mesh.element_jacobian(0, xi);
        let det_dyn = j_dyn.determinant();
        worst = worst.max((det_dyn - det_mesh).abs() / det_mesh.abs().max(1.0));
        for i in 0..dim {
            for j in 0..dim {
                worst = worst.max(
                    (j_dyn[(i, j)] - j_mesh[(i, j)]).abs() / j_mesh[(i, j)].abs().max(1.0),
                );
            }
            worst = worst.max((xp_dyn[i] - xp_mesh[i]).abs());
        }
    }
    eprintln!("{label}: dyn-vs-Mesh::element_jacobian worst |Δ| = {worst:.3e}");
    assert!(worst <= TOL, "{label}: the two mesh-crate Jacobian entries disagree ({worst:.3e})");
}

/// `geometry_jacobian` — the other public geometry entry, `(det J, J^{-T})` —
/// takes the same arms: it used to keep the P1 vertex map on every curved
/// non-pyramid cell, so its `J^{-T}` (the gradient transform
/// `physics::mixed_hyperelasticity` applies) disagreed with the map
/// `element_jacobian_at` and the assembler evaluate for the same cell.
fn check_geometry_jacobian<const D: usize>(mesh: &Mesh<D>, dim: usize, label: &str) {
    let mut worst = 0.0_f64;
    // Two reference points inside every fixture cell (tet/triangle: the
    // barycentric sum stays ≤ 1; prism: `tx + ty ≤ 1`; quad `[0,1]²`).
    let second: Vec<f64> = if dim == 3 { vec![0.1, 0.2, 0.3] } else { vec![0.1, 0.2] };
    for xi in [vec![0.25; dim], second] {
        let (j, _xp) = element_jacobian_at(mesh, 0, &xi, dim);
        let (det, jit) = fem_mesh::transformation::geometry_jacobian(mesh, 0, &xi, dim);
        worst = worst.max((det - j.determinant()).abs() / j.determinant().abs().max(1.0));
        let want = j.clone().try_inverse().expect("non-singular").transpose();
        for i in 0..dim {
            for jj in 0..dim {
                worst = worst.max((jit[(i, jj)] - want[(i, jj)]).abs());
            }
        }
    }
    eprintln!("{label}: geometry_jacobian-vs-element_jacobian_at worst |Δ| = {worst:.3e}");
    assert!(
        worst <= TOL,
        "{label}: `geometry_jacobian` disagrees with `element_jacobian_at` ({worst:.3e})"
    );
}

// ─── the red tests: curved simplices were integrated with the straight map ──

/// Curved P2 tet: `J`, `det J` and `x(ξ)` at five reference points, plus the
/// element volume, all against MFEM 4.10.
///
/// Fix前 red evidence (`cargo test --release -p fem-mesh --test
/// d787_curved_simplex_geometry -- --nocapture`):
/// `∫|det J| = 2.0e-1` (the straight map) vs MFEM `1.829847222222222e-1`;
/// `det J ≡ 1.2` at every sample vs `1.098734375` / `1.039104` / `1.1978375` /
/// `1.019949875` / `1.1310740740740726`.
#[test]
fn d787_curved_tet_p2_jacobian_and_volume_match_mfem() {
    let mesh = curved_unit_tet(2);
    assert_eq!(mesh.geom_order(), 2);
    assert_eq!(mesh.element_nodes(0).len(), 4, "still a Tet4 cell");
    assert_eq!(mesh.geometry_nodes(0).len(), 10, "H1TetPk(2) geometry row");

    let vol = volume(&mesh, 0, 3, &tet_rule(8), "curved tet P2");
    assert_close(vol, MFEM_TET_P2_VOL, TOL, "curved tet P2 volume");
    let vol_p3 = volume(&mesh, 0, 3, &tet_rule(3), "curved tet P2 (order-3 rule)");
    assert_close(vol_p3, MFEM_TET_P2_VOL_P3_RULE, TOL, "curved tet P2 volume, order-3 rule");
    assert_close(vol_p3, vol, TOL, "rule-independence of the curved tet volume");

    for (k, s) in MFEM_TET_P2_SAMPLES.iter().enumerate() {
        check_sample(&mesh, 3, 0, s, &format!("curved tet P2 sample {k}"));
    }
    check_agrees_with_mesh_entry(&mesh, 3, &tet_rule(8), "curved tet P2");
    check_geometry_jacobian(&mesh, 3, "curved tet P2");
}

/// Curved P3 tet — the **family** check: `set_curvature(3)` stores the table on
/// `H1TetPk(3)`'s Gauss-Lobatto lattice, so only `H1TetPk(3)` (not the
/// equispaced `TetPk(3)` the generic factory returns) reads the node values
/// from the reference points they belong to.  Both lattices reproduce the same
/// quadratic warp in exact arithmetic, so a wrong-family evaluation shows up as
/// a wrong *map* (≈1e-2 `det J` error), not as a wrong volume.
#[test]
fn d787_curved_tet_p3_gauss_lobatto_geometry_matches_mfem() {
    let mesh = curved_unit_tet(3);
    assert_eq!(mesh.geometry_nodes(0).len(), 20, "H1TetPk(3) geometry row");
    let vol = volume(&mesh, 0, 3, &tet_rule(8), "curved tet P3");
    assert_close(vol, MFEM_TET_P3_VOL, TOL, "curved tet P3 volume");
    for (k, s) in MFEM_TET_P3_SAMPLES.iter().enumerate() {
        check_sample(&mesh, 3, 0, s, &format!("curved tet P3 sample {k}"));
    }
    check_agrees_with_mesh_entry(&mesh, 3, &tet_rule(8), "curved tet P3");
    check_geometry_jacobian(&mesh, 3, "curved tet P3");
}

/// Curved P3 prism (`PrismPk(3)`'s GLL lattice, layer-major slots).
#[test]
fn d787_curved_prism_p3_geometry_matches_mfem() {
    let mesh = curved_unit_prism(3);
    assert_eq!(mesh.geometry_nodes(0).len(), 40, "PrismPk(3) geometry row");
    let vol = volume(&mesh, 0, 3, &prism_rule(8), "curved prism P3");
    assert_close(vol, MFEM_PRISM_P3_VOL, TOL, "curved prism P3 volume");
    for (k, s) in MFEM_PRISM_P3_SAMPLES.iter().enumerate() {
        check_sample(&mesh, 3, 0, s, &format!("curved prism P3 sample {k}"));
    }
    check_agrees_with_mesh_entry(&mesh, 3, &prism_rule(8), "curved prism P3");
    check_geometry_jacobian(&mesh, 3, "curved prism P3");
}

/// Curved P2 prism: the reference-frame relabeling is part of the contract —
/// `element_jacobian_at` evaluates `PrismPk(g)` on `(ξ = extrusion, η, ζ)`,
/// MFEM on the cyclic `(tri-x, tri-y, extrusion)`.
#[test]
fn d787_curved_prism_p2_jacobian_and_volume_match_mfem() {
    let mesh = curved_unit_prism(2);
    assert_eq!(mesh.geometry_nodes(0).len(), 18, "PrismPk(2) geometry row");
    let vol = volume(&mesh, 0, 3, &prism_rule(8), "curved prism P2");
    assert_close(vol, MFEM_PRISM_P2_VOL, TOL, "curved prism P2 volume");
    let vol_p3 = volume(&mesh, 0, 3, &prism_rule(3), "curved prism P2 (order-3 rule)");
    assert_close(vol_p3, MFEM_PRISM_P2_VOL_P3_RULE, TOL, "curved prism P2 volume, order-3 rule");
    for (k, s) in MFEM_PRISM_P2_SAMPLES.iter().enumerate() {
        check_sample(&mesh, 3, 0, s, &format!("curved prism P2 sample {k}"));
    }
    check_agrees_with_mesh_entry(&mesh, 3, &prism_rule(8), "curved prism P2");
    check_geometry_jacobian(&mesh, 3, "curved prism P2");
}

/// Curved P2 **quad** (2-D): the same `(None, None)` fall-through dropped the
/// `QuadQk(2)` table and integrated the bilinear corner map.
#[test]
fn d787_curved_quad_p2_jacobian_and_volume_match_mfem() {
    let mesh = curved_unit_quad(2);
    assert_eq!(mesh.geometry_nodes(0).len(), 9, "QuadQk(2) geometry row");
    let vol = volume(&mesh, 0, 2, &quad_rule_01(8), "curved quad P2");
    assert_close(vol, MFEM_QUAD_P2_VOL, TOL, "curved quad P2 volume");
    let vol_p3 = volume(&mesh, 0, 2, &quad_rule_01(3), "curved quad P2 (order-3 rule)");
    assert_close(vol_p3, MFEM_QUAD_P2_VOL_P3_RULE, TOL, "curved quad P2 volume, order-3 rule");
    for (k, s) in MFEM_QUAD_P2_SAMPLES.iter().enumerate() {
        check_sample(&mesh, 2, 0, s, &format!("curved quad P2 sample {k}"));
    }
    check_agrees_with_mesh_entry(&mesh, 2, &quad_rule_01(8), "curved quad P2");
    check_geometry_jacobian(&mesh, 2, "curved quad P2");
}

/// Curved P2 **triangle** (2-D).
#[test]
fn d787_curved_tri_p2_jacobian_and_volume_match_mfem() {
    let mesh = curved_unit_tri(2);
    assert_eq!(mesh.geometry_nodes(0).len(), 6, "H1TriPk(2) geometry row");
    let vol = volume(&mesh, 0, 2, &tri_rule(8), "curved tri P2");
    assert_close(vol, MFEM_TRI_P2_VOL, TOL, "curved tri P2 volume");
    let vol_p3 = volume(&mesh, 0, 2, &tri_rule(3), "curved tri P2 (order-3 rule)");
    assert_close(vol_p3, MFEM_TRI_P2_VOL_P3_RULE, TOL, "curved tri P2 volume, order-3 rule");
    for (k, s) in MFEM_TRI_P2_SAMPLES.iter().enumerate() {
        check_sample(&mesh, 2, 0, s, &format!("curved tri P2 sample {k}"));
    }
    check_agrees_with_mesh_entry(&mesh, 2, &tri_rule(8), "curved tri P2");
    check_geometry_jacobian(&mesh, 2, "curved tri P2");
}

// ─── straight meshes must keep the previous path bit for bit ────────────────

/// The straight path is *not* re-routed: with `geom_order == 1` (no table) the
/// P1 vertex interpolation is exactly the affine simplex map, checked here
/// against the vertex differences directly (not against the implementation's
/// own output), and against the same map through `Mesh::element_jacobian`.
#[test]
fn d787_straight_simplices_keep_the_affine_map() {
    for (label, mesh, dim) in [
        ("tet", unit_tet(), 3usize),
        ("prism", unit_prism(), 3),
    ] {
        let (jac, xp) = element_jacobian_at(&mesh, 0, &[0.25, 0.25, 0.25][..dim], dim);
        let v = mesh.element_nodes(0);
        // J[:,k] = x_{k+1} - x_0 for the affine simplex (Prism6's corner order
        // [0,1,2] = (ext,η,ζ) axes via nodes 3/1/2 — same table the reference
        // element's slot order dictates).
        let x0 = mesh.coords_of(v[0]);
        let col_of: &[usize] = if dim == 3 && v.len() == 6 { &[3, 1, 2] } else { &[1, 2, 3] };
        for (col, &n) in col_of.iter().enumerate() {
            let xn = mesh.coords_of(v[n]);
            for row in 0..dim {
                let want = xn[row] - x0[row];
                assert_close(jac[(row, col)], want, TOL, &format!("{label}: straight J[{row}][{col}]"));
            }
        }
        for row in 0..dim {
            let want = x0[row] + (0..dim).map(|k| jac[(row, k)] * 0.25).sum::<f64>();
            assert_close(xp[row], want, TOL, &format!("{label}: straight x[{row}]"));
        }
        assert_close(jac.determinant(), 1.0, TOL, &format!("{label}: straight det J"));
    }
    for (label, mesh, dim) in [("quad", unit_quad(), 2usize), ("tri", unit_tri(), 2)] {
        let (jac, _xp) = element_jacobian_at(&mesh, 0, &[0.5, 0.5][..dim], dim);
        assert_close(jac[(0, 0)], 1.0, TOL, &format!("{label}: straight J[0][0]"));
        assert_close(jac[(1, 1)], 1.0, TOL, &format!("{label}: straight J[1][1]"));
        assert_close(jac[(0, 1)], 0.0, TOL, &format!("{label}: straight J[0][1]"));
        assert_close(jac[(1, 0)], 0.0, TOL, &format!("{label}: straight J[1][0]"));
    }
}

/// A geometrically periodic-style mesh keeps a **P1-sized** geometry table
/// (`raw_geometry_nodes`'s "table only when P1-sized" rule) — the new arm must
/// not hijack it.  The table here is the vertex table itself, so the map is the
/// affine one either way.
#[test]
fn d787_p1_sized_geometry_table_keeps_the_straight_path() {
    let mut mesh = unit_tet();
    let conn = mesh.conn.clone();
    let coords = mesh.coords.clone();
    let n = mesh.n_nodes();
    mesh.geometry = Some(fem_mesh::simplex::GeometryData {
        order: 1,
        conn,
        nodes_per_elem: 4,
        coords,
        n_nodes: n,
    });
    assert_eq!(mesh.geom_order(), 1);
    let (jac, xp) = element_jacobian_at(&mesh, 0, &[0.1, 0.2, 0.3], 3);
    assert_close(jac.determinant(), 1.0, TOL, "P1-sized table: det J");
    assert_close(xp[0], 0.1, TOL, "P1-sized table: x[0]");
    assert_close(xp[1], 0.2, TOL, "P1-sized table: x[1]");
    assert_close(xp[2], 0.3, TOL, "P1-sized table: x[2]");
}
