//! D104 — `MFEM NC mesh v1.0` writer (polar-nc lane) regression pins.
//!
//! Round 104 added [`fem_io::mfem_nc`]: the non-conforming container writer
//! (`NCMesh::Print` + the curved-`nodes` tail of `Mesh::Printer`) plus the
//! hanging-free conforming fallback (`Mesh::Printer`'s plain `MFEM mesh v1.0`
//! branch), so the `polar-nc` miniapp can reproduce MFEM 4.10's products.
//!
//! Provenance of the two embedded goldens: generated by the **C++** MFEM
//! 4.10 `miniapps/meshing/polar-nc` (WSL, `$HOME/mfem410_ser`,
//! `polar-nc -no-vis -n 2` and `-n 1`), copied verbatim from
//! `fem-rs/tmp/d104pnc/gold/`.  The round-104 byte-diff ledger showed the
//! Rust miniapp's full output byte-identical to the C++ products for **21/21**
//! parameter sets (def, ±sfc, -o 1..5, -n 1/2/3/4/7/20, -a 0.4/0.5/2,
//! -phi 30/120/270, -r 0.5); the two smallest artifacts are embedded here so
//! the *writer* half of that equality stays pinned in CI (the generator half
//! lives in the miniapp binary and is re-verified against WSL MFEM by the
//! round script).  The GridFunction values below are transcribed from the
//! C++ text; `format_g` renders 8-significant-digit literals identically
//! after an f64 round trip, so transcription (not derivation) is exact.
//!
//! The tests were written against these bytes *before* the final writer state
//! was reached (red): during development they caught a missing
//! `nvert + nedge` interior-dof base and a doubled blank line before the
//! `nodes` section — the teeth are real.

use fem_io::mfem::{read_mfem, MfemFile};
use fem_io::mfem_nc::{
    write_conforming_mesh_v1, write_nc_mesh, ConformingMeshV1, NcBoundary, NcElement, NcGeometry,
    NcMeshV1,
};

/// C++ MFEM 4.10 `polar-nc -no-vis -n 2` product, byte for byte
/// (`tmp/d104pnc/gold/n2.mesh`, 854 bytes).
const GOLDEN_N2: &str = "\
MFEM NC mesh v1.0

# NCMesh supported geometry types:
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
# PRISM       = 6
# PYRAMID     = 7

dimension
2

# rank attr geom ref_type nodes/children
elements
3
0 1 2 0 0 1 2
0 1 3 0 3 5 6 2
0 1 3 0 1 4 5 3

# attr geom nodes
boundary
6
1 1 0 1
2 1 2 0
3 1 5 6
2 1 6 2
1 1 1 4
3 1 4 5

# vert_id p1 p2
vertex_parents
1
3 1 2

# mesh curvature GridFunction
nodes
FiniteElementSpace
FiniteElementCollection: H1_2D_P2
VDim: 2
Ordering: 1

0 0
0.5 0
3.061617e-17 0.5
1 0
0.70710678 0.70710678
6.123234e-17 1
0.35355339 0.35355339
0.25 0
0.35355339 0.35355339
1.5308085e-17 0.25
0.53033009 0.53033009
0.38268343 0.92387953
4.5924255e-17 0.75
0.20266504 0.45266504
0.75 0
0.92387953 0.38268343
0.45266504 0.20266504
0.28701257 0.69290965
0.69290965 0.28701257

mfem_mesh_end
";

/// C++ MFEM 4.10 `polar-nc -no-vis -n 1` product, byte for byte
/// (`tmp/d104pnc/gold/n1.mesh`, 440 bytes).  `-n 1` never calls
/// `AddVertexParents`, so the C++ mesh stays conforming and `Mesh::Print`
/// writes the plain `MFEM mesh v1.0` container — no `mfem_mesh_end`.
const GOLDEN_N1: &str = "\
MFEM mesh v1.0

#
# MFEM Geometry Types (see fem/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
# PRISM       = 6
# PYRAMID     = 7
#

dimension
2

elements
1
1 2 0 1 2

boundary
3
1 1 0 1
3 1 1 2
2 1 2 0

vertices
3

nodes
FiniteElementSpace
FiniteElementCollection: H1_2D_P2
VDim: 2
Ordering: 1

0 0
1 0
6.123234e-17 1
0.5 0
0.70710678 0.70710678
3.061617e-17 0.5
";

/// The `-n 2` C++ artifact's records (element/boundary/parent blocks
/// transcribed from the golden; GridFunction values are the golden's own
/// 8-digit literals — see the module header for why transcription is exact).
fn golden_n2_document() -> NcMeshV1 {
    let v = |s: &str| -> f64 { s.parse().expect("literal") };
    let mut values: Vec<f64> = Vec::new();
    for row in [
        ["0", "0"],
        ["0.5", "0"],
        ["3.061617e-17", "0.5"],
        ["1", "0"],
        ["0.70710678", "0.70710678"],
        ["6.123234e-17", "1"],
        ["0.35355339", "0.35355339"],
        ["0.25", "0"],
        ["0.35355339", "0.35355339"],
        ["1.5308085e-17", "0.25"],
        ["0.53033009", "0.53033009"],
        ["0.38268343", "0.92387953"],
        ["4.5924255e-17", "0.75"],
        ["0.20266504", "0.45266504"],
        ["0.75", "0"],
        ["0.92387953", "0.38268343"],
        ["0.45266504", "0.20266504"],
        ["0.28701257", "0.69290965"],
        ["0.69290965", "0.28701257"],
    ] {
        values.push(v(row[0]));
        values.push(v(row[1]));
    }
    NcMeshV1 {
        dim: 2,
        elements: vec![
            NcElement { rank: 0, attr: 1, geom: 2, ref_type: 0, nodes: vec![0, 1, 2] },
            NcElement { rank: 0, attr: 1, geom: 3, ref_type: 0, nodes: vec![3, 5, 6, 2] },
            NcElement { rank: 0, attr: 1, geom: 3, ref_type: 0, nodes: vec![1, 4, 5, 3] },
        ],
        boundary: vec![
            NcBoundary { attr: 1, geom: 1, nodes: vec![0, 1] },
            NcBoundary { attr: 2, geom: 1, nodes: vec![2, 0] },
            NcBoundary { attr: 3, geom: 1, nodes: vec![5, 6] },
            NcBoundary { attr: 2, geom: 1, nodes: vec![6, 2] },
            NcBoundary { attr: 1, geom: 1, nodes: vec![1, 4] },
            NcBoundary { attr: 3, geom: 1, nodes: vec![4, 5] },
        ],
        vertex_parents: vec![[3, 1, 2]],
        geometry: NcGeometry::NodesGf {
            collection: "H1_2D_P2".into(),
            vdim: 2,
            ordering: 1,
            values,
        },
        precision: 8,
    }
}

/// The `-n 1` artifact's records (single ring-1 triangle, rstep = 1).
fn golden_n1_document() -> ConformingMeshV1 {
    let v = |s: &str| -> f64 { s.parse().expect("literal") };
    let mut values: Vec<f64> = Vec::new();
    for row in [
        ["0", "0"],
        ["1", "0"],
        ["6.123234e-17", "1"],
        ["0.5", "0"],
        ["0.70710678", "0.70710678"],
        ["3.061617e-17", "0.5"],
    ] {
        values.push(v(row[0]));
        values.push(v(row[1]));
    }
    ConformingMeshV1 {
        dim: 2,
        elements: vec![(1, 2, vec![0, 1, 2])],
        boundary: vec![(1, 1, vec![0, 1]), (3, 1, vec![1, 2]), (2, 1, vec![2, 0])],
        n_vertices: 3,
        geometry: NcGeometry::NodesGf {
            collection: "H1_2D_P2".into(),
            vdim: 2,
            ordering: 1,
            values,
        },
        precision: 8,
    }
}

/// The NC writer reproduces the C++ `-n 2` product byte for byte.
#[test]
fn nc_writer_reproduces_mfem_polar_nc_n2_byte_for_byte() {
    let mut out = Vec::new();
    write_nc_mesh(&mut out, &golden_n2_document()).unwrap();
    assert_eq!(out.len(), GOLDEN_N2.len(), "byte count");
    assert_eq!(String::from_utf8(out).unwrap(), GOLDEN_N2);
}

/// The conforming fallback writer reproduces the C++ `-n 1` product byte for
/// byte (hanging-free mesh → plain `MFEM mesh v1.0`, no `mfem_mesh_end`).
#[test]
fn conforming_writer_reproduces_mfem_polar_nc_n1_byte_for_byte() {
    let mut out = Vec::new();
    write_conforming_mesh_v1(&mut out, &golden_n1_document()).unwrap();
    assert_eq!(out.len(), GOLDEN_N1.len(), "byte count");
    assert_eq!(String::from_utf8(out).unwrap(), GOLDEN_N1);
}

/// Straight (`coordinates`) NC output at the stream precision: the subnormal
/// `cos(pi/2)` renders as `6.123234e-18` (`%.{prec}g`), zero renders as `0`.
#[test]
fn nc_straight_coordinates_rendering() {
    let doc = NcMeshV1 {
        dim: 2,
        elements: vec![NcElement { rank: 0, attr: 1, geom: 2, ref_type: 0, nodes: vec![0, 1, 2] }],
        boundary: vec![NcBoundary { attr: 1, geom: 1, nodes: vec![0, 1] }],
        vertex_parents: vec![],
        geometry: NcGeometry::Coordinates {
            space_dim: 2,
            coords: vec![
                0.0,
                0.0,
                0.1,
                0.0,
                6.123233995736766e-18,
                0.1,
            ],
        },
        precision: 8,
    };
    let mut out = Vec::new();
    write_nc_mesh(&mut out, &doc).unwrap();
    let text = String::from_utf8(out).unwrap();
    let tail = "\
# top-level node coordinates
coordinates
3
2
0 0
0.1 0
6.123234e-18 0.1

mfem_mesh_end
";
    assert!(text.ends_with(tail), "tail mismatch:\n{text}");
}

/// Write → read round trip through the crate's own conforming reader: the
/// `-n 1` document's topology survives (the reader owns the `MFEM mesh v1.0`
/// container; the NC container has no fem-rs reader — see the next test).
#[test]
fn written_conforming_mesh_round_trips_through_reader() {
    let mut out = Vec::new();
    write_conforming_mesh_v1(&mut out, &golden_n1_document()).unwrap();
    let MfemFile { mesh2d, .. } = read_mfem(out.as_slice()).ok().expect("read succeeds");
    let mesh = mesh2d.expect("2-D mesh");
    assert_eq!(mesh.coords.len(), 6, "3 vertices × 2 components");
    assert_eq!(mesh.conn, vec![0, 1, 2]);
    assert_eq!(mesh.elem_tags, vec![1]);
    assert_eq!(mesh.face_conn, vec![0, 1, 1, 2, 2, 0]);
    assert_eq!(mesh.face_tags, vec![1, 3, 2]);
}

/// The NC container is outside the conforming reader's contract — pin the
/// current loud refusal so a silent mis-parse can never creep in.  (Reader
/// behaviour is the 106-ledger's domain; this only records the boundary.)
#[test]
fn nc_header_is_refused_by_the_conforming_reader() {
    let err = match read_mfem(GOLDEN_N2.as_bytes()) {
        Err(err) => err,
        Ok(_) => panic!("NC header must be refused by the conforming reader"),
    };
    assert!(err.to_string().contains("expected 'MFEM mesh' header"), "{err}");
}

/// Writer validation teeth: a refined NC tree (`ref_type != 0`), a nonzero
/// serial rank, a wrong node count, and a degenerate precision are refused
/// rather than emitted (MFEM would misread them).
#[test]
fn writer_refuses_out_of_subset_documents() {
    let mut refined = golden_n2_document();
    refined.elements[0].ref_type = 7;
    assert!(write_nc_mesh(&mut Vec::new(), &refined).is_err(), "ref_type");

    let mut ranked = golden_n2_document();
    ranked.elements[0].rank = 3;
    assert!(write_nc_mesh(&mut Vec::new(), &ranked).is_err(), "rank");

    let mut short = golden_n2_document();
    short.elements[1].nodes.pop();
    assert!(write_nc_mesh(&mut Vec::new(), &short).is_err(), "node count");

    let mut prec = golden_n2_document();
    prec.precision = 0;
    assert!(write_nc_mesh(&mut Vec::new(), &prec).is_err(), "precision");

    let mut ordering = golden_n1_document();
    if let NcGeometry::NodesGf { ordering: o, .. } = &mut ordering.geometry {
        *o = 7;
    }
    assert!(write_conforming_mesh_v1(&mut Vec::new(), &ordering).is_err(), "ordering");
}
