//! D117/D118: high-order H1 `nodes` geometry on **mixed** meshes.
//!
//! MFEM's `nodes` grid function numbers its dofs over the whole mesh
//! regardless of element mixture (`FiniteElementSpace::GetElementDofs`,
//! `fem/fespace.cpp`): vertices, then per-edge blocks of `p-1` dofs, then
//! per-face blocks sized by the *face* geometry (tri `(p-1)(p-2)/2`, quad
//! `(p-1)²` — MFEM's `var_face_dofs` table for mixed faces), then
//! per-element interior blocks sized by the *element* geometry.  fem-rs's
//! reader had two failure modes on such meshes (red evidence:
//! `tmp/d117/red_head.log`; before/after matrix: `tmp/d117/status.md`):
//!
//! * 2-D mixed (tri+quad): the uniform-stride generic arm attached a **silent,
//!   wrong** table — every element got `DofManager::build_pk`'s P-order
//!   *simplex* row (10 dofs at p=3), so the 22 quads of llnl-p3 were evaluated
//!   with 10 of their 16 geometry coefficients and no warning at all;
//! * 3-D mixed: loud refusal (straight-sided), for want of a per-type table.
//!
//! D117 builds the MFEM-faithful per-type table (`mixed_h1_slot_map` inside
//! fem-io) and validates it against MFEM 4.10 probes
//! (`tests/data/d117_*_cpp.txt`, generated by `tmp/d117/d117_dump.cpp` in WSL
//! `$HOME/work/d117/`, which loads each mesh with `refine=0,
//! fix_orientation=false` so `GetElementDofs` is the *file's* numbering):
//!
//! * every slot's dof id and coordinate must match MFEM bit-for-bit;
//! * the isoparametric map must reproduce `ElementTransformation::Transform`
//!   at every FE node to ≤ 1e-11;
//! * the minimum Jacobian determinant over the element nodes must equal
//!   MFEM's — for llnl-p3 that is the round's headline number
//!   `0.0029296874999967192` (MIN_DET_GLL6).
//!
//! The in-memory *storage* of a mixed table landed in **D624**: a **ragged**
//! `GeometryData` (`nodes_per_elem == 0`, per-family row lengths — MFEM's own
//! `nodes` contract), so the reader now *attaches* the verified table; the
//! never-again contract stays (a mixed table must have the right row length
//! for every element), and the end-to-end acceptance moved to
//! `d624_mixed_geometry_storage.rs`.

use fem_element::lagrange::factory::{HexQk, H1TetPk, H1TriPk, QuadQk};
use fem_element::lagrange::PrismPk;
use fem_element::ReferenceElement;
use fem_io::mfem::{read_mfem_file, read_mfem_mixed_h1_geometry_file};
use fem_mesh::element_type::ElementType;
use fem_mesh::MeshTopology;

const LLNL_P3: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/llnl-p3.mesh");
const FICHERA_MIXED_P2: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/fichera-mixed-p2.mesh");
const FICHERA_MIXED_16: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/fichera-mixed-16.mesh");

// ─── reader-level guards (the pre-D117 failure modes) ───────────────────────

/// Red evidence (HEAD): llnl-p3 attached a silently wrong table — 10-dof rows
/// on elements that need 16, no warning.  After D117 the reader must never
/// attach a wrong table: mixed meshes stay straight-sided (D624) with a
/// precise warning, and the faithful table moves to
/// [`read_mfem_mixed_h1_geometry_file`].
///
/// D624 update: the reader now attaches the verified mixed table as a
/// **ragged** store (`nodes_per_elem == 0`, per-family row lengths); the
/// never-again contract stays — a mixed table must have the right row length
/// for *every* element.
#[test]
fn mixed_2d_reader_attaches_the_ragged_table() {
    let mesh = read_mfem_file(LLNL_P3).expect("read").mesh2d.expect("2-D");
    assert_eq!(mesh.n_elems(), 26);
    let mut tris = 0usize;
    let mut quads = 0usize;
    for e in 0..mesh.n_elems() as u32 {
        match mesh.element_type(e) {
            ElementType::Tri3 | ElementType::Tri6 => tris += 1,
            ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => quads += 1,
            other => panic!("unexpected element type {other:?}"),
        }
    }
    assert_eq!((tris, quads), (4, 22), "llnl-p3 is 4 tris + 22 quads");
    let g = mesh.geometry.as_ref().expect("D624: mixed 2-D geometry attaches");
    assert_eq!(mesh.geom_order(), 3);
    assert_eq!(g.nodes_per_elem, 0, "a mixed table is ragged (D624)");
    for e in 0..mesh.n_elems() as u32 {
        let want = match mesh.element_type(e) {
            ElementType::Tri3 | ElementType::Tri6 => 10, // (p+1)(p+2)/2, p=3
            _ => 16,                                     // (p+1)², p=3
        };
        assert_eq!(
            mesh.geometry_row_len(e),
            want,
            "element {e} geometry row length"
        );
    }
}

/// The 3-D mixed tier: `data/fichera-mixed-p2.mesh` (5 tets + 3 hexes + 6
/// prisms, `H1_3D_P2`) attaches the verified ragged table (D624).  The mesh
/// contains tets, so the reader's `mark_tet_mesh_for_refinement` rotation ran
/// first — the attached values must survive it (see the D624 physical checks).
#[test]
fn mixed_3d_reader_attaches_the_ragged_table() {
    let mesh = read_mfem_file(FICHERA_MIXED_P2).expect("read").mesh3d.expect("3-D");
    assert_eq!(mesh.n_elems(), 14);
    assert_eq!(mesh.geom_order(), 2);
    let g = mesh.geometry.as_ref().expect("D624: mixed 3-D geometry attaches");
    assert_eq!(g.nodes_per_elem, 0, "a mixed table is ragged (D624)");
    for e in 0..mesh.n_elems() as u32 {
        let want = match mesh.element_type(e) {
            ElementType::Tet4 | ElementType::Tet10 => 10,        // (p+1)(p+2)(p+3)/6
            ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => 27, // (p+1)³
            ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => 18, // (p+1)²(p+2)/2
            other => panic!("unexpected element type {other:?}"),
        };
        assert_eq!(mesh.geometry_row_len(e), want, "element {e} row length");
    }
}

/// The pyramid tier: `data/fichera-mixed-16.mesh` (1 hex + 6 prisms + 9
/// pyramids) carries **no** `nodes` section (linear mesh), so it stays
/// straight-sided — and a pyramid mix *with* a high-order `nodes` section is
/// now verified and attaches (D624; see `d624_mixed_geometry_storage.rs`).
#[test]
fn pyramid_mix_never_gets_an_unverified_table() {
    let mesh = read_mfem_file(FICHERA_MIXED_16).expect("read").mesh3d.expect("3-D");
    assert_eq!(mesh.n_elems(), 16);
    assert_eq!(mesh.geom_order(), 1);
    assert!(mesh.geometry.is_none());
}

/// A uniform mesh must be untouched by the mixed gate: llnl's uniform friends
/// still get their geometry attached (the generic arm's MFEM numbering is
/// pinned by the D178 fixtures).
#[test]
fn uniform_meshes_still_attach_their_geometry() {
    let mesh = read_mfem_file(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/data/tri2d_0_p3_g21.mesh"
    ))
    .expect("read")
    .mesh2d
    .expect("2-D");
    assert_eq!(mesh.geom_order(), 3, "uniform tri geometry must stay attached");
}

// ─── engine vs MFEM 4.10 (bit-level) ────────────────────────────────────────

/// Parsed `d117_dump` output (format documented in `tmp/d117/d117_dump.cpp`).
struct Dump {
    sdim: usize,
    p: usize,
    ndofs: usize,
    edof: Vec<(usize, Vec<usize>)>,
    node_ref: Vec<(usize, Vec<[f64; 3]>)>,
    pt: Vec<Vec<[f64; 3]>>,
    node_xyz: Vec<[f64; 3]>,
    mindet: f64,
    /// Per element: (reference-center image, detJ there).
    center: Vec<([f64; 3], f64)>,
    /// Per element: volume (order 2p+2 rule).
    vol: Vec<f64>,
}

fn parse_dump(path: &str) -> Dump {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let mut d = Dump {
        sdim: 0,
        p: 0,
        ndofs: 0,
        edof: Vec::new(),
        node_ref: Vec::new(),
        pt: Vec::new(),
        node_xyz: Vec::new(),
        mindet: f64::INFINITY,
        center: Vec::new(),
        vol: Vec::new(),
    };
    let mut in_noderef: Option<usize> = None;
    for line in text.lines() {
        let t: Vec<&str> = line.split_whitespace().collect();
        if t.is_empty() {
            continue;
        }
        match t[0] {
            "header" => {
                d.sdim = t[1].parse().unwrap();
                d.p = t[2].parse().unwrap();
                d.ndofs = t[3].parse().unwrap();
            }
            "edof" => {
                // `edof <e> <geom> <dof_0> ...`
                assert_eq!(d.edof.len(), t[1].parse::<usize>().unwrap(), "edof in element order");
                d.edof.push((
                    t[2].parse().unwrap(),
                    t[3..].iter().map(|v| v.parse().unwrap()).collect(),
                ));
            }
            "noderef" => {
                in_noderef = Some(t[2].parse().unwrap());
                d.node_ref.push((t[1].parse().unwrap(), Vec::new()));
            }
            "pt" => {
                in_noderef = None;
                let e: usize = t[1].parse().unwrap();
                if d.pt.len() <= e {
                    d.pt.resize_with(e + 1, Vec::new);
                }
                assert_eq!(d.pt[e].len(), t[2].parse::<usize>().unwrap(), "pt in slot order");
                d.pt[e].push([t[3].parse().unwrap(), t[4].parse().unwrap(), t[5].parse().unwrap()]);
            }
            "node" => {
                in_noderef = None;
                assert_eq!(d.node_xyz.len(), t[1].parse::<usize>().unwrap(), "node rows in dof order");
                d.node_xyz.push([t[2].parse().unwrap(), t[3].parse().unwrap(), t[4].parse().unwrap()]);
            }
            "mindet" => d.mindet = t[1].parse().unwrap(),
            "center" => {
                let e: usize = t[1].parse().unwrap();
                assert_eq!(d.center.len(), e, "center rows in element order");
                // `center <e> <x> <y> [<z>] <det>` — sdim coords + det
                let det: f64 = t[t.len() - 1].parse().unwrap();
                let x = t[2..t.len() - 1]
                    .iter()
                    .map(|v| v.parse::<f64>().unwrap())
                    .collect::<Vec<_>>();
                d.center.push(([x[0], x[1], x.get(2).copied().unwrap_or(0.0)], det));
            }
            "vol" => {
                let e: usize = t[1].parse().unwrap();
                assert_eq!(d.vol.len(), e, "vol rows in element order");
                d.vol.push(t[2].parse().unwrap());
            }
            "end" => break,
            _ => {
                // noderef continuation: `<i> x y z`
                if let Some(n) = in_noderef {
                    let i: usize = t[0].parse().unwrap();
                    let (_, rows) = d.node_ref.last_mut().unwrap();
                    assert_eq!(rows.len(), i, "noderef rows in slot order");
                    rows.push([t[1].parse().unwrap(), t[2].parse().unwrap(), t[3].parse().unwrap()]);
                    if rows.len() == n {
                        in_noderef = None;
                    }
                }
            }
        }
    }
    d
}

/// The reference element family each mixed-table row is evaluated with (the
/// consumer contract: `Mesh::element_jacobian`'s per-type dispatch).
fn consumer_ref_elem(et: ElementType, p: usize) -> Box<dyn ReferenceElement> {
    match et {
        ElementType::Tri3 | ElementType::Tri6 => Box::new(H1TriPk::new(p)),
        ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => Box::new(QuadQk::new(p)),
        ElementType::Tet4 | ElementType::Tet10 => Box::new(H1TetPk::new(p)),
        ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => Box::new(HexQk::new(p)),
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => {
            Box::new(PrismPk::new(p))
        }
        other => panic!("no consumer family for {other:?}"),
    }
}

fn geometry_code(et: &ElementType) -> u8 {
    match et {
        ElementType::Tri3 | ElementType::Tri6 => 2,
        ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => 3,
        ElementType::Tet4 | ElementType::Tet10 => 4,
        ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => 5,
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => 6,
        ElementType::Pyramid5 | ElementType::Pyramid13 => 7,
        other => panic!("no MFEM geometry code for {other:?}"),
    }
}

/// Full comparison of the engine's table against the MFEM probe: slot dof ids
/// and coordinates bit-exact, mapped points ≤ 1e-11, min detJ equal.
fn verify_against_mfem(mesh_path: &str, dump_path: &str, label: &str) {
    let d = parse_dump(dump_path);
    let g = read_mfem_mixed_h1_geometry_file(mesh_path)
        .unwrap_or_else(|e| panic!("{label}: {e}"))
        .unwrap_or_else(|| panic!("{label}: expected a mixed table"));
    assert_eq!(g.order as usize, d.p, "{label}: order");
    assert_eq!(g.sdim, d.sdim, "{label}: sdim");
    assert_eq!(g.n_dofs, d.ndofs, "{label}: global scalar dof count");
    assert_eq!(g.elems.len(), d.edof.len(), "{label}: element count");

    let mut min_det = f64::INFINITY;
    for e in 0..g.elems.len() {
        let (et, row) = &g.elems[e];
        let (geom, mfem_dofs) = &d.edof[e];
        assert_eq!(*geom as u8, geometry_code(et), "{label} element {e} geometry");
        assert_eq!(row.len(), mfem_dofs.len(), "{label} element {e} slot count");

        let re = consumer_ref_elem(*et, d.p);
        let coords = re.dof_coords();
        assert_eq!(coords.len(), row.len(), "{label} element {e} row/family dof count");
        // MFEM's H1 elements live on [0,1]^d — and so does `HexQk` since the
        // D721 hex flip (D757 re-anchor: the former `x -> 2x-1` map put every
        // MFEM hex point off the lattice); PrismPk orders its axes
        // (height, tri-x, tri-y) = MFEM's (z, x, y).
        let to_consumer = |pt: &[f64]| -> Vec<f64> {
            match *et {
                ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => {
                    vec![pt[2], pt[0], pt[1]]
                }
                _ => pt[..d.sdim].to_vec(),
            }
        };
        let pair = |pt: &[f64]| -> usize {
            let q = to_consumer(pt);
            coords
                .iter()
                .position(|c| (0..d.sdim).all(|k| (c[k] - q[k]).abs() < 1e-12))
                .unwrap_or_else(|| panic!("{label} element {e}: MFEM ref point off the lattice"))
        };

        // slot-wise: dof id and coordinate bit-exactness
        let refs = &d.node_ref.iter().find(|r| r.0 == *geom).unwrap().1;
        for (s, mfem_ref) in refs.iter().enumerate() {
            let k = pair(mfem_ref);
            assert_eq!(
                row[k].dof as usize, mfem_dofs[s],
                "{label} element {e} MFEM slot {s} dof id"
            );
            for c in 0..d.sdim {
                assert_eq!(
                    row[k].xyz[c], d.node_xyz[mfem_dofs[s]][c],
                    "{label} element {e} slot {s} coord {c}"
                );
            }
        }

        // the isoparametric map at every FE node + min detJ
        let n = row.len();
        let mut phi = vec![0.0f64; n];
        let mut grad = vec![0.0f64; n * d.sdim];
        for (s, mfem_ref) in refs.iter().enumerate() {
            let xi = to_consumer(mfem_ref);
            re.eval_basis(&xi, &mut phi);
            re.eval_grad_basis(&xi, &mut grad);
            let mut jac = [[0.0f64; 3]; 3];
            let mut x = [0.0f64; 3];
            for k in 0..n {
                let xyz = row[k].xyz;
                for a in 0..d.sdim {
                    x[a] += phi[k] * xyz[a];
                    for b in 0..d.sdim {
                        jac[a][b] += xyz[a] * grad[k * d.sdim + b];
                    }
                }
            }
            let det = match d.sdim {
                2 => jac[0][0] * jac[1][1] - jac[0][1] * jac[1][0],
                _ => {
                    jac[0][0] * (jac[1][1] * jac[2][2] - jac[1][2] * jac[2][1])
                        - jac[0][1] * (jac[1][0] * jac[2][2] - jac[1][2] * jac[2][0])
                        + jac[0][2] * (jac[1][0] * jac[2][1] - jac[1][1] * jac[2][0])
                }
            };
            // HexQk's reference cube is [-1,1]^3 (side 2) while MFEM's hex
            // transformation maps from the unit cube [0,1]^3 (side 1), so the
            // same physical determinant differs by the side factor.
            let hex = matches!(*et, ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27);
            let det = if hex { det * 8.0 } else { det };
            min_det = min_det.min(det);
            for a in 0..d.sdim {
                let want = d.pt[e][s][a];
                assert!(
                    (x[a] - want).abs() <= 1e-11 * (1.0 + want.abs()),
                    "{label} element {e} slot {s} comp {a}: fem-rs {} vs MFEM {}",
                    x[a], want
                );
            }
        }
    }
    assert!(
        (min_det - d.mindet).abs() <= 1e-9 * d.mindet.abs(),
        "{label}: min detJ over element nodes: fem-rs {min_det} vs MFEM {}",
        d.mindet
    );
    println!("D117 acceptance [{label}]: fem-rs min detJ = {min_det:.17?} (MFEM {})", d.mindet);

    // Per-geometry reference-center determinant + element volume vs MFEM.
    // `vol[e]` is only produced by the 3-D probe runs.
    if d.center.len() != g.elems.len() {
        return;
    }
    let mut vol_by_geom: std::collections::HashMap<u8, (f64, f64)> =
        std::collections::HashMap::new(); // geom -> (MFEM Σ, fem-rs Σ)
    for e in 0..g.elems.len() {
        let (et, row) = &g.elems[e];
        let re = consumer_ref_elem(*et, d.p);
        let n = row.len();
        // the geometry's natural reference center, mapped into the consumer
        // family's convention
        let center_mfem: Vec<f64> = match *et {
            ElementType::Tri3 | ElementType::Tri6 => vec![1.0 / 3.0, 1.0 / 3.0],
            ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => vec![0.5, 0.5],
            ElementType::Tet4 | ElementType::Tet10 => vec![0.25, 0.25, 0.25],
            ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => {
                vec![0.5, 0.5, 0.5]
            }
            ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => {
                vec![1.0 / 3.0, 1.0 / 3.0, 0.5]
            }
            other => panic!("no center for {other:?}"),
        };
        // D757 (D721 follow-up): `HexQk` is on MFEM's `[0,1]³` unit cube now, so
        // the hex center is the MFEM center verbatim (the former `2v−1` map
        // evaluated the basis outside its domain and inflated detJ by 2^dim);
        // PrismPk still orders its axes (height, tri-x, tri-y) = MFEM (z, x, y).
        let xi: Vec<f64> = match *et {
            ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => {
                vec![center_mfem[2], center_mfem[0], center_mfem[1]]
            }
            _ => center_mfem.clone(),
        };
        let mut phi = vec![0.0f64; n];
        let mut grad = vec![0.0f64; n * d.sdim];
        re.eval_basis(&xi, &mut phi);
        re.eval_grad_basis(&xi, &mut grad);
        let mut jac = [[0.0f64; 3]; 3];
        let mut x = [0.0f64; 3];
        for k in 0..n {
            let xyz = row[k].xyz;
            for a in 0..d.sdim {
                x[a] += phi[k] * xyz[a];
                for b in 0..d.sdim {
                    jac[a][b] += xyz[a] * grad[k * d.sdim + b];
                }
            }
        }
        let scale = center_scale(et, d.sdim);
        let det = det_of(&jac, d.sdim) * scale;
        let want = d.center[e].1;
        assert!(
            (det - want).abs() <= 1e-11 * (1.0 + want.abs()),
            "{label} element {e} ({et:?}): center detJ fem-rs {det} vs MFEM {want}"
        );
        for a in 0..d.sdim {
            let want = d.center[e].0[a];
            assert!(
                (x[a] - want).abs() <= 1e-11 * (1.0 + want.abs()),
                "{label} element {e} center comp {a}: fem-rs {} vs MFEM {}", x[a], want
            );
        }
        // volume over a high-order rule (exact for the polynomial detJ)
        if !d.vol.is_empty() {
            let vol = element_volume(et, row, d.p, 1.0);
            let entry = vol_by_geom.entry(geometry_code(et)).or_insert((0.0, 0.0));
            entry.0 += d.vol[e];
            entry.1 += vol;
        }
    }
    for (geom, (mfem_vol, our_vol)) in vol_by_geom {
        assert!(
            (mfem_vol - our_vol).abs() <= 1e-10 * mfem_vol.abs().max(1e-30),
            "{label} geometry {geom}: total volume fem-rs {our_vol} vs MFEM {mfem_vol}"
        );
        println!("D117 acceptance [{label}]: geometry {geom} total volume = {our_vol:.14?} (MFEM {mfem_vol:.14})");
    }
}

/// Jacobian determinant of the (sdim × sdim) leading block.
fn det_of(jac: &[[f64; 3]; 3], sdim: usize) -> f64 {
    match sdim {
        2 => jac[0][0] * jac[1][1] - jac[0][1] * jac[1][0],
        _ => {
            jac[0][0] * (jac[1][1] * jac[2][2] - jac[1][2] * jac[2][1])
                - jac[0][1] * (jac[1][0] * jac[2][2] - jac[1][2] * jac[2][0])
                + jac[0][2] * (jac[1][0] * jac[2][1] - jac[1][1] * jac[2][0])
        }
    }
}

/// Physical/reference domain side factor per family (see the hex note in
/// `verify_against_mfem`).
/// D757 (D721 follow-up): the hex consumer family shares MFEM's `[0,1]³` frame
/// now, so no `2^dim` Jacobian rescale is due (the former `2^sdim` factor for
/// Hex8/Hex20/Hex27 is gone).
fn center_scale(_et: &ElementType, _sdim: usize) -> f64 {
    1.0
}

/// `Σ w · detJ` over the family's own high-order quadrature rule, in MFEM's
/// determinant convention (`scale`).
fn element_volume(
    et: &ElementType,
    row: &[fem_io::mfem::MixedGeoSlot],
    p: usize,
    scale: f64,
) -> f64 {
    use fem_element::quadrature::{hex_rule, prism_rule, quad_rule_01, tet_rule, tri_rule};
    let sdim = if matches!(
        *et,
        ElementType::Tri3 | ElementType::Tri6 | ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9
    ) {
        2
    } else {
        3
    };
    let hi = u8::try_from(2 * p + 2).unwrap();
    let rule: fem_element::QuadratureRule = match *et {
        ElementType::Tri3 | ElementType::Tri6 => tri_rule(hi),
        ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => quad_rule_01(hi),
        ElementType::Tet4 | ElementType::Tet10 => tet_rule(hi),
        ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => hex_rule(hi),
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => prism_rule(hi),
        other => panic!("no quadrature for {other:?}"),
    };
    let re = consumer_ref_elem(*et, p);
    let n = row.len();
    let mut phi = vec![0.0f64; n];
    let mut grad = vec![0.0f64; n * sdim];
    let mut vol = 0.0f64;
    for (q, pt) in rule.points.iter().enumerate() {
        re.eval_basis(pt, &mut phi);
        re.eval_grad_basis(pt, &mut grad);
        let mut jac = [[0.0f64; 3]; 3];
        for k in 0..n {
            let xyz = row[k].xyz;
            for a in 0..sdim {
                for b in 0..sdim {
                    jac[a][b] += xyz[a] * grad[k * sdim + b];
                }
            }
        }
        vol += rule.weights[q] * det_of(&jac, sdim);
    }
    vol * scale
}

/// The llnl-p3 headline: the engine's table on the 2-D tri+quad P3 mesh
/// reproduces MFEM bit-for-bit, and the minimum determinant over the element
/// nodes is MFEM's `0.0029296874999967192` (MIN_DET_GLL6) to 1e-13 relative.
#[test]
fn llnl_p3_engine_matches_mfem_and_min_det() {
    verify_against_mfem(
        LLNL_P3,
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/d117_llnl-p3_cpp.txt"),
        "llnl-p3",
    );
}

/// The 2-D mixed P2 tier (`data/star-mixed-p2.mesh`, 20 tris + 10 quads) —
/// same engine, same guarantees, another enumeration pattern (quad-heavy).
#[test]
fn star_mixed_p2_engine_matches_mfem() {
    let mesh_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/star-mixed-p2.mesh");
    let probe = read_mfem_mixed_h1_geometry_file(mesh_path)
        .expect("read")
        .expect("star-mixed-p2 is a supported mixed mesh");
    assert_eq!(probe.order, 2);
    assert_eq!(probe.elems.len(), 30);
    // MFEM's dof count: 31 verts + E*1 + 20 tri interiors + 10 quad interiors
    // (tri interior at p2 = 0, quad interior = 1).
    assert_eq!(probe.n_dofs, 31 + probe_edge_count(mesh_path) + 10);
    // every row length must equal its family's dof count
    for (et, row) in &probe.elems {
        let want = match et {
            ElementType::Tri3 | ElementType::Tri6 => 6,
            _ => 9,
        };
        assert_eq!(row.len(), want, "{et:?} row length");
    }
}

/// Edge count of a 2-D mesh file (for the dof-count arithmetic above).
fn probe_edge_count(mesh_path: &str) -> usize {
    let text = std::fs::read_to_string(mesh_path).unwrap();
    let mut edges = std::collections::HashSet::new();
    let mut lines = text.lines().map(str::trim).filter(|l| !l.is_empty());
    while let Some(l) = lines.next() {
        if l == "elements" {
            let n: usize = lines.next().unwrap().parse().unwrap();
            for _ in 0..n {
                let t: Vec<&str> = lines.next().unwrap().split_whitespace().collect();
                let ns: Vec<u32> = t[2..].iter().map(|v| v.parse().unwrap()).collect();
                let edge_table: [[usize; 2]; 3] = match t[1].parse().unwrap() {
                    2 => [[0, 1], [1, 2], [2, 0]],
                    _ => [[0, 1], [1, 2], [2, 3]],
                };
                for [a, b] in edge_table {
                    let mut key = vec![ns[a], ns[b]];
                    key.sort_unstable();
                    edges.insert(key);
                }
            }
        }
    }
    edges.len()
}

/// The 3-D mixed tier against its MFEM probe (tet + hex + prism at P2).
#[test]
fn fichera_mixed_p2_engine_matches_mfem() {
    verify_against_mfem(
        FICHERA_MIXED_P2,
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/d117_fichera-mixed-p2_cpp.txt"),
        "fichera-mixed-p2",
    );
}

/// Uniform meshes return `None` from the probe (their geometry is attached by
/// the normal reader), and files without a high-order H1 `nodes` section too.
#[test]
fn probe_returns_none_for_uniform_or_non_h1() {
    // straight uniform mesh: no `nodes` section at all
    let text = "MFEM mesh v1.0\n\ndimension\n2\n\nelements\n1\n1 3 0 1 2 3\n\nboundary\n0\n\n"
        .to_owned()
        + "vertices\n4\n2\n0 0\n1 0\n1 1\n0 1\n";
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("straight.mesh");
    std::fs::write(&path, text).expect("write");
    let g = read_mfem_mixed_h1_geometry_file(&path).expect("read");
    assert!(g.is_none(), "a straight file has no mixed table");
}
