//! D236 regression: hex RT fields read from MFEM VisIt data collections must
//! be evaluated with the **nodal GaussLegendre** open basis — the element
//! `RT_FECollection(p, dim)` builds by default (`fem/fe_coll.hpp`,
//! `ob_type = BasisType::GaussLegendre`) and therefore the flavour every
//! MFEM-saved RT coefficient vector lives in — *not* the IntegratedGLL pair
//! (`HexRTk::new`), which is the LOR-only basis of MFEM `fem/lor/lor.cpp`.
//!
//! Reference: the round-40 archives `tmp/d225/dc_RT{1,2}` (single hex
//! `1.0 x 1.2 x 0.8`, unit-dof coefficient vectors `f_k` = e_k generated by
//! `tmp/d158/gen_d158_unit.cpp`) and the C++ `tools/get-values` transcripts
//! `tmp/d225/cppnow_RT{1,2}_p2.txt` (MFEM 4.10, physical point
//! `(0.65, 0.84, 0.6)`, fields in `std::map` order).  The round-40 report
//! recorded the IntegratedGLL evaluation as a 36-token (RT1) / 108-token
//! (RT2) residual against these transcripts; this test pins the
//! GaussLegendre evaluation to the same transcripts.
//!
//! The evaluation below is the get-values pipeline itself:
//! `find_points` reports `[0,1]^3` reference coordinates (D224, re-anchored by
//! D757 after the D721 hex flip), the basis is evaluated there and transformed
//! with the contravariant Piola map of the `[0,1]` isoparametric frame,
//! `phi = J psi / det J` — exactly
//! `GridFunction::evaluate_vector_at_element`'s H(div) arm.

use fem_element::raviart_thomas::{HexRTk, HexRtOpen};
use fem_element::reference::VectorReferenceElement;
use fem_io::mfem::read_mfem;
use fem_mesh::transformation::find_points;
use fem_space::HDivSpace;

const HEX_MESH: &str = "MFEM mesh v1.0

dimension
3

elements
1
1 5 0 1 3 2 4 5 7 6

boundary
6
1 3 0 2 3 1
6 3 4 5 7 6
5 3 0 4 6 2
3 3 1 3 7 5
2 3 0 1 5 4
4 3 2 6 7 3

vertices
8
3
0 0 0
1 0 0
0 1.2 0
1 1.2 0
0 0 0.8
1 0 0.8
0 1.2 0.8
1 1.2 0.8
";

/// Archived MFEM get-values values for the 36 unit-dof RT1 fields, in the
/// transcript's field order (`f0, f1, f10, ...` — `std::map` alphabetical),
/// 3 components per field (the first four transcript tokens `0 0.65 0.84 0.6`
/// are the point index/location and are dropped).
const MFEM_RT1: &str = "
0 -1.46946e-18 0.0211772  0 -4.6484e-18 0.0669905  0.0291081 0 0  0.16041 0 0
0 0.0178141 -8.24068e-19 0  0.00563144 -2.60507e-19 0  0.248119 -1.14778e-17 0
0.0784359 -3.62839e-18 0.00620142  0 0 0.00112531  0 0 0.0863747  0 0 0.0156736
0 0 0 -2.66649e-19 0.00384282  0 -7.99948e-19 0.0115285  0 -2.5305e-18 0.0364684
0 -4.40839e-18 0.0635316  0 -1.39452e-17 0.200972  0.00975271 0 0  0.0537457 0 0
0.135838 0 0  0.748581 0 0  0 0.0168943 -7.8152e-19 0  0.0534423 -2.4722e-18 0
-8.435e-19 0.0121561 0  0.235308 -1.08852e-17 0  0.744356 -3.44334e-17 0
-1.5999e-18 0.0230569 0  -5.061e-18 0.0729367 0  -8.81679e-18 0.127063 0
-2.78904e-17 0.401943 0  0.00241348 -1.11646e-19 0  0.00763462 -3.53172e-19 0
0.0336154 -1.55502e-18 0  0.106337 -4.91905e-18 0.00208987  0 0 0.0115169 0 0
";

/// Archived MFEM get-values values for the 108 unit-dof RT2 fields (same
/// conventions as [`MFEM_RT1`]).
const MFEM_RT2: &str = "
0 -4.19722e-20 0.000604882  0 3.00688e-19 -0.00433336  0 -0.00182349 8.43535e-20
0 6.09319e-18 -0.0878121  0 1.9258e-18 -0.0277537  0 4.99516e-18 -0.0719878
0 -3.57852e-17 0.515719  0 -1.13102e-17 0.162997  0 2.66695e-18 -0.0384348
0 -1.9106e-17 0.275346  0 -6.0386e-18 0.0870254  0 -0.000576329 2.66606e-20 0
-0.00129773 6.00319e-20 0  0.00929687 -4.30067e-19 0  0.00293835 -1.35926e-19 0
-0.00118148 5.46546e-20 0  0.00846412 -3.91544e-19 0  0.00267515 -1.23751e-19
-0.00133006 0 0  0.00781143 0 0  0 9.50347e-20 -0.00136959  0.00417058 0 0
0.00678116 0 0  -0.0398257 0 0  -0.0212632 0 0  0.00617375 0 0  -0.0362583 0 0
-0.0193586 0 0  0 0.00134477 -6.2208e-20 0  0.00425482 -1.96825e-19 0
-0.000593918 2.74742e-20 0  -7.86131e-20 0.00113293 0  -0.00685615 3.17161e-19 0
-0.0216927 1.00349e-18 0  0.00302803 -1.40074e-19 0  -0.00624202 2.88751e-19 0
-0.0197496 9.13603e-19 0  0.00275679 -1.27527e-19 -0.0022457 0 0  -0.00420615 0 0
0.000716187 0 0  0.0114494 0 0  0 5.63183e-19 -0.00811632  0.0214446 0 0
-0.0036514 0 0  0.0104239 0 0  0.0195237 0 0  -0.00332433 0 0
0 -4.01567e-20 0.000578719  0 2.87681e-19 -0.00414593  0 9.0924e-20 -0.00131035
0 2.35839e-19 -0.0033988  0 -1.68955e-18 0.024349  0 1.77998e-19 -0.00256523 0
-5.33995e-19 0.00769568 0  1.25916e-19 -0.00181465 0  -9.02063e-19 0.0130001 0
-2.85104e-19 0.00410878 -0.00278618 0 0  0.0141419 0 0  0.0163632 0 0
-0.0830549 0 0  0.00873644 0 0  -0.0443437 0 0  0 1.33856e-20 -0.000192906
0.014205 0 0  -0.0721007 0 0  -0.083426 0 0  0.423446 0 0  -0.0445418 0 0
0.226081 0 0  0.0129326 0 0  -0.0656424 0 0  -0.0759532 0 0  0.385516 0 0
0 -9.58938e-20 0.00138198 -0.040552 0 0  0.20583 0 0  0 -0.000940524 4.3508e-20 0
0.0067379 -3.1169e-19 0  0.00212957 -9.85122e-20 0  0.016877 -7.80719e-19 0
-0.120907 5.59306e-18 0  -0.0382135 1.76773e-18 0  0.00479516 -2.21821e-19 0
-0.0343524 1.58912e-18 0  -3.0308e-20 0.000436784 0  -0.0108573 5.02253e-19 0
-0.0860456 3.98041e-18 0  0.616429 -2.85156e-17 0  0.194827 -9.01257e-18 0
0.00436564 -2.01951e-19 0  -0.0312753 1.44677e-18 0  -0.00988481 4.57264e-19 0
-0.0783382 3.62387e-18 0  0.561213 -2.59613e-17 0  0.177376 -8.20528e-18 0
0.000254536 -1.17747e-20 0  -4.73985e-20 0.000683085  0 3.39562e-19 -0.0048936 0
1.07321e-19 -0.00154666 0  2.78371e-19 -0.00401174 0  -1.99424e-18 0.02874 0
-6.30296e-19 0.00908352 0  1.48624e-19 -0.0021419 0  -1.06474e-18 0.0153445 0
-3.3652e-19 0.00484976 0  -8.50532e-19 0.0122575
";

fn hex_mesh() -> fem_mesh::Mesh<3> {
    read_mfem(HEX_MESH.as_bytes())
        .expect("hex mesh parses")
        .mesh3d
        .expect("expected a 3-D mesh")
}

/// Evaluate every unit-dof field of an HDiv `RT_k` space at the transcript
/// point with the given open-basis variant and return the values in the
/// transcript's field order (`std::map` alphabetical), 3 components per
/// field — the same layout as the archived MFEM token tables.
fn unit_field_values<const N: usize>(open: HexRtOpen) -> Vec<f64> {
    let mesh = hex_mesh();
    let sp = HDivSpace::new(mesh.clone(), N as u8);
    let n = sp.n_dofs();
    assert_eq!(n, 3 * (N + 1) * (N + 1) * (N + 2));
    assert_eq!(sp.element_dofs(0), &(0..n as u32).collect::<Vec<_>>()[..]);
    assert!(sp.element_signs(0).iter().all(|&s| s == 1.0));

    // find_points reports `[0,1]^3` reference coordinates on hexes since D721
    // (`to_factory_coords` became the identity); the basis is evaluated there
    // and transformed with the contravariant Piola map, `phi = J psi / det J` —
    // exactly `GridFunction::evaluate_vector_at_element`'s H(div) arm.
    let pt = [0.65_f64, 0.84, 0.6];
    let (elem_ids, ips) = find_points(&mesh, &pt, 1);
    assert_eq!(elem_ids[0], 0, "point must be found in the single hex");
    let xi = [ips[0][0], ips[0][1], ips[0][2]];

    let el = match open {
        HexRtOpen::GaussLegendre => HexRTk::new_gauss_legendre(N),
        HexRtOpen::IntegratedGLL => HexRTk::new(N),
    };
    let mut psi = vec![0.0_f64; el.n_dofs() * 3];
    el.eval_basis_vec(&xi, &mut psi);

    // Contravariant Piola of the `[0,1]³` isoparametric hex frame (D757
    // re-anchor after D721: `HexRTk` and `find_points` both live on MFEM's
    // unit cube now, so `J = diag(h)` with the raw edge lengths
    // `h = (1.0, 1.2, 0.8)` — the former `[-1,1]` frame used `h/2` and a
    // `det = 0.12` three-quarters smaller, which is the exact ×4 the transcript
    // comparison flagged).  `phi = J psi / det J`.
    let det = 1.0 * 1.2 * 0.8;
    let jscale = [1.0 / det, 1.2 / det, 0.8 / det];

    // Transcript field order: alphabetical over "f0".."f{n-1}".
    let mut order: Vec<usize> = (0..n).collect();
    order.sort_by_key(|&k| format!("f{k}"));

    let mut out = Vec::with_capacity(n * 3);
    for &k in &order {
        for c in 0..3 {
            out.push(jscale[c] * psi[k * 3 + c]);
        }
    }
    out
}

fn check_against_mfem<const N: usize>(mfem_tokens: &str, tag: &str) {
    let want: Vec<f64> = mfem_tokens
        .split_whitespace()
        .map(|t| t.parse::<f64>().expect("token parses"))
        .collect();
    let got = unit_field_values::<N>(HexRtOpen::GaussLegendre);
    assert_eq!(got.len(), want.len(), "{tag}: token count");
    let mut worst = 0.0_f64;
    for (i, (&g, &w)) in got.iter().zip(want.iter()).enumerate() {
        let diff = (g - w).abs();
        // The transcripts carry 6 significant digits; "0" tokens are exact
        // structural zeros on both sides.
        assert!(
            diff <= 1e-5 * (1.0 + w.abs()) + 1e-12,
            "{tag} token {i}: fem-rs {g} vs mfem {w}"
        );
        worst = worst.max(diff);
    }
    println!("{tag}: max |diff| = {worst:.3e} over {} tokens", want.len());
}

/// RT1: all 36 unit-dof fields at the generic point match the MFEM 4.10
/// get-values transcript (the round-40 36-token IntegratedGLL residual).
#[test]
fn rt1_unit_fields_match_mfem_get_values() {
    check_against_mfem::<1>(MFEM_RT1, "RT1 nodal-GL");
}

/// RT2: all 108 unit-dof fields at the generic point match the MFEM 4.10
/// get-values transcript (the round-40 108-token IntegratedGLL residual).
#[test]
fn rt2_unit_fields_match_mfem_get_values() {
    check_against_mfem::<2>(MFEM_RT2, "RT2 nodal-GL");
}
