//! D624: mixed-mesh high-order H1 geometry **storage** — the ragged
//! `GeometryData` (`nodes_per_elem == 0`, per-family row lengths).
//!
//! The D117 round delivered the MFEM-verified mixed slot map
//! (`mixed_h1_slot_map` + the `read_mfem_mixed_h1_geometry_file` probe) but
//! the reader could not *store* a mixed table: `GeometryData` had a single
//! uniform stride.  D624 lands the storage and flips `build_h1_geometry`'s
//! mixed gate from "precise warning + straight-sided" to **attach**.
//!
//! Acceptance (MFEM 4.10 probe truth, `tmp/d117/d117_dump.cpp` runs in WSL
//! `$HOME/work/{d117,d624}/`; 2-D and tet+hex+prism fixtures from D117, the
//! hex+prism+pyramid fixture generated by MFEM itself via
//! `SetCurvature(2)` + `Save`):
//!
//! * `llnl-p3` (2-D tri+quad P3): the attached table's min detJ over the FE
//!   nodes equals MFEM's `0.0029296874999965726`, and the reader's
//!   "wrong orientation 15/26" report drops to zero (the CW-in-straight
//!   quads are positively oriented in their curved geometry);
//! * `fichera-mixed-p2` (tet+hex+prism P2): the geometry survives the
//!   reader's `mark_tet_mesh_for_refinement` rotation — per-element physical
//!   node sets match the file-frame probe bit-for-bit, min detJ
//!   `0.35384952876017473` is kept;
//! * `fichera-mixed-16-p2` (hex+prism+pyramid P2, **new** fixture generated
//!   by MFEM's own `SetCurvature`): reads curved (was loud-refused before
//!   D624) — the Fuentes-pyramid rows pin the pyramid numbering end-to-end,
//!   volumes match the probe per element;
//! * uniform meshes and AMR: a refinement of the curved llnl-p3 keeps the
//!   mixed geometry (children interpolate the parent map).

use fem_element::lagrange::factory::{HexQk, H1TetPk, H1TriPk, QuadQk};
use fem_element::lagrange::PrismPk;
use fem_element::ReferenceElement;
use fem_io::mfem::{read_mfem_file, read_mfem_mixed_h1_geometry_file};
use fem_mesh::element_type::ElementType;
use fem_mesh::MeshTopology;

const LLNL_P3: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/llnl-p3.mesh");
const FICHERA_MIXED_P2: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/fichera-mixed-p2.mesh");
const FICHERA_MIXED_16_P2: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/fichera-mixed-16-p2.mesh");
const LLNL_P3_TRUTH: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/d117_llnl-p3_cpp.txt");
const FICHERA_P2_TRUTH: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/d117_fichera-mixed-p2_cpp.txt");
const FICHERA_16_P2_TRUTH: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/d624_fichera-mixed-16-p2_cpp.txt");

/// The reference element family each mixed-table row is evaluated with (the
/// consumer contract: `Mesh::element_jacobian`'s per-type dispatch).
fn consumer_ref_elem(et: ElementType, p: usize) -> Box<dyn ReferenceElement> {
    match et {
        ElementType::Tri3 | ElementType::Tri6 => Box::new(H1TriPk::new(p)),
        ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => Box::new(QuadQk::new(p)),
        ElementType::Tet4 | ElementType::Tet10 => Box::new(H1TetPk::new(p)),
        ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => Box::new(HexQk::new(p)),
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => {
            Box::new(PrismPk::new(p))
        }
        ElementType::Pyramid5 | ElementType::Pyramid13 => {
            // D347 consumer contract: MFEM's `SetCurvature` default (Fuentes).
            fem_element::lagrange::h1_pyramid_element(
                p,
                fem_element::lagrange::PyramidBasisType::default(),
            )
        }
        other => panic!("no consumer family for {other:?}"),
    }
}

/// MFEM reference-center of each geometry, in the *consumer* frame.
///
/// D757 (D721 follow-up): the hex consumer (`HexQk`) shares MFEM's `[0,1]³`
/// unit cube now, so the hex center is `(0.5,0.5,0.5)` verbatim — the former
/// `(0,0,0)` was the `[-1,1]³` center.
fn ref_center(et: ElementType, sdim: usize) -> Vec<f64> {
    match (et, sdim) {
        (ElementType::Tri3 | ElementType::Tri6, _) => vec![1.0 / 3.0; 2],
        (ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9, _) => vec![0.5, 0.5],
        (ElementType::Tet4 | ElementType::Tet10, _) => vec![0.25; 3],
        (ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27, _) => vec![0.5; 3],
        (ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18, _) => {
            vec![0.5, 1.0 / 3.0, 1.0 / 3.0] // PrismPk frame: (z, x, y)
        }
        (ElementType::Pyramid5 | ElementType::Pyramid13, _) => vec![0.0, 0.0, 0.25],
        _ => panic!("no center for {et:?}"),
    }
}

/// Consumer-frame reference volume (for straight elements:
/// volume = detJ(center) × this).  D757 (D721 follow-up): the hex frame is the
/// unit cube, reference volume 1, no longer `[-1,1]³`'s 8.
fn ref_volume(et: ElementType, sdim: usize) -> f64 {
    match (et, sdim) {
        (ElementType::Tri3 | ElementType::Tri6, 2) => 0.5,
        (ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9, 2) => 1.0,
        (ElementType::Tet4 | ElementType::Tet10, 3) => 1.0 / 6.0,
        (ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27, 3) => 1.0,
        (ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18, 3) => 0.5,
        (ElementType::Pyramid5 | ElementType::Pyramid13, 3) => 1.0 / 3.0,
        other => panic!("no reference volume for {other:?}"),
    }
}

/// detJ scale between the consumer frame and MFEM's `[0,1]^d` frames.
/// D757 (D721 follow-up): every consumer family — the hexahedron included —
/// now lives on MFEM's frames, so this is uniformly 1.
fn det_scale(_et: ElementType) -> f64 {
    1.0
}

/// Map an MFEM reference point into the consumer family's frame.
/// D757 (D721 follow-up): the hex is the identity now (its consumer element
/// was the last `[-1,1]³` holdout); only the prism's `(z, x, y)` axis order
/// remains.
fn to_consumer(et: ElementType, pt: &[f64], sdim: usize) -> Vec<f64> {
    match et {
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => {
            vec![pt[2], pt[0], pt[1]]
        }
        _ => pt[..sdim].to_vec(),
    }
}

// ─── probe truth (d117_dump format) ─────────────────────────────────────────

struct Probe {
    sdim: usize,
    p: usize,
    ndofs: usize,
    /// Per element: (MFEM geometry code, dof ids in MFEM slot order).
    edof: Vec<(usize, Vec<usize>)>,
    /// Per geometry: FE reference node positions (MFEM slot order).
    node_ref: Vec<(usize, Vec<[f64; 3]>)>,
    /// Per element: per-slot mapped positions.
    pt: Vec<Vec<[f64; 3]>>,
    /// Per dof: the file's stored coordinate triple.
    node_xyz: Vec<[f64; 3]>,
    mindet: f64,
    /// Per element: detJ at the reference center.
    center_det: Vec<f64>,
    /// Per element: volume (order-2p+2 rule).
    vol: Vec<f64>,
}

fn parse_probe(path: &str) -> Probe {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let mut pr = Probe {
        sdim: 0,
        p: 0,
        ndofs: 0,
        edof: Vec::new(),
        node_ref: Vec::new(),
        pt: Vec::new(),
        node_xyz: Vec::new(),
        mindet: f64::INFINITY,
        center_det: Vec::new(),
        vol: Vec::new(),
    };
    let mut in_noderef: Option<usize> = None;
    for line in text.lines() {
        let t: Vec<&str> = line.split_whitespace().collect();
        if t.is_empty() {
            continue;
        }
        match t[0] {
            "header" => {
                pr.sdim = t[1].parse().unwrap();
                pr.p = t[2].parse().unwrap();
                pr.ndofs = t[3].parse().unwrap();
            }
            "edof" => {
                assert_eq!(pr.edof.len(), t[1].parse::<usize>().unwrap(), "edof in element order");
                pr.edof
                    .push((t[2].parse().unwrap(), t[3..].iter().map(|v| v.parse().unwrap()).collect()));
            }
            "noderef" => {
                in_noderef = Some(t[2].parse().unwrap());
                pr.node_ref.push((t[1].parse().unwrap(), Vec::new()));
            }
            "pt" => {
                in_noderef = None;
                let e: usize = t[1].parse().unwrap();
                if pr.pt.len() <= e {
                    pr.pt.resize_with(e + 1, Vec::new);
                }
                assert_eq!(pr.pt[e].len(), t[2].parse::<usize>().unwrap(), "pt in slot order");
                pr.pt[e].push([t[3].parse().unwrap(), t[4].parse().unwrap(), t[5].parse().unwrap()]);
            }
            "mindet" => pr.mindet = t[1].parse().unwrap(),
            "node" => {
                assert_eq!(
                    pr.node_xyz.len(),
                    t[1].parse::<usize>().unwrap(),
                    "node rows in dof order"
                );
                pr.node_xyz.push([
                    t[2].parse().unwrap(),
                    t[3].parse().unwrap(),
                    t[4].parse().unwrap(),
                ]);
            }
            "center" => {
                let e: usize = t[1].parse().unwrap();
                assert_eq!(pr.center_det.len(), e, "center rows in element order");
                pr.center_det.push(t[t.len() - 1].parse().unwrap());
            }
            "vol" => {
                let e: usize = t[1].parse().unwrap();
                assert_eq!(pr.vol.len(), e, "vol rows in element order");
                pr.vol.push(t[2].parse().unwrap());
            }
            "end" => break,
            _ => {
                if let Some(n) = in_noderef {
                    let i: usize = t[0].parse().unwrap();
                    let (_, rows) = pr.node_ref.last_mut().unwrap();
                    assert_eq!(rows.len(), i, "noderef rows in slot order");
                    rows.push([t[1].parse().unwrap(), t[2].parse().unwrap(), t[3].parse().unwrap()]);
                    if rows.len() == n {
                        in_noderef = None;
                    }
                }
            }
        }
    }
    pr
}

fn geometry_code(et: &ElementType) -> u8 {
    match et {
        ElementType::Tri3 | ElementType::Tri6 => 2,
        ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => 3,
        ElementType::Tet4 | ElementType::Tet10 => 4,
        ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => 5,
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => 6,
        ElementType::Pyramid5 | ElementType::Pyramid13 => 7,
        other => panic!("no MFEM geometry code for {other:?}"),
    }
}

/// Sorted physical-node multiset of an element (for the frame-independent
/// comparison across the tet renumbering).
fn sorted_row_xyz(
    mesh: &fem_mesh::simplex::Mesh<3>,
    e: u32,
) -> Vec<([f64; 3], usize)> {
    let mut v: Vec<([f64; 3], usize)> = mesh
        .geometry_row(e)
        .iter()
        .map(|&g| {
            let c = mesh.geom_coords_of(g);
            ([c[0], c[1], c[2]], g as usize)
        })
        .collect();
    v.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap());
    v
}

// ─── acceptance tiers ───────────────────────────────────────────────────────

/// llnl-p3 (2-D tri+quad P3): the attached ragged table reproduces MFEM's
/// min detJ over the FE nodes, and the wrong-orientation report drops to 0
/// (red at HEAD: 15 / 26 "wrong orientation" + straight-sided geometry).
#[test]
fn d624_llnl_p3_attached_geometry_matches_mfem() {
    let mesh = read_mfem_file(LLNL_P3).expect("read").mesh2d.expect("2-D");
    let pr = parse_probe(LLNL_P3_TRUTH);
    let g = mesh.geometry.as_ref().expect("D624: ragged geometry attached");
    assert_eq!(mesh.geom_order(), 3);
    assert_eq!(g.nodes_per_elem, 0, "mixed table is ragged");

    // min detJ over every element's FE-node lattice == MFEM
    let mut min_det = f64::INFINITY;
    for e in 0..mesh.n_elems() as u32 {
        let et = mesh.element_type(e);
        let re = consumer_ref_elem(et, pr.p);
        let row = mesh.geometry_row(e).to_vec();
        assert_eq!(row.len(), re.n_dofs(), "element {e} row length");
        for c in re.dof_coords() {
            let (_j, det, _x) = mesh.element_jacobian(e, &c);
            min_det = min_det.min(det);
        }
    }
    println!("D624 llnl-p3 min detJ = {min_det:.17?} (MFEM {})", pr.mindet);
    assert!(
        (min_det - pr.mindet).abs() <= 1e-12 * pr.mindet.abs(),
        "llnl-p3 min detJ: fem-rs {min_det} vs MFEM {}",
        pr.mindet
    );

    // the attached rows ARE the file's rows (no 2-D renumbering): per-element
    // dof-id sequences match the probe position-for-position.
    for e in 0..mesh.n_elems() as u32 {
        let (geom, mfem_dofs) = &pr.edof[e as usize];
        let et = mesh.element_type(e);
        assert_eq!(*geom as u8, geometry_code(&et));
        let re = consumer_ref_elem(et, pr.p);
        let refs = &pr.node_ref.iter().find(|r| r.0 == *geom).unwrap().1;
        let row = mesh.geometry_row(e);
        assert_eq!(row.len(), mfem_dofs.len());
        for (s, mfem_ref) in refs.iter().enumerate() {
            // MFEM slot s ↔ consumer slot (position match on the lattice)
            let xi = to_consumer(et, mfem_ref, pr.sdim);
            let coords = re.dof_coords();
            let k = coords
                .iter()
                .position(|c| (0..pr.sdim).all(|d| (c[d] - xi[d]).abs() < 1e-12))
                .expect("MFEM ref point off the consumer lattice");
            assert_eq!(
                row[k] as usize, mfem_dofs[s],
                "element {e} MFEM slot {s} dof id"
            );
        }
    }

    // wrong orientation: the reader's `check_element_orientation` evaluated
    // the *curved* geometry — zero elements flagged (HEAD reported 15 / 26).
    let mut mesh_mut = mesh;
    let wo = mesh_mut.check_element_orientation(false);
    assert_eq!(wo, 0, "llnl-p3 curved orientation must be clean (HEAD: 15/26)");
}

/// fichera-mixed-p2 (tet+hex+prism P2): the attached values survive the
/// reader's tet renumbering — per-element physical node sets equal the
/// file-frame probe bit-for-bit, and min detJ is kept.
#[test]
fn d624_fichera_mixed_p2_values_survive_the_tet_rotation() {
    let mesh = read_mfem_file(FICHERA_MIXED_P2).expect("read").mesh3d.expect("3-D");
    let pr = parse_probe(FICHERA_P2_TRUTH);
    let g = mesh.geometry.as_ref().expect("D624: ragged geometry attached");
    assert_eq!(mesh.geom_order(), 2);
    assert_eq!(g.nodes_per_elem, 0);
    assert_eq!(g.n_nodes, pr.ndofs, "global geometry dof count");

    // physical per-element node sets (sorted) vs the probe — the dof *ids*
    // were renumbered by `mark_tet_mesh_for_refinement`, the *values* must
    // not move.  (`want` comes from the probe's own node table, i.e. the
    // file frame.)
    for e in 0..mesh.n_elems() as u32 {
        let (_, mfem_dofs) = &pr.edof[e as usize];
        let mut want: Vec<[f64; 3]> = mfem_dofs.iter().map(|&d| pr.node_xyz[d]).collect();
        want.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let got: Vec<[f64; 3]> = sorted_row_xyz(&mesh, e).into_iter().map(|(c, _)| c).collect();
        for (a, b) in got.iter().zip(want.iter()) {
            for d in 0..3 {
                assert_eq!(a[d].to_bits(), b[d].to_bits(), "element {e} coord bit-exact");
            }
        }
    }

    // min detJ over the FE-node lattice == MFEM (hex dets scaled /8 into the
    // consumer's [-1,1]³ frame).
    let mut min_det = f64::INFINITY;
    for e in 0..mesh.n_elems() as u32 {
        let et = mesh.element_type(e);
        let re = consumer_ref_elem(et, pr.p);
        for c in re.dof_coords() {
            let (_j, det, _x) = mesh.element_jacobian(e, &c);
            min_det = min_det.min(det * det_scale(et));
        }
    }
    println!("D624 fichera-mixed-p2 min detJ = {min_det:.17?} (MFEM {})", pr.mindet);
    assert!(
        (min_det - pr.mindet).abs() <= 1e-11 * pr.mindet.abs(),
        "fichera-mixed-p2 min detJ: fem-rs {min_det} vs MFEM {}",
        pr.mindet
    );
}

/// fichera-mixed-16-p2 (hex+prism+pyramid P2): loud-refuse at HEAD, attached
/// at D624 — the Fuentes pyramid rows pin the pyramid numbering end-to-end;
/// every element's volume equals the MFEM probe (straight geometry: exact).
#[test]
fn d624_fichera_mixed_16_p2_pyramids_attach() {
    let mesh = read_mfem_file(FICHERA_MIXED_16_P2)
        .expect("read")
        .mesh3d
        .expect("3-D");
    let pr = parse_probe(FICHERA_16_P2_TRUTH);
    assert_eq!(mesh.n_elems(), 16);
    assert_eq!(mesh.geom_order(), 2, "D624: the p2 pyramid mix attaches (HEAD: refuse)");
    let g = mesh.geometry.as_ref().expect("D624: ragged geometry attached");
    assert_eq!(g.nodes_per_elem, 0);
    assert_eq!(g.n_nodes, pr.ndofs, "global geometry dof count (126)");

    // per-family row lengths + composition: 1 hex + 6 prisms + 9 pyramids
    let (mut n_hex, mut n_prism, mut n_pyr) = (0usize, 0usize, 0usize);
    for e in 0..mesh.n_elems() as u32 {
        let len = mesh.geometry_row_len(e);
        match mesh.element_type(e) {
            ElementType::Hex8 => {
                n_hex += 1;
                assert_eq!(len, 27);
            }
            ElementType::Prism6 => {
                n_prism += 1;
                assert_eq!(len, 18);
            }
            ElementType::Pyramid5 => {
                n_pyr += 1;
                assert_eq!(len, 15, "Fuentes p(p²+3)+1, p=2");
            }
            other => panic!("unexpected {other:?}"),
        }
    }
    assert_eq!((n_hex, n_prism, n_pyr), (1, 6, 9));

    // min detJ over FE nodes + per-element volumes vs the probe.
    let mut min_det = f64::INFINITY;
    for e in 0..mesh.n_elems() as u32 {
        let et = mesh.element_type(e);
        let re = consumer_ref_elem(et, pr.p);
        let mut e_min = f64::INFINITY;
        for c in re.dof_coords() {
            let (_j, det, _x) = mesh.element_jacobian(e, &c);
            e_min = e_min.min(det * det_scale(et));
        }
        min_det = min_det.min(e_min);
        // straight geometry: volume = detJ(center) × consumer ref volume
        let center = ref_center(et, pr.sdim);
        let (_j, det_c, _x) = mesh.element_jacobian(e, &center);
        let vol = det_c * ref_volume(et, pr.sdim);
        assert!(
            (vol - pr.vol[e as usize]).abs() <= 1e-12 * (1.0 + pr.vol[e as usize].abs()),
            "element {e} ({et:?}) volume {} vs MFEM {}",
            vol,
            pr.vol[e as usize]
        );
    }
    println!("D624 fichera-mixed-16-p2 min detJ = {min_det:.17?} (MFEM {})", pr.mindet);
    assert!(
        (min_det - pr.mindet).abs() <= 1e-11,
        "fichera-mixed-16-p2 min detJ: fem-rs {min_det} vs MFEM {}",
        pr.mindet
    );

    // pyramid center det vs the probe (Fuentes consumer frame == MFEM frame).
    for e in 0..mesh.n_elems() as u32 {
        if mesh.element_type(e) != ElementType::Pyramid5 {
            continue;
        }
        let center = ref_center(ElementType::Pyramid5, pr.sdim);
        let (_j, det_c, _x) = mesh.element_jacobian(e, &center);
        assert_eq!(
            det_c.to_bits(),
            pr.center_det[e as usize].to_bits(),
            "pyramid element {e} center det bit-exact"
        );
    }
}

/// AMR tier: one uniform refinement of the curved llnl-p3 keeps the mixed
/// geometry — children are curved (ragged table, positive dets) and every
/// child dof value equals the parent map restricted to the child (the check
/// `refine_mixed_2d_geometry`'s construction promises).
#[test]
fn d624_amr_refines_the_curved_mixed_mesh() {
    use fem_mesh::MeshTopology as _;
    let coarse = read_mfem_file(LLNL_P3).expect("read").mesh2d.expect("2-D");
    assert_eq!(coarse.geom_order(), 3);
    let fine = fem_mesh::refine_uniform(&coarse);
    assert_eq!(fine.n_elems(), 4 * coarse.n_elems());
    let fg = fine.geometry.as_ref().expect("D624: refined mixed geometry attached");
    assert_eq!(fg.order, 3, "children keep the geometric order");
    assert_eq!(fg.nodes_per_elem, 0, "children keep the ragged layout");
    assert_eq!(fine.geom_order(), 3);

    // row lengths follow the children's families; dets stay positive.
    let mut min_det = f64::INFINITY;
    for e in 0..fine.n_elems() as u32 {
        let et = fine.element_type(e);
        let want = match et {
            ElementType::Tri3 | ElementType::Tri6 => 10,
            ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => 16,
            other => panic!("unexpected {other:?}"),
        };
        assert_eq!(fine.geometry_row_len(e), want, "child {e} row length");
        let re = consumer_ref_elem(et, 3);
        for c in re.dof_coords() {
            let (_j, det, _x) = fine.element_jacobian(e, &c);
            min_det = min_det.min(det);
            assert!(det > 0.0, "child {e} det {det} at {c:?}");
        }
    }
    println!("D624 llnl-p3 fine min detJ = {min_det:.17?}");
    // uniform refinement scales each child's Jacobian by 1/4, so the fine
    // minimum is the coarse minimum / 4 — MFEM's `0.0029296874999965726 / 4`.
    assert!(
        (min_det * 4.0 - 0.0029296874999965726_f64).abs() <= 1e-9,
        "fine min det {min_det} should be the coarse min / 4"
    );

    // geometry preservation: for every child, its dof *coordinates* must
    // equal the parent geometry evaluated at the child dof's pre-image
    // (the refinement operator MFEM applies to the `nodes` field).
    let p = 3usize;
    for e in 0..coarse.n_elems() as u32 {
        let et = coarse.element_type(e);
        let is_tri = matches!(et, ElementType::Tri3 | ElementType::Tri6);
        let pre = consumer_ref_elem(et, p);
        let prow: Vec<usize> = coarse
            .geometry_row(e)
            .iter()
            .map(|&n| n as usize)
            .collect();
        for c in 0..4 {
            let child = 4 * e + c;
            let cet = fine.element_type(child);
            let cre = consumer_ref_elem(cet, p);
            let ccoords = cre.dof_coords();
            let crow = fine.geometry_row(child);
            let child_cns = fine.element_nodes(child);
            for (s, dc) in ccoords.iter().enumerate() {
                let (xc, yc) = (dc[0], dc[1]);
                // child dof → parent reference position
                let xi_p: [f64; 2] = if is_tri {
                    let corners: [[f64; 3]; 3] = match c {
                        0 => [[1.0, 0.0, 0.0], [0.5, 0.5, 0.0], [0.5, 0.0, 0.5]],
                        1 => [[0.0, 0.5, 0.5], [0.5, 0.0, 0.5], [0.5, 0.5, 0.0]],
                        2 => [[0.5, 0.5, 0.0], [0.0, 1.0, 0.0], [0.0, 0.5, 0.5]],
                        _ => [[0.5, 0.0, 0.5], [0.0, 0.5, 0.5], [0.0, 0.0, 1.0]],
                    };
                    let lam = [1.0 - xc - yc, xc, yc];
                    let mut lam_p = [0.0f64; 3];
                    for (i, &l) in lam.iter().enumerate() {
                        for j in 0..3 {
                            lam_p[j] += l * corners[i][j];
                        }
                    }
                    [lam_p[1], lam_p[2]]
                } else {
                    let origin = match c {
                        0 => [0.0, 0.0],
                        1 => [0.5, 0.0],
                        2 => [0.5, 0.5],
                        _ => [0.0, 0.5],
                    };
                    [origin[0] + 0.5 * xc, origin[1] + 0.5 * yc]
                };
                // parent field at the pre-image (parent node ids → fine ids:
                // the coarse vertex ids are unchanged under refinement)
                let mut phi = vec![0.0f64; prow.len()];
                pre.eval_basis(&xi_p, &mut phi);
                let mut want = [0.0f64; 2];
                for (k, &g) in prow.iter().enumerate() {
                    let c = coarse.geom_coords_of(g as u32);
                    want[0] += phi[k] * c[0];
                    want[1] += phi[k] * c[1];
                }
                // child dof value: vertex slots sit on fine vertices; the
                // rest are geometry dofs.
                let is_vertex = match cet {
                    ElementType::Tri3 | ElementType::Tri6 => {
                        let lam = [1.0 - xc - yc, xc, yc];
                        lam.iter().filter(|&&l| l.abs() < 1e-12).count() == 2
                    }
                    _ => {
                        (xc - (xc * p as f64).round()).abs() < 1e-12
                            && (yc - (yc * p as f64).round()).abs() < 1e-12
                            && ((xc * p as f64).round() as i64 == 0
                                || (xc * p as f64).round() as i64 == p as i64)
                            && ((yc * p as f64).round() as i64 == 0
                                || (yc * p as f64).round() as i64 == p as i64)
                    }
                };
                let got = if is_vertex {
                    let v = if is_tri {
                        let lam = [1.0 - xc - yc, xc, yc];
                        (0..3).find(|&m| lam[m].abs() > 1e-12).unwrap()
                    } else {
                        match (
                            (xc * p as f64).round() as i64,
                            (yc * p as f64).round() as i64,
                        ) {
                            (0, 0) => 0,
                            (1, 0) => 1,
                            (1, 1) => 2,
                            _ => 3,
                        }
                    };
                    let c = fine.coords_of(child_cns[v]);
                    [c[0], c[1]]
                } else {
                    let c = fine.geom_coords_of(crow[s]);
                    [c[0], c[1]]
                };
                assert!(
                    (got[0] - want[0]).abs() <= 1e-11 * (1.0 + want[0].abs())
                        && (got[1] - want[1]).abs() <= 1e-11 * (1.0 + want[1].abs()),
                    "child {child} slot {s} ({xc},{yc}): parent-restricted {want:?} vs stored {got:?}"
                );

            }
        }
    }
}
