//! D675 (round 65): legacy VTK reader ↔ MFEM 4.10 `LoadVtk` parity pins.
//!
//! Every case reads a `.vtk` file with [`fem_io::vtk_legacy_reader::read_vtk_mesh_file`],
//! renders it in MFEM format with
//! [`fem_io::vtk_legacy_reader::write_mfem_vtk_load_style_file`], and demands
//! byte equality with the golden — produced by MFEM 4.10 itself as
//! `Mesh mesh(file, 1, 1); out.precision(16); mesh.Print(out);`
//! (`Mesh::Save`'s stream precision).
//!
//! * `data/{beam-tet,fichera-q2,square-disc-p2}.vtk` — the three repo assets
//!   (all "Generated by MFEM").
//! * `fixtures/vtk_d675/*.vtk` — MFEM `PrintVTK` round-trip probes, one per
//!   supported cell type, incl. the `*r.vtk` forced-rotation meshes whose
//!   geometry stretches the longest edge off (v0, v1) so the refinement
//!   marking (elements, boundary faces and the geometry-row permutations)
//!   is exercised for real.
//!
//! Re-generating the goldens: `tmp/d675/probe.cpp` (round 65 workspace).

use fem_io::vtk_legacy_reader::{read_vtk_mesh, read_vtk_mesh_file, write_mfem_vtk_load_style_file};

/// `(label, vtk path relative to the crate, golden path relative to the
/// crate)` — the repo assets live in the workspace-root `data/`, the probe
/// meshes in the test fixtures directory.
fn cases() -> Vec<(&'static str, String, String)> {
    let mut cases = Vec::new();
    for name in ["beam-tet", "fichera-q2", "square-disc-p2"] {
        cases.push((
            name,
            format!("../../data/{name}.vtk"),
            format!("tests/fixtures/vtk_d675/{name}.print"),
        ));
    }
    for name in [
        "tri3", "quad4", "tet4", "hex8", "prism6", "pyr5", "tri6", "quad9",
        "tet10", "hex27", "prism18", "tri3r", "tri6r", "tet4r", "tet10r",
    ] {
        cases.push((
            name,
            format!("tests/fixtures/vtk_d675/{name}.vtk"),
            format!("tests/fixtures/vtk_d675/{name}.print"),
        ));
    }
    cases
}

#[test]
fn d675_vtk_reader_matches_mfem_print_byte_for_byte() {
    // Resolve the crate directory so the test is cwd-independent.
    let crate_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace = crate_dir.parent().unwrap().parent().unwrap();
    let tmp = crate_dir.join("../../target/vtk_d675_parity");
    std::fs::create_dir_all(&tmp).expect("create scratch dir");

    for (label, vtk, golden) in cases() {
        let vtk_path = if vtk.starts_with("../../") {
            workspace.join(vtk.trim_start_matches("../../"))
        } else {
            crate_dir.join(&vtk)
        };
        let golden = std::fs::read_to_string(crate_dir.join(golden))
            .unwrap_or_else(|e| panic!("{label}: missing golden: {e}"));

        let mesh = read_vtk_mesh_file(&vtk_path).unwrap_or_else(|e| panic!("{label}: {e}"));
        let out = tmp.join(format!("{label}.mesh"));
        match (mesh.mesh2d.as_ref(), mesh.mesh3d.as_ref()) {
            (Some(m2), None) => write_mfem_vtk_load_style_file(&out, Some(m2), None)
                .unwrap_or_else(|e| panic!("{label}: {e}")),
            (None, Some(m3)) => write_mfem_vtk_load_style_file(&out, None, Some(m3))
                .unwrap_or_else(|e| panic!("{label}: {e}")),
            _ => panic!("{label}: expected exactly one mesh"),
        }
        let written = std::fs::read_to_string(&out).unwrap_or_else(|e| panic!("{label}: {e}"));
        assert_eq!(
            written, golden,
            "{label}: fem-rs VTK→MFEM output differs from MFEM 4.10 Print()"
        );
    }
}

#[test]
fn d675_vtk_reader_rejects_unsupported_types_loudly() {
    // A QUADRATIC_PYRAMID (27) mesh: MFEM 4.10 itself aborts on it
    // ("QuadraticFECollection: unknown geometry type") — the reader must
    // reject it with the offending type number.
    let vtk = "# vtk DataFile Version 3.0
p
ASCII
DATASET UNSTRUCTURED_GRID
POINTS 13 double
0 0 0
1 0 0
1 1 0
0 1 0
0 0 1
0.5 0 0
1 0.5 0
0.5 1 0
0 0.5 0
0 0 0.5
0.5 0 0.5
0.5 0.5 0.5
0 0.5 0.5
CELLS 1 14
13 0 1 2 3 4 5 6 7 8 9 10 11 12
CELL_TYPES 1
27
";
    let err = match read_vtk_mesh(vtk.as_bytes()) {
        Err(e) => e,
        Ok(_) => panic!("type 27 must be rejected"),
    };
    let msg = format!("{err}");
    assert!(msg.contains("27"), "rejection must name the type: {msg}");
}
