//! D456 — `transform_grid` (quad faces) must match MFEM
//! `RT_FECollection::QuadDofOrd` verbatim, and the tri-face analogue
//! `tri_face_grid_transform` must match `TriDofOrd`
//! (MFEM 4.10 `fem/fe_coll.cpp`, `InitFaces`: QuadDofOrd loop at
//! fe_coll.cpp:2712-2730, TriDofOrd loop at fe_coll.cpp:2695-2710; the rows
//! are served by `DofOrderForOrientation(SQUARE/TRIANGLE, Or)`).
//!
//! Ground truth was dumped from MFEM 4.10 serial by
//! `tmp/d456/probe_d456.cpp`:
//! 1. the raw `DofOrderForOrientation` tables (p = 1, 2, Or = 0..7/0..5,
//!    signs=true default: odd rows carry the `-1-x` encoding), pinned below
//!    as `MFEM_QUAD_P*` / `MFEM_TRI_P*`;
//! 2. `GetElementVDofs` for 2-element meshes whose shared face realizes
//!    every orientation reachable between two positively-oriented elements:
//!    hex pair Or∈{1,3,5,7} (k = 1, 2), tet pair Or∈{1,3,5}, prism pair on a
//!    quad face Or∈{3,7}, stacked prism pair on a tri face Or∈{1,3,5}
//!    (the `tmp/d398/d398_probe.cpp` multi-orientation pattern).
//!
//! Reachability theorem (verified by exhaustive search over all
//! positive-Jacobian numberings of the neighbour element, probe output
//! `tmp/d456/out/probe_d456.out`): two valid elements share each interior
//! face from opposite sides, so conforming interior faces ALWAYS carry odd
//! orientations; Or = 0 occurs for canonical (first-registered) faces and
//! the even nonzero rows (quad 2/4/6, tri 2/4) are table-level only.  The
//! D456 lesion — fem-rs `transform_grid` rows r2/r6 transposed against
//! MFEM's QuadDofOrd — is therefore pinned by the table test below, while
//! the mesh-integration pins hold both before and after the fix (they guard
//! the reachable rows 1/3/5/7, 0 and the tri side against regressions).

use fem_io::mfem::read_mfem_file;
use fem_mesh::Mesh;
use fem_space::hdiv::{rt_face_sign, transform_grid, tri_face_grid_transform};
use fem_space::HDivSpace;

// ── MFEM pins (generated by tmp/d456/probe_d456.cpp) ───────────────────────

pub static MFEM_QUAD_P1: [[i32; 4]; 8] = [
    [0, 1, 2, 3],
    [-1, -3, -2, -4],
    [2, 0, 3, 1],
    [-2, -1, -4, -3],
    [3, 2, 1, 0],
    [-4, -2, -3, -1],
    [1, 3, 0, 2],
    [-3, -4, -1, -2],
];
pub static MFEM_TRI_P1: [[i32; 3]; 6] = [
    [0, 1, 2],
    [-2, -1, -3],
    [1, 2, 0],
    [-3, -2, -1],
    [2, 0, 1],
    [-1, -3, -2],
];
pub static MFEM_QUAD_P2: [[i32; 9]; 8] = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8],
    [-1, -4, -7, -2, -5, -8, -3, -6, -9],
    [6, 3, 0, 7, 4, 1, 8, 5, 2],
    [-3, -2, -1, -6, -5, -4, -9, -8, -7],
    [8, 7, 6, 5, 4, 3, 2, 1, 0],
    [-9, -6, -3, -8, -5, -2, -7, -4, -1],
    [2, 5, 8, 1, 4, 7, 0, 3, 6],
    [-7, -8, -9, -4, -5, -6, -1, -2, -3],
];
pub static MFEM_TRI_P2: [[i32; 6]; 6] = [
    [0, 1, 2, 3, 4, 5],
    [-3, -2, -1, -5, -4, -6],
    [2, 4, 5, 1, 3, 0],
    [-6, -5, -3, -4, -2, -1],
    [5, 3, 0, 4, 1, 2],
    [-1, -4, -6, -2, -5, -3],
];

pub static HEX_ORI_K1_E0_IDS: [u32; 36] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55];
pub static HEX_ORI_K1_E0_SGN: [i8; 36] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
pub static HEX_ORI_K1_ORIS: [usize; 4] = [1, 3, 5, 7];
pub static HEX_ORI_K1_E1_IDS: [[u32; 36]; 4] = [
    [24, 25, 26, 27, 8, 10, 9, 11, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67],
    [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 9, 8, 11, 10, 40, 41, 42, 43, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67],
    [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 11, 9, 10, 8, 40, 41, 42, 43, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67],
    [10, 11, 8, 9, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67],
];
pub static HEX_ORI_K1_E1_SGN: [[i8; 36]; 4] = [
    [1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [-1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
];
pub static HEX_ORI_K2_E0_IDS: [u32; 108] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152];
pub static HEX_ORI_K2_E0_SGN: [i8; 108] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
pub static HEX_ORI_K2_ORIS: [usize; 4] = [1, 3, 5, 7];
pub static HEX_ORI_K2_E1_IDS: [[u32; 108]; 4] = [
    [54, 55, 56, 57, 58, 59, 60, 61, 62, 18, 21, 24, 19, 22, 25, 20, 23, 26, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206],
    [54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 20, 19, 18, 23, 22, 21, 26, 25, 24, 90, 91, 92, 93, 94, 95, 96, 97, 98, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206],
    [54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 26, 23, 20, 25, 22, 19, 24, 21, 18, 90, 91, 92, 93, 94, 95, 96, 97, 98, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206],
    [24, 25, 26, 21, 22, 23, 18, 19, 20, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206],
];
pub static HEX_ORI_K2_E1_SGN: [[i8; 108]; 4] = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
];
pub static TET_ORI_K1_E0_IDS: [u32; 15] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 21, 22, 23];
pub static TET_ORI_K1_E0_SGN: [i8; 15] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
pub static TET_ORI_K1_ORIS: [usize; 3] = [1, 3, 5];
pub static TET_ORI_K1_E1_IDS: [[u32; 15]; 3] = [
    [12, 13, 14, 15, 16, 17, 18, 19, 20, 11, 10, 9, 24, 25, 26],
    [12, 13, 14, 15, 16, 17, 18, 19, 20, 11, 10, 9, 24, 25, 26],
    [12, 13, 14, 15, 16, 17, 18, 19, 20, 11, 10, 9, 24, 25, 26],
];
pub static TET_ORI_K1_E1_SGN: [[i8; 15]; 3] = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 1, 1, 1],
];
pub static PRISQ_ORI_K1_E0_IDS: [u32; 25] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 32, 33, 34, 35, 36, 37, 38];
pub static PRISQ_ORI_K1_E0_SGN: [i8; 25] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
pub static PRISQ_ORI_K1_ORIS: [usize; 2] = [3, 7];
pub static PRISQ_ORI_K1_E1_IDS: [[u32; 25]; 2] = [
    [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 11, 10, 13, 12, 39, 40, 41, 42, 43, 44, 45],
    [18, 19, 20, 21, 22, 23, 12, 13, 10, 11, 24, 25, 26, 27, 28, 29, 30, 31, 39, 40, 41, 42, 43, 44, 45],
];
pub static PRISQ_ORI_K1_E1_SGN: [[i8; 25]; 2] = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
];
pub static PRIST_ORI_K1_E0_IDS: [u32; 25] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 33, 34, 35, 36, 37, 38, 39];
pub static PRIST_ORI_K1_E0_SGN: [i8; 25] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
pub static PRIST_ORI_K1_ORIS: [usize; 3] = [1, 3, 5];
pub static PRIST_ORI_K1_E1_IDS: [[u32; 25]; 3] = [
    [4, 3, 5, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 40, 41, 42, 43, 44, 45, 46],
    [5, 4, 3, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 40, 41, 42, 43, 44, 45, 46],
    [3, 5, 4, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 40, 41, 42, 43, 44, 45, 46],
];
pub static PRIST_ORI_K1_E1_SGN: [[i8; 25]; 3] = [
    [-1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [-1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [-1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
];

fn load(rel: &str) -> Mesh<3> {
    let path = format!("{}/../../{}", env!("CARGO_MANIFEST_DIR"), rel);
    let mfem = read_mfem_file(&path).unwrap_or_else(|e| panic!("failed to read {path}: {e}"));
    mfem.mesh3d.unwrap_or_else(|| panic!("{rel} must be a 3-D mesh"))
}

fn assert_signed(actual: &[f64], want: &[i8], ctx: String) {
    assert_eq!(actual.len(), want.len(), "{ctx}: sign count");
    for (i, (&a, &w)) in actual.iter().zip(want.iter()).enumerate() {
        assert_eq!(a, w as f64, "{ctx}: sign[{i}]");
    }
}

/// Slot-level table check: fem-rs `transform_grid` (+ `rt_face_sign`) must
/// reproduce every MFEM QuadDofOrd row entry for entry, p = 1 and 2,
/// Or = 0..=7.  RED before the D456 fix: fem-rs rows r2/r6 are transposed
/// against MFEM (fem-rs r2 == MFEM r6 and vice versa).
#[test]
fn quad_doford_matches_mfem_table() {
    let tables: Vec<(usize, Vec<&[i32]>)> = vec![(
            1,
            MFEM_QUAD_P1.iter().map(|r| r.as_slice()).collect(),
        ), (
            2,
            MFEM_QUAD_P2.iter().map(|r| r.as_slice()).collect(),
        )];
    for (p, table) in &tables {
        let side = p + 1;
        for (or, row) in table.iter().enumerate() {
            let sign = rt_face_sign(or);
            for j in 0..side {
                for i in 0..side {
                    let o = i + j * side;
                    let (ic, jc) = transform_grid(i, j, side, or);
                    let idx = jc * side + ic;
                    let (want_idx, want_sgn) = if row[o] >= 0 {
                        (row[o] as usize, 1.0)
                    } else {
                        ((-1 - row[o]) as usize, -1.0)
                    };
                    assert_eq!(
                        (idx, sign),
                        (want_idx, want_sgn),
                        "QuadDofOrd p={p} Or={or} slot (i={i}, j={j})"
                    );
                }
            }
        }
    }
}

/// Same check for the triangular-face grid (`TriDofOrd`) — green before and
/// after D456 (the tri side was already verbatim MFEM).
#[test]
fn tri_doford_matches_mfem_table() {
    let tables: Vec<(usize, Vec<&[i32]>)> = vec![(
            1,
            MFEM_TRI_P1.iter().map(|r| r.as_slice()).collect(),
        ), (
            2,
            MFEM_TRI_P2.iter().map(|r| r.as_slice()).collect(),
        )];
    for (p0, table) in &tables {
        let p = *p0;
        for (or, row) in table.iter().enumerate() {
            let sign = rt_face_sign(or);
            let mut used = vec![false; row.len()];
            for j in 0..=p {
                for i in 0..=(p - j) {
                    let o = j * (2 * p + 3 - j) / 2 + i;
                    let idx = tri_face_grid_transform(p, or, j, i);
                    let (want_idx, want_sgn) = if row[o] >= 0 {
                        (row[o] as usize, 1.0)
                    } else {
                        ((-1 - row[o]) as usize, -1.0)
                    };
                    assert_eq!(
                        (idx, sign),
                        (want_idx, want_sgn),
                        "TriDofOrd p={p} Or={or} slot (i={i}, j={j})"
                    );
                    used[idx as usize] = true;
                }
            }
            assert!(
                used.iter().all(|&u| u),
                "TriDofOrd p={p} Or={or} must permute all {} slots",
                row.len()
            );
        }
    }
}

/// Hex pair: element vdofs (ids + signs) for every reachable quad
/// orientation, RT k = 1 and k = 2.
#[test]
fn hex_pair_element_dofs_match_mfem() {
    for (col, or) in HEX_ORI_K1_ORIS.iter().enumerate() {
        let mesh = load(&format!("data/d456_hex_ori{or}.mesh"));
        let space = HDivSpace::new(mesh.clone(), 1);
        assert_eq!(space.n_dofs(), 68, "hex k=1 or{or} vsize (44 face + 2x12 interiors)");
        assert_eq!(space.element_dofs(0), HEX_ORI_K1_E0_IDS, "hex k=1 or{or} elem0 ids");
        assert_signed(space.element_signs(0), &HEX_ORI_K1_E0_SGN, format!("hex k=1 or{or} elem0"));
        assert_eq!(space.element_dofs(1), HEX_ORI_K1_E1_IDS[col], "hex k=1 or{or} elem1 ids");
        assert_signed(space.element_signs(1), &HEX_ORI_K1_E1_SGN[col], format!("hex k=1 or{or} elem1"));
    }
    for (col, or) in HEX_ORI_K2_ORIS.iter().enumerate() {
        let mesh = load(&format!("data/d456_hex_ori{or}.mesh"));
        let space = HDivSpace::new(mesh.clone(), 2);
        assert_eq!(space.n_dofs(), 207, "hex k=2 or{or} vsize (99 face + 2x54 interiors)");
        assert_eq!(space.element_dofs(0), HEX_ORI_K2_E0_IDS, "hex k=2 or{or} elem0 ids");
        assert_signed(space.element_signs(0), &HEX_ORI_K2_E0_SGN, format!("hex k=2 or{or} elem0"));
        assert_eq!(space.element_dofs(1), HEX_ORI_K2_E1_IDS[col], "hex k=2 or{or} elem1 ids");
        assert_signed(space.element_signs(1), &HEX_ORI_K2_E1_SGN[col], format!("hex k=2 or{or} elem1"));
    }
}

/// Tet pair: shared tri face at Or ∈ {1,3,5}, RT k = 1.
#[test]
fn tet_pair_element_dofs_match_mfem() {
    for (col, or) in TET_ORI_K1_ORIS.iter().enumerate() {
        let mesh = load(&format!("data/d456_tet_ori{or}.mesh"));
        let space = HDivSpace::new(mesh.clone(), 1);
        assert_eq!(space.n_dofs(), 27, "tet RT1 vsize (7 faces x3 + 2x3 interiors)");
        assert_eq!(space.element_dofs(0), TET_ORI_K1_E0_IDS, "tet or{or} elem0 ids");
        assert_signed(space.element_signs(0), &TET_ORI_K1_E0_SGN, format!("tet or{or} elem0"));
        assert_eq!(space.element_dofs(1), TET_ORI_K1_E1_IDS[col], "tet or{or} elem1 ids");
        assert_signed(space.element_signs(1), &TET_ORI_K1_E1_SGN[col], format!("tet or{or} elem1"));
    }
}

/// Prism pair sharing a quad face at Or ∈ {3,7}, RT k = 1.
#[test]
fn prism_quad_pair_element_dofs_match_mfem() {
    for (col, or) in PRISQ_ORI_K1_ORIS.iter().enumerate() {
        let mesh = load(&format!("data/d456_prisq_ori{or}.mesh"));
        let space = HDivSpace::new(mesh.clone(), 1);
        assert_eq!(space.n_dofs(), 46, "prism RT1 vsize (32 face + 2x7 interiors)");
        assert_eq!(space.element_dofs(0), PRISQ_ORI_K1_E0_IDS, "prisq or{or} elem0 ids");
        assert_signed(space.element_signs(0), &PRISQ_ORI_K1_E0_SGN, format!("prisq or{or} elem0"));
        assert_eq!(space.element_dofs(1), PRISQ_ORI_K1_E1_IDS[col], "prisq or{or} elem1 ids");
        assert_signed(space.element_signs(1), &PRISQ_ORI_K1_E1_SGN[col], format!("prisq or{or} elem1"));
    }
}

/// Stacked prism pair sharing a tri face at Or ∈ {1,3,5}, RT k = 1.
#[test]
fn prism_tri_pair_element_dofs_match_mfem() {
    for (col, or) in PRIST_ORI_K1_ORIS.iter().enumerate() {
        let mesh = load(&format!("data/d456_prist_ori{or}.mesh"));
        let space = HDivSpace::new(mesh.clone(), 1);
        assert_eq!(space.n_dofs(), 47, "prism RT1 vsize (33 face + 2x7 interiors)");
        assert_eq!(space.element_dofs(0), PRIST_ORI_K1_E0_IDS, "prist or{or} elem0 ids");
        assert_signed(space.element_signs(0), &PRIST_ORI_K1_E0_SGN, format!("prist or{or} elem0"));
        assert_eq!(space.element_dofs(1), PRIST_ORI_K1_E1_IDS[col], "prist or{or} elem1 ids");
        assert_signed(space.element_signs(1), &PRIST_ORI_K1_E1_SGN[col], format!("prist or{or} elem1"));
    }
}
