
[package]
name    = "fem-examples"
version = "0.1.0"
edition = "2021"

[features]
default = []
gpu = ["fem-solver/gpu", "fem-linalg-gpu", "wgpu", "bytemuck"]
io_hdf5 = ["fem-io-hdf5-parallel/hdf5"]
io_hdf5_mpi = ["fem-io-hdf5-parallel/hdf5-mpi"]
parallel = ["fem-assembly/parallel", "fem-linalg/parallel"]

[dependencies]
fem-core     = { path = "../crates/core" }
fem-mesh     = { path = "../crates/mesh" }
fem-linalg   = { path = "../crates/linalg" }
fem-io       = { path = "../crates/io" }
fem-parallel = { path = "../crates/parallel" }
fem-element  = { path = "../crates/element" }
fem-space    = { path = "../crates/space" }
fem-assembly = { path = "../crates/assembly" }
fem-solver   = { path = "../crates/solver" }
fem-amg      = { path = "../crates/amg" }
fem-io-hdf5-parallel = { path = "../crates/io_hdf5_parallel" }
fem-linalg-gpu = { path = "../crates/linalg-gpu", optional = true }
wgpu           = { version = "27", optional = true }
bytemuck       = { workspace = true, optional = true }
nalgebra     = { workspace = true }
linlvo       = { git = "https://github.com/rem-rs/linlvo.git" }
log          = { workspace = true }
env_logger   = { workspace = true }
rand         = "0.8"
rand_distr   = "0.4"

[dev-dependencies]
fem-regression = { path = "../crates/regression" }

[lib]
name = "fem_examples"
[[example]]
name = "mfem_ex0_mesh_intro"
path = "mfem_ex0_mesh_intro.rs"
[[example]]
name = "mfem_ex10_hyperelastic_dyn"
path = "mfem_ex10_hyperelastic_dyn.rs"
[[example]]
name = "mfem_ex11_eigenvalue"
path = "mfem_ex11_eigenvalue.rs"
[[example]]
name = "mfem_ex12_elastic_eigen"
path = "mfem_ex12_elastic_eigen.rs"
[[example]]
name = "mfem_ex13_eigenvalue"
path = "mfem_ex13_eigenvalue.rs"
[[example]]
name = "mfem_ex14_dg_poisson"
path = "mfem_ex14_dg_poisson.rs"
[[example]]
name = "mfem_ex15_dynamic_amr"
path = "mfem_ex15_dynamic_amr.rs"
[[example]]
name = "mfem_ex16_nonlinear_heat"
path = "mfem_ex16_nonlinear_heat.rs"
[[example]]
name = "mfem_ex17_dg_elasticity"
path = "mfem_ex17_dg_elasticity.rs"
[[example]]
name = "mfem_ex18_euler"
path = "mfem_ex18_euler.rs"
[[example]]
name = "mfem_ex19_hyperelastic_incomp"
path = "mfem_ex19_hyperelastic_incomp.rs"
[[example]]
name = "mfem_ex1_poisson"
path = "mfem_ex1_poisson.rs"
[[example]]
name = "mfem_ex20_symplectic"
path = "mfem_ex20_symplectic.rs"
[[example]]
name = "mfem_ex21_amr_elasticity"
path = "mfem_ex21_amr_elasticity.rs"
[[example]]
name = "mfem_ex22_complex_helmholtz"
path = "mfem_ex22_complex_helmholtz.rs"
[[example]]
name = "mfem_ex23_wave_equation"
path = "mfem_ex23_wave_equation.rs"
[[example]]
name = "mfem_ex24_discrete_ops"
path = "mfem_ex24_discrete_ops.rs"
[[example]]
name = "mfem_ex25_pml_maxwell"
path = "mfem_ex25_pml_maxwell.rs"
[[example]]
name = "mfem_ex26_geom_mg"
path = "mfem_ex26_geom_mg.rs"
[[example]]
name = "mfem_ex27_robin_bc"
path = "mfem_ex27_robin_bc.rs"
[[example]]
name = "mfem_ex28_sliding_elasticity"
path = "mfem_ex28_sliding_elasticity.rs"
[[example]]
name = "mfem_ex29_curved_poisson"
path = "mfem_ex29_curved_poisson.rs"
[[example]]
name = "mfem_ex2_elasticity"
path = "mfem_ex2_elasticity.rs"
[[example]]
name = "mfem_ex30_aniso_amr"
path = "mfem_ex30_aniso_amr.rs"
[[example]]
name = "mfem_ex31_anisotropic_maxwell"
path = "mfem_ex31_anisotropic_maxwell.rs"
[[example]]
name = "mfem_ex31_dump"
path = "mfem_ex31_dump.rs"
[[example]]
name = "mfem_ex32_maxwell_eigenvalue"
path = "mfem_ex32_maxwell_eigenvalue.rs"
[[example]]
name = "mfem_ex32_dump"
path = "mfem_ex32_dump.rs"
[[example]]
name = "mfem_ex33_fractional_laplacian"
path = "mfem_ex33_fractional_laplacian.rs"
[[example]]
name = "mfem_ex33_fractional_diffusion"
path = "mfem_ex33_fractional_diffusion.rs"
[[example]]
name = "dbg_e2v"
path = "dbg_e2v.rs"
[[example]]
name = "dbg_j2"
path = "dbg_j2.rs"
[[example]]
name = "dbg_rt0"
path = "dbg_rt0.rs"
[[example]]
name = "dbg_phi2"
path = "dbg_phi2.rs"
[[example]]
name = "dbg_elmat2"
path = "dbg_elmat2.rs"
[[example]]
name = "dbg_prism"
path = "dbg_prism.rs"
[[example]]
name = "dbg_prism2"
path = "dbg_prism2.rs"
[[example]]
name = "mfem_ex34_magnetostatics"
path = "mfem_ex34_magnetostatics.rs"
[[example]]
name = "mfem_ex35_complex_oscillator"
path = "mfem_ex35_complex_oscillator.rs"
[[example]]
name = "mfem_ex36_obstacle"
path = "mfem_ex36_obstacle.rs"
[[example]]
name = "mfem_ex37_topology_optimization"
path = "mfem_ex37_topology_optimization.rs"
[[example]]
name = "mfem_ex38_immersed_boundary"
path = "mfem_ex38_immersed_boundary.rs"
[[example]]
name = "mfem_ex39_compass"
path = "mfem_ex39_compass.rs"
[[example]]
name = "mfem_ex3_maxwell_cavity"
path = "mfem_ex3_maxwell_cavity.rs"
[[example]]
name = "mfem_ex40_eikonal"
path = "mfem_ex40_eikonal.rs"
[[example]]
name = "mfem_ex41_imex"
path = "mfem_ex41_imex.rs"
[[example]]
name = "mfem_ex4_darcy"
path = "mfem_ex4_darcy.rs"
[[example]]
name = "mfem_ex5_mixed_darcy"
path = "mfem_ex5_mixed_darcy.rs"
[[example]]
name = "mfem_ex6_flux_recovery"
path = "mfem_ex6_flux_recovery.rs"
[[example]]
name = "mfem_ex7_surface_poisson"
path = "mfem_ex7_surface_poisson.rs"
[[example]]
name = "mfem_ex8_dpg_2x2"
path = "mfem_ex8_dpg_2x2.rs"
[[example]]
name = "mfem_ex8_hybridization"
path = "mfem_ex8_hybridization.rs"
[[example]]
name = "mfem_ex9_dg_advection"
path = "mfem_ex9_dg_advection.rs"
[[example]]
name = "mfem_pex10_parallel_hyperelastic"
path = "mfem_pex10_parallel_hyperelastic.rs"
[[example]]
name = "mfem_pex11_parallel_eigenvalue"
path = "mfem_pex11_parallel_eigenvalue.rs"
[[example]]
name = "mfem_pex12_parallel_elastic_eigen"
path = "mfem_pex12_parallel_elastic_eigen.rs"
[[example]]
name = "mfem_pex13_parallel_eigenvalue"
path = "mfem_pex13_parallel_eigenvalue.rs"
[[example]]
name = "mfem_pex14_parallel_dg_poisson"
path = "mfem_pex14_parallel_dg_poisson.rs"
[[example]]
name = "mfem_pex15_parallel_dynamic_amr"
path = "mfem_pex15_parallel_dynamic_amr.rs"
[[example]]
name = "mfem_pex16_parallel_nonlinear_heat"
path = "mfem_pex16_parallel_nonlinear_heat.rs"
[[example]]
name = "mfem_pex17_parallel_dg_elasticity"
path = "mfem_pex17_parallel_dg_elasticity.rs"
[[example]]
name = "mfem_pex18_parallel_euler"
path = "mfem_pex18_parallel_euler.rs"
[[example]]
name = "mfem_pex19_parallel_incomp_hyperelastic"
path = "mfem_pex19_parallel_incomp_hyperelastic.rs"
[[example]]
name = "mfem_pex1_parallel_poisson"
path = "mfem_pex1_parallel_poisson.rs"
[[example]]
name = "mfem_pex20_parallel_symplectic"
path = "mfem_pex20_parallel_symplectic.rs"
[[example]]
name = "mfem_pex21_parallel_amr_elasticity"
path = "mfem_pex21_parallel_amr_elasticity.rs"
[[example]]
name = "mfem_pex22_parallel_complex_helmholtz"
path = "mfem_pex22_parallel_complex_helmholtz.rs"
[[example]]
name = "mfem_pex23_parallel_wave"
path = "mfem_pex23_parallel_wave.rs"
[[example]]
name = "mfem_pex24_parallel_discrete_ops"
path = "mfem_pex24_parallel_discrete_ops.rs"
[[example]]
name = "mfem_pex25_pml_maxwell"
path = "mfem_pex25_pml_maxwell.rs"
[[example]]
name = "mfem_pex26_parallel_geom_mg"
path = "mfem_pex26_parallel_geom_mg.rs"
[[example]]
name = "mfem_pex27_parallel_robin_bc"
path = "mfem_pex27_parallel_robin_bc.rs"
[[example]]
name = "mfem_pex28_parallel_sliding_elasticity"
path = "mfem_pex28_parallel_sliding_elasticity.rs"
[[example]]
name = "mfem_pex29_surface_poisson"
path = "mfem_pex29_surface_poisson.rs"
[[example]]
name = "mfem_pex2_mixed_darcy"
path = "mfem_pex2_mixed_darcy.rs"
[[example]]
name = "mfem_pex2_parallel_elasticity"
path = "mfem_pex2_parallel_elasticity.rs"
[[example]]
name = "mfem_pex30_amr_preprocess"
path = "mfem_pex30_amr_preprocess.rs"
[[example]]
name = "mfem_pex31_restricted_hcurl"
path = "mfem_pex31_restricted_hcurl.rs"
[[example]]
name = "mfem_pex32_maxwell_eigenvalue"
path = "mfem_pex32_maxwell_eigenvalue.rs"
[[example]]
name = "mfem_pex33_fractional_laplacian"
path = "mfem_pex33_fractional_laplacian.rs"
[[example]]
name = "mfem_pex34_magnetostatics"
path = "mfem_pex34_magnetostatics.rs"
[[example]]
name = "mfem_pex35_complex_oscillator"
path = "mfem_pex35_complex_oscillator.rs"
[[example]]
name = "mfem_pex36_obstacle"
path = "mfem_pex36_obstacle.rs"
[[example]]
name = "mfem_pex37_topology_optimization"
path = "mfem_pex37_topology_optimization.rs"
[[example]]
name = "mfem_pex39_named_attributes"
path = "mfem_pex39_named_attributes.rs"
[[example]]
name = "mfem_pex3_maxwell_cavity"
path = "mfem_pex3_maxwell_cavity.rs"
[[example]]
name = "mfem_pex40_eikonal"
path = "mfem_pex40_eikonal.rs"
[[example]]
name = "mfem_pex41_imex"
path = "mfem_pex41_imex.rs"
[[example]]
name = "mfem_pex4_parallel_heat"
path = "mfem_pex4_parallel_heat.rs"
[[example]]
name = "mfem_pex5_hdiv_darcy"
path = "mfem_pex5_hdiv_darcy.rs"
[[example]]
name = "mfem_pex6_parallel_amr"
path = "mfem_pex6_parallel_amr.rs"
[[example]]
name = "mfem_pex7_parallel_surface"
path = "mfem_pex7_parallel_surface.rs"
[[example]]
name = "mfem_pex8_parallel_p_multigrid"
path = "mfem_pex8_parallel_p_multigrid.rs"
[[example]]
name = "mfem_pex9_parallel_dg_advection"
path = "mfem_pex9_parallel_dg_advection.rs"
[[example]]
name = "mfem_miniapp_joule"
path = "mfem_miniapp_joule.rs"
[[example]]
name = "mfem_miniapp_lorentz"
path = "mfem_miniapp_lorentz.rs"
[[example]]
name = "mfem_miniapp_maxwell"
path = "mfem_miniapp_maxwell.rs"
[[example]]
name = "mfem_miniapp_tesla"
path = "mfem_miniapp_tesla.rs"
[[example]]
name = "mfem_miniapp_volta"
path = "mfem_miniapp_volta.rs"
