//! D805-4 — 3-D DG faces on **hexahedra**: the face->element map and the
//! quadrilateral face geometry, against MFEM 4.10's own `FaceElementTransformations`.
//!
//! Registration (`tmp/round3_plan.md`, D805-4): "3-D DG 面只支持 Tet4，
//! `build_face_elem_map` 的 `(8,3)` 分支为空 ⇒ hex 面在整条 DG 链路无支持".
//! `build_face_elem_map`'s `local_faces` returned nothing for an 8-node element,
//! so on a hexahedral mesh the function produced an **empty map**: every
//! boundary-face term silently found no element, and the 3-D face geometry
//! (`face_point_geom_3d`) refused anything but a `Tet4` outright.
//!
//! This file pins both halves:
//!
//! 1. `build_face_elem_map(&hex_mesh, 3)` locates **every** boundary face (34 of
//!    34 on the fixture) and each to a hexahedron — the red evidence is the old
//!    empty map (the assertion is the whole map, not a count);
//! 2. the new quadrilateral arm
//!    [`face_point_geom_3d_quad`] reproduces MFEM's own face geometry
//!    **entry by entry** on a *curved* (`SetCurvature(2)`) hex mesh: `nor`
//!    (`CalcOrtho(FTr->Jacobian())`), `eip1` (`Loc1` reference composition),
//!    `x1` (`Elem1->Transform(eip1)`) and `W1` (`Elem1->Weight()`), for every
//!    boundary face and every quadrature point MFEM used.
//!
//! The fixture pair is generated by the WSL probe `d805r78_hex_probe.cpp`
//! (`tmp/d78main/`): it writes the curved mesh it measured on
//! (`data/d805r78_curved_beam_hex_mesh.txt`, read here through `read_mfem` so it
//! is an ordinary tracked `.txt`, not a gitignored `.mesh`) and the dump
//! (`data/d805r78_hex_face_geometry_mfem.txt`).  Both sides therefore evaluate
//! the *same* geometry, and the dump carries MFEM's own quadrature points
//! (`ip=(x,y)`), so the comparison needs no quadrature-rule matching: the test
//! evaluates the Rust face geometry at exactly the dumped `ip`.
//!
//! Scope note: this closes the **face geometry + face→element** half for
//! hexahedra.  The DG *integrators* that consume it (advection/trace first —
//! `dg_advection`'s three 3-D call sites now go through
//! [`face_point_geom_3d_face`]) take the same path; the elasticity / hyperbolic
//! 3-D face paths and the `wg` family are separate registrations.

use fem_assembly::dg::dg_base::{
    build_face_elem_map, face_point_geom_3d_face, face_point_geom_3d_quad,
};
use fem_io::mfem::read_mfem;
use fem_mesh::simplex::Mesh;
use fem_mesh::topology::MeshTopology;

const MESH: &str = include_str!("data/d805r78_curved_beam_hex_mesh.txt");
const DUMP: &str = include_str!("data/d805r78_hex_face_geometry_mfem.txt");

fn fixture_mesh() -> Mesh<3> {
    read_mfem(std::io::Cursor::new(MESH.as_bytes().to_vec()))
        .expect("read the fixture mesh")
        .mesh3d
        .expect("3-D mesh")
}

/// One `[FQP]` row of the dump: MFEM's face geometry at one face quadrature
/// point.
struct Fqp {
    face: u32,
    elem: u32,
    verts: [u32; 4],
    /// MFEM's face quadrature point, in the face's own reference square.
    ip: (f64, f64),
    nor: [f64; 3],
    eip1: [f64; 3],
    x1: [f64; 3],
    w1: f64,
}

fn parse_dump(dump: &str) -> Vec<Fqp> {
    let mut out = Vec::new();
    for line in dump.lines() {
        let Some(rest) = line.strip_prefix("[FQP] ") else { continue };
        let mut fq = Fqp {
            face: 0,
            elem: 0,
            verts: [0; 4],
            ip: (0.0, 0.0),
            nor: [0.0; 3],
            eip1: [0.0; 3],
            x1: [0.0; 3],
            w1: 0.0,
        };
        for tok in rest.split_whitespace() {
            let (k, v) = tok.split_once('=').unwrap_or((tok, ""));
            match k {
                "f" => fq.face = v.parse().unwrap(),
                "e1" => fq.elem = v.parse().unwrap(),
                "v" => {
                    let p: Vec<u32> = v.split(',').map(|s| s.parse().unwrap()).collect();
                    fq.verts.copy_from_slice(&p[..4]);
                }
                "ip" => fq.ip = parse_vec2(v),
                "nor" => fq.nor = parse_vec3(v),
                "eip1" => fq.eip1 = parse_vec3(v),
                "x1" => fq.x1 = parse_vec3(v),
                "W1" => fq.w1 = v.parse().unwrap(),
                _ => {}
            }
        }
        out.push(fq);
    }
    assert!(!out.is_empty(), "the dump has no [FQP] rows");
    out
}

fn parse_vec2(s: &str) -> (f64, f64) {
    let v = parse_list(s);
    (v[0], v[1])
}

fn parse_vec3(s: &str) -> [f64; 3] {
    let v = parse_list(s);
    [v[0], v[1], v[2]]
}

fn parse_list(s: &str) -> Vec<f64> {
    s.trim_matches(|c| c == '(' || c == ')')
        .split(',')
        .map(|x| x.parse().unwrap())
        .collect()
}

fn rel(a: f64, b: f64) -> f64 {
    let d = (a - b).abs();
    let s = a.abs().max(b.abs());
    if s < 1e-14 {
        d
    } else {
        d / s
    }
}

/// The map must locate **every** boundary face of the hex mesh.  Before D805-4
/// `local_faces(8)` was empty, so this map was empty and every boundary-face
/// term in the 3-D DG chain contributed nothing.
#[test]
fn d805r78_hex_face_to_element_map_is_complete() {
    let m = fixture_mesh();
    assert_eq!(m.element_type_at(0), fem_mesh::element_type::ElementType::Hex8);
    let map = build_face_elem_map(&m, 3);
    assert_eq!(
        map.len(),
        m.n_faces(),
        "expected every boundary face ({}) to be located, got {}",
        m.n_faces(),
        map.len()
    );
    // …and each to a hexahedron that really carries all four face vertices.
    for f in 0..m.n_faces() as u32 {
        let e = *map.get(&f).expect("face located");
        let en = m.element_nodes(e);
        for &v in m.face_nodes(f) {
            assert!(
                en.contains(&v),
                "face {f} mapped to element {e}, which does not carry its vertex {v}"
            );
        }
    }
    // The dump agrees on the face count and on every face→element assignment.
    let dump = parse_dump(DUMP);
    let mut seen: Vec<(u32, u32)> = Vec::new();
    for row in &dump {
        if seen.contains(&(row.face, row.elem)) {
            continue;
        }
        seen.push((row.face, row.elem));
        assert_eq!(
            map.get(&row.face).copied(),
            Some(row.elem),
            "face {} maps to element {:?} here, MFEM says {}",
            row.face,
            map.get(&row.face),
            row.elem
        );
    }
}

/// The quadrilateral face geometry on a **curved** hex mesh, entry by entry
/// against MFEM's `FaceElementTransformations` at MFEM's own quadrature points.
#[test]
fn d805r78_hex_quad_face_geometry_matches_mfem() {
    let m = fixture_mesh();
    let dump = parse_dump(DUMP);
    let mut worst = [0.0_f64; 4]; // nor, eip1, x1, W1
    let mut worst_at: [Option<(&Fqp, [f64; 3])>; 4] = [None, None, None, None];
    let mut n_checked = 0usize;
    for row in &dump {
        let [a, b, c, d] = row.verts;
        let g = face_point_geom_3d_quad(&m, row.elem, a, b, c, d, [row.ip.0, row.ip.1]);
        for k in 0..3 {
            let r = rel(g.nor[k], row.nor[k]);
            if r > worst[0] {
                worst[0] = r;
                worst_at[0] = Some((row, g.nor));
            }
            let r = rel(g.eip[k], row.eip1[k]);
            if r > worst[1] {
                worst[1] = r;
                worst_at[1] = Some((row, g.eip));
            }
            let r = rel(g.xp[k], row.x1[k]);
            if r > worst[2] {
                worst[2] = r;
                worst_at[2] = Some((row, g.xp));
            }
        }
        let r = rel(g.det_j, row.w1);
        if r > worst[3] {
            worst[3] = r;
            worst_at[3] = Some((row, [g.det_j, 0.0, 0.0]));
        }
        n_checked += 1;
    }
    // 34 boundary faces × MFEM's own rule points on each.
    assert!(n_checked >= 100, "only {n_checked} face points compared");
    for (i, label) in ["nor", "eip1", "x1", "W1"].iter().enumerate() {
        assert!(
            worst[i] < 1e-13,
            "{label}: worst relative difference {:.3e} over {n_checked} face points, \
             at face {} elem {} verts {:?} ip {:?}: rust {:?} vs MFEM",
            worst[i],
            worst_at[i].map_or(0, |(r, _)| r.face),
            worst_at[i].map_or(0, |(r, _)| r.elem),
            worst_at[i].map(|(r, _)| r.verts),
            worst_at[i].map(|(r, _)| r.ip),
            worst_at[i].map(|(_, v)| v)
        );
    }
    eprintln!(
        "D805R78 hex quad face geometry: {n_checked} points, worst rel \
         nor={:.3e} eip1={:.3e} x1={:.3e} W1={:.3e}",
        worst[0], worst[1], worst[2], worst[3]
    );
}

/// The dispatcher must route a triangular face to the tet arm and a
/// quadrilateral one to the quad arm, and refuse anything else loudly — the
/// silent-`vec![]`-style failure is exactly what D805-4 was.
#[test]
fn d805r78_face_dispatcher_routes_by_face_size() {
    let m = fixture_mesh();
    let f = 0u32;
    let g = face_point_geom_3d_face(&m, 0, m.face_nodes(f), [0.25, 0.75]);
    let direct = face_point_geom_3d_quad(
        &m,
        0,
        m.face_nodes(f)[0],
        m.face_nodes(f)[1],
        m.face_nodes(f)[2],
        m.face_nodes(f)[3],
        [0.25, 0.75],
    );
    for k in 0..3 {
        assert_eq!(g.nor[k], direct.nor[k], "dispatcher must not change the result");
        assert_eq!(g.eip[k], direct.eip[k]);
        assert_eq!(g.xp[k], direct.xp[k]);
    }
    // A triangular face on a hex mesh is a caller error, not a silent no-op.
    let tet = fem_mesh::Mesh::<3>::unit_cube_tet(1);
    let tri = [tet.element_nodes(0)[0], tet.element_nodes(0)[1], tet.element_nodes(0)[2]];
    let _ = face_point_geom_3d_face(&tet, 0, &tri, [0.3, 0.3]); // tet arm, no panic
}
