//! D810-1 — the **wg family's face geometry** (`wg_poisson`, `wg_stokes`,
//! `wg_maxwell`) on curved simplex meshes.
//!
//! # The debt
//!
//! Each of the three modules carried its own private **chord route** for the
//! face stabilizer `α·∫_F φᵢφⱼ dS`: `face_geom_2d`/`face_geom_3d` built the
//! measure from the face's **corner nodes**, the quadrature point was the
//! linear interpolation of those corners, and the element reference point came
//! from *inverting* the element's vertex Jacobian (`local_phys_to_ref`).  That
//! is the route round 75 deleted from `dg.rs`/`dg_advection`/`dg_elasticity`/
//! `dg_hyperbolic` and round 76 from the PA kernels: exact only while the mesh
//! is straight, silently `O(h)`-wrong on a mesh carrying an order-`g` geometry
//! table.  Registration also undercounted the damage as "one line": the chord
//! route covered **three** things — the face measure, the face physical point,
//! and the reference-point inversion.
//!
//! The family now takes the whole face path from `dg_base::face_point_geom` /
//! `face_point_geom_3d` (the single arithmetic source round 75 introduced),
//! plus MFEM's face rules (`seg_rule` in 2-D, `tri_rule` in 3-D — the pre-fix
//! 2-D loop fed a *triangle* rule to a segment parameterisation and used only
//! its `ξ₀`).
//!
//! # The oracle (and what it proves)
//!
//! MFEM 4.10 has **no WG miniapp** (`miniapps/` has none), so there is no WG
//! truth to port.  What *is* available is the truth for the arithmetic the
//! family uses: `tmp/d78c/d810_probe.cpp` dumps MFEM's own
//! `FaceElementTransformations` on the **same curved fixtures** —
//! `MakeCartesian{2,3}D(1,1[,1], TRIANGLE/TETRAHEDRON)` + `SetCurvature(2)` +
//! the D787/D793 word-warp applied to every geometry dof and vertex — at the
//! face reference points of the wg rules themselves:
//!
//! * every face (boundary **and** interior), both sides,
//! * `nor = CalcOrtho(Trans.Jacobian())` (magnitude = face measure),
//! * `eip = GetElement{1,2}IntPoint()` (the `Loc1`/`Loc2` composition — the
//!   quantity the inversion used to approximate),
//! * `x = Elem->Transform(eip)` (the physical face point),
//! * `W = Elem->Weight()` (the element Jacobian determinant there).
//!
//! [`d810_1_face_primitive_matches_mfem`] compares them entry by entry with
//! fem-rs' `face_point_geom`/`face_point_geom_3d` — the *functions the wg
//! modules now call* — so it proves the wg face path's arithmetic equals
//! MFEM's on curved simplices.  It does **not** prove WG *methods* numbers
//! (no MFEM WG exists); the wg assembly-level pins below ([`wg_face_diff`]
//! against an independent assembly through the same primitive, and the
//! straight-mesh relation to the verbatim pre-fix route) are what bind the
//! modules to that primitive.
//!
//! The gold files are the probe's stdout verbatim (17 significant digits):
//! `crates/assembly/tests/data/d810_mfem_face_{tet,tri}_n1.txt`, regenerated by
//! `wsl -e bash -lc 'cd /home/quan/work/d78c && ./d810_probe tet 1 2'`.

use fem_assembly::dg::dg_base::{face_point_geom, face_point_geom_3d};
use fem_assembly::{assemble_wg_maxwell, assemble_wg_poisson, InteriorFaceList};
use fem_element::lagrange::{TetPk, TriPk};
use fem_element::nedelec::TriNDk;
use fem_element::quadrature::{seg_rule, tri_rule};
use fem_element::{ReferenceElement, VectorReferenceElement};
use fem_mesh::{element_type::ElementType, Mesh, MeshTopology};
use fem_space::fe_space::FESpace;
use fem_space::{HCurlSpace, L2Space};

const GOLD_TET: &str = include_str!("data/d810_mfem_face_tet_n1.txt");
const GOLD_TRI: &str = include_str!("data/d810_mfem_face_tri_n1.txt");

// ─── Fixtures (the MFEM probe's meshes, cell for cell) ─────────────────────

fn warp3(x: [f64; 3]) -> [f64; 3] {
    [
        x[0] + 0.1 * x[1] * x[2] + 0.2 * x[0] * x[0],
        x[1] + 0.05 * x[0] * x[2],
        x[2] + 0.1 * x[0] * x[1],
    ]
}

fn warp2(x: [f64; 2]) -> [f64; 2] {
    [x[0] + 0.2 * x[0] * x[0] + 0.1 * x[0] * x[1], x[1] + 0.05 * x[0] * x[1]]
}

fn warp_all<const D: usize>(mesh: &mut Mesh<D>, f: fn([f64; D]) -> [f64; D]) {
    let n_geom = mesh.geometry.as_ref().expect("curved table").coords.len() / D;
    {
        let geo = mesh.geometry.as_mut().expect("curved table");
        for k in 0..n_geom {
            let mut x = [0.0_f64; D];
            x.copy_from_slice(&geo.coords[k * D..(k + 1) * D]);
            let y = f(x);
            geo.coords[k * D..(k + 1) * D].copy_from_slice(&y);
        }
    }
    for k in 0..mesh.n_nodes() {
        let mut x = [0.0_f64; D];
        x.copy_from_slice(&mesh.coords[k * D..(k + 1) * D]);
        let y = f(x);
        mesh.coords[k * D..(k + 1) * D].copy_from_slice(&y);
    }
}

/// `Mesh::unit_cube_tet(1)` (the 6-tet Kuhn split of the unit cube) with an
/// order-2 geometry table and the probe's warp — `MakeCartesian3D(1,1,1,
/// TETRAHEDRON)` + `SetCurvature(2)` + the same warp.
fn curved_tet_mesh() -> Mesh<3> {
    let mut m = Mesh::<3>::unit_cube_tet(1);
    m.set_curvature(2);
    warp_all(&mut m, warp3);
    m
}

/// The two triangles of `MakeCartesian2D(1,1,TRIANGLE)` — the diagonal is
/// nodes 0–2 — with an order-2 geometry table and the probe's warp.
fn curved_tri_mesh() -> Mesh<2> {
    let mut m = Mesh::<2>::uniform(
        vec![0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0],
        vec![0, 1, 2, 0, 2, 3],
        vec![1, 1],
        ElementType::Tri3,
        vec![0, 1, 1, 2, 2, 3, 3, 0],
        vec![1, 1, 1, 1],
        ElementType::Line2,
    );
    m.set_curvature(2);
    warp_all(&mut m, warp2);
    m
}

fn straight_tet_mesh() -> Mesh<3> {
    Mesh::<3>::unit_cube_tet(1)
}

fn straight_tri_mesh() -> Mesh<2> {
    Mesh::<2>::uniform(
        vec![0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0],
        vec![0, 1, 2, 0, 2, 3],
        vec![1, 1],
        ElementType::Tri3,
        vec![0, 1, 1, 2, 2, 3, 3, 0],
        vec![1, 1, 1, 1],
        ElementType::Line2,
    )
}

// ─── The MFEM gold ─────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
struct GoldFace {
    e1: i64,
    e2: i64,
    /// The face's vertices in MFEM's own order — the `(a, b[, c])` the Rust
    /// side must pass so that the reference parameterisation coincides.
    fv: Vec<u32>,
}

#[derive(Debug, Clone)]
struct GoldQp {
    f: usize,
    side: usize,
    e: i64,
    r: usize,
    nor: Vec<f64>,
    eip: Vec<f64>,
    x: Vec<f64>,
    w: f64,
}

#[derive(Debug)]
struct Gold {
    dim: usize,
    verts: Vec<Vec<f64>>,
    elems: Vec<Vec<u32>>,
    evols: Vec<f64>,
    rps: Vec<Vec<f64>>,
    faces: Vec<GoldFace>,
    qps: Vec<GoldQp>,
}

fn nums(s: &str) -> Vec<f64> {
    s.split(|c: char| !(c.is_ascii_digit() || c == '.' || c == '-' || c == 'e' || c == 'E' || c == '+'))
        .filter(|t| !t.is_empty() && *t != "-" && *t != "+")
        .map(|t| t.parse::<f64>().unwrap_or_else(|_| panic!("bad number {t:?} in {s:?}")))
        .collect()
}

/// `k=(...)` → the numbers inside the parentheses.
fn paren(line: &str, key: &str) -> Vec<f64> {
    let i = line.find(key).unwrap_or_else(|| panic!("no {key} in {line:?}"));
    let rest = &line[i + key.len()..];
    let j = rest.find(')').expect("unterminated tuple");
    nums(&rest[..j])
}

/// `k=<n>` → the number.
fn scalar(line: &str, key: &str) -> f64 {
    let i = line.find(key).unwrap_or_else(|| panic!("no {key} in {line:?}"));
    let rest = &line[i + key.len()..];
    let end = rest.find(|c: char| c == ' ' || c == ')' || c == '(').unwrap_or(rest.len());
    rest[..end].parse::<f64>().unwrap_or_else(|_| panic!("bad scalar in {line:?}"))
}

fn parse_gold(s: &str) -> Gold {
    let mut g = Gold {
        dim: 0,
        verts: Vec::new(),
        elems: Vec::new(),
        evols: Vec::new(),
        rps: Vec::new(),
        faces: Vec::new(),
        qps: Vec::new(),
    };
    for line in s.lines() {
        if let Some(r) = line.strip_prefix("[MESH] ") {
            g.dim = scalar(r, "dim=") as usize;
        } else if let Some(r) = line.strip_prefix("[V] ") {
            let v = nums(r);
            g.verts.push(v[1..].to_vec());
        } else if let Some(r) = line.strip_prefix("[ELEM] ") {
            let n = r.find(':').expect("ELEM has no ':'");
            let vs: Vec<u32> = nums(&r[n + 1..]).iter().map(|v| *v as u32).collect();
            g.elems.push(vs);
        } else if let Some(r) = line.strip_prefix("[EVOL] ") {
            g.evols.push(nums(r)[1]);
        } else if let Some(r) = line.strip_prefix("[RP] ") {
            g.rps.push(nums(r)[1..].to_vec());
        } else if let Some(r) = line.strip_prefix("[FACE] ") {
            let n = r.find(':').expect("FACE has no ':'");
            let head = nums(&r[..n]);
            g.faces.push(GoldFace {
                e1: head[1] as i64,
                e2: head[2] as i64,
                fv: nums(&r[n + 1..]).iter().map(|v| *v as u32).collect(),
            });
        } else if let Some(r) = line.strip_prefix("[FQP] ") {
            g.qps.push(GoldQp {
                f: scalar(r, "f=") as usize,
                side: scalar(r, "side=") as usize,
                // NB: `" e="` — a bare `"e="` also matches inside `"side="`.
                e: scalar(r, " e=") as i64,
                r: scalar(r, "r=") as usize,
                nor: paren(r, "nor="),
                eip: paren(r, "eip="),
                x: paren(r, "x="),
                w: scalar(r, "W="),
            });
        }
    }
    assert!(!g.qps.is_empty() && !g.faces.is_empty(), "empty gold");
    g
}

/// The `fem-rs` element with the **ordered** vertex tuple `tuple`.
fn match_elem<const D: usize>(mesh: &Mesh<D>, tuple: &[u32]) -> u32 {
    for e in 0..mesh.n_elems() as u32 {
        if mesh.element_nodes(e) == tuple {
            return e;
        }
    }
    panic!("no element with the ordered vertex tuple {tuple:?} — the fixtures diverged");
}

/// `∫_T |det J|` over the mesh's own geometry map (the `[EVOL]` quantity).
fn element_measure<const D: usize>(mesh: &Mesh<D>, e: u32) -> f64 {
    let dim = mesh.dim() as usize;
    let qf = if dim == 2 { tri_rule(10) } else { fem_element::quadrature::tet_rule(10) };
    let mut v = 0.0;
    for (qi, xi) in qf.points.iter().enumerate() {
        let arr: [f64; D] = std::array::from_fn(|k| xi[k]);
        let (j, _x) = fem_mesh::transformation::element_jacobian_at(mesh, e, &arr, dim);
        v += qf.weights[qi] * j.determinant().abs();
    }
    v
}

fn check_mesh_identity<const D: usize>(mesh: &Mesh<D>, gold: &Gold, name: &str) {
    assert_eq!(mesh.dim() as usize, gold.dim, "{name}: dimension");
    assert_eq!(mesh.n_nodes(), gold.verts.len(), "{name}: vertex count");
    let mut worst_v = 0.0_f64;
    for (i, gv) in gold.verts.iter().enumerate() {
        for d in 0..gold.dim {
            worst_v = worst_v.max((mesh.coords[i * gold.dim + d] - gv[d]).abs());
        }
    }
    assert!(worst_v < 1e-15, "{name}: vertices differ by {worst_v:.3e}");

    let mut worst_vol = 0.0_f64;
    for (i, ge) in gold.elems.iter().enumerate() {
        let e = match_elem::<D>(mesh, ge);
        let want = gold.evols[i];
        worst_vol = worst_vol.max((element_measure(mesh, e) - want).abs() / want.abs());
    }
    println!("{name}: mesh identity max|Δvertex|={worst_v:.3e} max rel|Δvol|={worst_vol:.3e}");
    assert!(worst_vol < 1e-13, "{name}: element measures differ by {worst_vol:.3e}");
}

/// The four quantities MFEM's `FaceElementTransformations` hands a DG/WG face
/// term, as `face_point_geom`(`_3d`) returns them.
struct RsFace {
    eip: Vec<f64>,
    x: Vec<f64>,
    nor: Vec<f64>,
    det_j: f64,
}

fn rs_face<const D: usize>(
    mesh: &Mesh<D>,
    elem: u32,
    fv: &[u32],
    xi: &[f64],
) -> RsFace {
    if D == 2 {
        let g = face_point_geom(mesh, elem, fv[0], fv[1], xi[0]);
        RsFace { eip: g.eip.to_vec(), x: g.xp.to_vec(), nor: g.nor.to_vec(), det_j: g.det_j }
    } else {
        let g = face_point_geom_3d(mesh, elem, fv[0], fv[1], fv[2], [xi[0], xi[1]]);
        RsFace { eip: g.eip.to_vec(), x: g.xp.to_vec(), nor: g.nor.to_vec(), det_j: g.det_j }
    }
}

/// MFEM's `FaceElementTransformations` vs `face_point_geom`(`_3d`) at every
/// face reference point of the wg rules, on every face, on both sides.
fn check_face_primitive<const D: usize>(
    mesh: &Mesh<D>,
    gold: &Gold,
    name: &str,
) -> (f64, f64, f64, f64, f64) {
    let (mut worst_nor, mut worst_eip, mut worst_x, mut worst_w) = (0.0_f64, 0.0_f64, 0.0_f64, 0.0_f64);
    let mut worst_dir = 0.0_f64;
    for qp in &gold.qps {
        let elem = match_elem::<D>(mesh, &gold.elems[qp.e as usize]);
        let fv = &gold.faces[qp.f].fv;
        let rs = rs_face(mesh, elem, fv, &gold.rps[qp.r]);
        // MFEM's `nor` is always Elem1's (outward from Elem1); Elem2's own
        // outward normal is its negative.  The comparison is
        // magnitude-relative: a bare per-component ratio blows up whenever one
        // component of the normal happens to be near zero (faces nearly
        // parallel to a coordinate plane), which is not a geometry error.
        let s = if qp.side == 1 { 1.0 } else { -1.0 };
        let gmag = qp.nor.iter().map(|v| v * v).sum::<f64>().sqrt();
        let rmag = rs.nor.iter().map(|v| v * v).sum::<f64>().sqrt();
        worst_nor = worst_nor.max((rmag - gmag).abs() / gmag.max(1e-300));
        for d in 0..gold.dim {
            worst_dir = worst_dir.max((s * rs.nor[d] - qp.nor[d]).abs() / gmag.max(1e-300));
            worst_eip = worst_eip.max((rs.eip[d] - qp.eip[d]).abs());
            worst_x = worst_x.max((rs.x[d] - qp.x[d]).abs());
        }
        worst_w = worst_w.max((rs.det_j - qp.w).abs() / qp.w.abs().max(1e-300));
    }
    println!(
        "{name}: max rel|Δ|nor||={worst_nor:.3e}  max|Δnor|/|nor|={worst_dir:.3e}           max|Δeip|={worst_eip:.3e}  max|Δx|={worst_x:.3e}  max rel|ΔW|={worst_w:.3e}"
    );
    (worst_nor.max(worst_dir), worst_eip, worst_x, worst_w, worst_dir)
}

// ─── wg assembly-level pins ────────────────────────────────────────────────

/// How a face's geometry is computed when building the stabilizer.
#[derive(Clone, Copy, PartialEq)]
enum Route {
    /// The post-D810-1 path: `face_point_geom`(`_3d`) + MFEM's face rule.
    Isoparametric,
    /// The pre-D810-1 chord route, reproduced verbatim: the corner chord /
    /// corner triangle for the measure, corner interpolation for the physical
    /// point, the affine vertex-Jacobian inverse for the reference point, and
    /// the pre-fix rule (`tri_rule` in *both* dimensions, only `ξ₀` used).
    Chord,
}

/// The wg face stabilizer `Σ_faces α·∫_F φᵢφⱼ dS` with `α = penalty/h`,
/// assembled independently of the wg modules.
fn wg_face_block<const D: usize>(
    mesh: &Mesh<D>,
    space: &L2Space<Mesh<D>>,
    quad_order: u8,
    penalty: f64,
    route: Route,
) -> Vec<Vec<f64>> {
    let dim = mesh.dim() as usize;
    let n = space.n_dofs();
    let mut k = vec![vec![0.0_f64; n]; n];

    for f in &InteriorFaceList::build(mesh).faces {
        face_block_add(mesh, space, &mut k, f.elem_left, f.elem_right, &f.face_nodes, quad_order, penalty, route);
    }
    let bmap = fem_assembly::dg::dg_base::build_face_elem_map(mesh, dim);
    for bf in mesh.face_iter() {
        if let Some(&el) = bmap.get(&bf) {
            let fnodes: Vec<u32> = mesh.face_nodes(bf).to_vec();
            face_block_add(mesh, space, &mut k, el, el, &fnodes, quad_order, penalty, route);
        }
    }
    k
}

#[allow(clippy::too_many_arguments)]
fn face_block_add<const D: usize>(
    mesh: &Mesh<D>,
    space: &L2Space<Mesh<D>>,
    k: &mut [Vec<f64>],
    el: u32,
    er: u32,
    fnodes: &[u32],
    quad_order: u8,
    penalty: f64,
    route: Route,
) {
    let dim = mesh.dim() as usize;
    let order = space.order() as usize;
    let ref_e: Box<dyn ReferenceElement> =
        if dim == 2 { Box::new(TriPk::new(order)) } else { Box::new(TetPk::new(order)) };
    let ne = ref_e.n_dofs();
    let (h, qf) = match route {
        Route::Isoparametric => {
            (face_measure(mesh, el, fnodes, quad_order), face_rule(dim, quad_order))
        }
        Route::Chord => (chord_measure(mesh, fnodes), tri_rule(quad_order)),
    };
    let alpha = penalty / h.max(1e-14);
    let dofs_l: Vec<usize> = space.element_dofs(el).iter().map(|&d| d as usize).collect();
    let dofs_r: Vec<usize> = space.element_dofs(er).iter().map(|&d| d as usize).collect();

    for (qi, xi) in qf.points.iter().enumerate() {
        let mut sides: Vec<(u32, &Vec<usize>)> = vec![(el, &dofs_l)];
        if el != er {
            sides.push((er, &dofs_r));
        }
        for (es, dofs) in sides {
            let (eip, w) = match route {
                Route::Isoparametric => {
                    let g = rs_face(mesh, es, fnodes, xi);
                    let mag = g.nor.iter().map(|v| v * v).sum::<f64>().sqrt();
                    (g.eip, qf.weights[qi] * mag)
                }
                Route::Chord => {
                    // Pre-fix: corner-interpolated physical point, inverted
                    // through the affine vertex Jacobian.
                    let (xp, _nor) = chord_point_normal(mesh, es, fnodes, xi);
                    (chord_invert(mesh, es, &xp), qf.weights[qi] * h)
                }
            };
            let mut pb = vec![0.0_f64; ne];
            ref_e.eval_basis(&eip, &mut pb);
            for i in 0..ne {
                for j in 0..ne {
                    let v = alpha * w * pb[i] * pb[j];
                    if v.abs() > 1e-30 {
                        k[dofs[i]][dofs[j]] += v;
                    }
                }
            }
        }
    }
}

fn face_rule(dim: usize, qo: u8) -> fem_element::reference::QuadratureRule {
    if dim == 2 { seg_rule(qo) } else { tri_rule(qo) }
}

/// `Σ_q ipw_q·|nor|_q` on the isoparametric face.
fn face_measure<const D: usize>(mesh: &Mesh<D>, elem: u32, fnodes: &[u32], qo: u8) -> f64 {
    let dim = mesh.dim() as usize;
    let qf = face_rule(dim, qo);
    let mut h = 0.0;
    for (qi, xi) in qf.points.iter().enumerate() {
        let g = rs_face(mesh, elem, fnodes, xi);
        h += qf.weights[qi] * g.nor.iter().map(|v| v * v).sum::<f64>().sqrt();
    }
    h
}

/// The pre-fix chord / corner-triangle measure.
fn chord_measure<const D: usize>(mesh: &Mesh<D>, fnodes: &[u32]) -> f64 {
    let c0 = mesh.node_coords(fnodes[0]);
    if fnodes.len() == 2 {
        let c1 = mesh.node_coords(fnodes[1]);
        ((c1[0] - c0[0]).powi(2) + (c1[1] - c0[1]).powi(2)).sqrt()
    } else {
        let c1 = mesh.node_coords(fnodes[1]);
        let c2 = mesh.node_coords(fnodes[2]);
        let u1 = [c1[0] - c0[0], c1[1] - c0[1], c1[2] - c0[2]];
        let u2 = [c2[0] - c0[0], c2[1] - c0[1], c2[2] - c0[2]];
        let n = [
            u1[1] * u2[2] - u1[2] * u2[1],
            u1[2] * u2[0] - u1[0] * u2[2],
            u1[0] * u2[1] - u1[1] * u2[0],
        ];
        (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt() / 2.0
    }
}

/// The pre-fix corner-interpolated physical point (returns its `|nor|` too).
fn chord_point_normal<const D: usize>(
    mesh: &Mesh<D>,
    _elem: u32,
    fnodes: &[u32],
    xi: &[f64],
) -> (Vec<f64>, f64) {
    let c0 = mesh.node_coords(fnodes[0]);
    if fnodes.len() == 2 {
        let c1 = mesh.node_coords(fnodes[1]);
        let n = [c1[1] - c0[1], -(c1[0] - c0[0])];
        (
            vec![c0[0] + xi[0] * (c1[0] - c0[0]), c0[1] + xi[0] * (c1[1] - c0[1])],
            (n[0] * n[0] + n[1] * n[1]).sqrt(),
        )
    } else {
        let c1 = mesh.node_coords(fnodes[1]);
        let c2 = mesh.node_coords(fnodes[2]);
        let u1 = [c1[0] - c0[0], c1[1] - c0[1], c1[2] - c0[2]];
        let u2 = [c2[0] - c0[0], c2[1] - c0[1], c2[2] - c0[2]];
        let n = [
            u1[1] * u2[2] - u1[2] * u2[1],
            u1[2] * u2[0] - u1[0] * u2[2],
            u1[0] * u2[1] - u1[1] * u2[0],
        ];
        (
            vec![
                c0[0] + xi[0] * u1[0] + xi[1] * u2[0],
                c0[1] + xi[0] * u1[1] + xi[1] * u2[1],
                c0[2] + xi[0] * u1[2] + xi[1] * u2[2],
            ],
            (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt(),
        )
    }
}

/// The pre-fix reference point: the affine vertex-Jacobian inverse applied to
/// the corner-interpolated physical point.
fn chord_invert<const D: usize>(mesh: &Mesh<D>, elem: u32, xp: &[f64]) -> Vec<f64> {
    let dim = mesh.dim() as usize;
    let nodes = mesh.element_nodes(elem);
    let x0 = mesh.node_coords(nodes[0]);
    // jac[(d, i)] = ∂x_d/∂ξ_i from the first `dim` vertices (the pre-fix
    // `local_jac`), then `ξ = J⁻¹(xp − x0)`.
    let mut a = vec![vec![0.0_f64; dim]; dim];
    for i in 0..dim {
        let xi = mesh.node_coords(nodes[1 + i]);
        for d in 0..dim {
            a[d][i] = xi[d] - x0[d];
        }
    }
    let det = if dim == 2 {
        a[0][0] * a[1][1] - a[0][1] * a[1][0]
    } else {
        a[0][0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
            - a[0][1] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
            + a[0][2] * (a[1][0] * a[2][1] - a[1][1] * a[2][0])
    };
    let inv = if det.abs() < 1e-300 { 0.0 } else { 1.0 / det };
    let mut xi = vec![0.0_f64; dim];
    if dim == 2 {
        xi[0] = inv * (a[1][1] * (xp[0] - x0[0]) - a[0][1] * (xp[1] - x0[1]));
        xi[1] = inv * (-a[1][0] * (xp[0] - x0[0]) + a[0][0] * (xp[1] - x0[1]));
    } else {
        xi[0] = inv * ((a[1][1] * a[2][2] - a[1][2] * a[2][1]) * (xp[0] - x0[0])
            + (a[0][2] * a[2][1] - a[0][1] * a[2][2]) * (xp[1] - x0[1])
            + (a[0][1] * a[1][2] - a[0][2] * a[1][1]) * (xp[2] - x0[2]));
        xi[1] = inv * ((a[1][2] * a[2][0] - a[1][0] * a[2][2]) * (xp[0] - x0[0])
            + (a[0][0] * a[2][2] - a[0][2] * a[2][0]) * (xp[1] - x0[1])
            + (a[0][2] * a[1][0] - a[0][0] * a[1][2]) * (xp[2] - x0[2]));
        xi[2] = inv * ((a[1][0] * a[2][1] - a[1][1] * a[2][0]) * (xp[0] - x0[0])
            + (a[0][1] * a[2][0] - a[0][0] * a[2][1]) * (xp[1] - x0[1])
            + (a[0][0] * a[1][1] - a[0][1] * a[1][0]) * (xp[2] - x0[2]));
    }
    xi
}

/// The wg assembler's face block, isolated by linearity in `penalty`:
/// `K(penalty=1) − K(penalty=0)`.
fn wg_face_diff<const D: usize>(
    _mesh: &Mesh<D>,
    space: &L2Space<Mesh<D>>,
    qo: u8,
) -> Vec<Vec<f64>> {
    let k1 = assemble_wg_poisson(space, qo, 1.0);
    let k0 = assemble_wg_poisson(space, qo, 0.0);
    let n = space.n_dofs();
    let mut d = vec![vec![0.0_f64; n]; n];
    for i in 0..n {
        for p in k0.row_ptr[i]..k0.row_ptr[i + 1] {
            d[i][k0.col_idx[p] as usize] -= k0.values[p];
        }
        for p in k1.row_ptr[i]..k1.row_ptr[i + 1] {
            d[i][k1.col_idx[p] as usize] += k1.values[p];
        }
    }
    d
}

fn max_rel_diff(a: &[Vec<f64>], b: &[Vec<f64>]) -> f64 {
    let mut num = 0.0_f64;
    let mut den = 0.0_f64;
    for i in 0..a.len() {
        for j in 0..a.len() {
            num = num.max((a[i][j] - b[i][j]).abs());
            den = den.max(b[i][j].abs());
        }
    }
    num / den.max(1e-300)
}

// ─── Tests ─────────────────────────────────────────────────────────────────

/// The gold is on the fixtures this crate builds: same vertices (bitwise),
/// same element vertex tuples (ordered), same element measures.
#[test]
fn d810_1_fixtures_are_the_mfem_meshes() {
    check_mesh_identity(&curved_tet_mesh(), &parse_gold(GOLD_TET), "tet");
    check_mesh_identity(&curved_tri_mesh(), &parse_gold(GOLD_TRI), "tri");
}

/// The primary oracle: `face_point_geom`(`_3d`) — the function the wg family's
/// whole face path now is — reproduces MFEM 4.10's `FaceElementTransformations`
/// (`nor`, `eip`, `Elem->Transform(eip)`, `Elem->Weight()`) at every face-QP of
/// every face, on the curved fixtures.
#[test]
fn d810_1_face_primitive_matches_mfem() {
    let t = check_face_primitive(&curved_tet_mesh(), &parse_gold(GOLD_TET), "tet");
    let r = check_face_primitive(&curved_tri_mesh(), &parse_gold(GOLD_TRI), "tri");
    for (name, v) in [("tet", t), ("tri", r)] {
        let (nor, eip, x, w, _dir) = v;
        assert!(nor < 1e-13, "{name}: |nor| = {nor:.3e}");
        assert!(eip < 1e-13, "{name}: eip = {eip:.3e}");
        assert!(x < 1e-13, "{name}: x = {x:.3e}");
        assert!(w < 1e-13, "{name}: W = {w:.3e}");
    }
}

/// The pre-fix chord route does **not** reproduce MFEM on the curved fixture —
/// the teeth of the oracle above (the same faces, the same points, the
/// geometry route it replaced) — and, as the measurement also shows, its
/// reference-point **inversion** is inert on simplex faces.
#[test]
fn d810_1_chord_route_is_far_from_mfem_on_curved_cells() {
    let tet = curved_tet_mesh();
    let gold = parse_gold(GOLD_TET);
    let (mut worst_eip, mut worst_x, mut worst_nor) = (0.0_f64, 0.0_f64, 0.0_f64);
    for qp in &gold.qps {
        let elem = match_elem(&tet, &gold.elems[qp.e as usize]);
        let fv = &gold.faces[qp.f].fv;
        let (xp, nor_mag) = chord_point_normal(&tet, elem, fv, &gold.rps[qp.r]);
        let eip = chord_invert(&tet, elem, &xp);
        let gold_nor = qp.nor.iter().map(|v| v * v).sum::<f64>().sqrt();
        worst_nor = worst_nor.max((nor_mag - gold_nor).abs() / gold_nor.max(1e-30));
        for d in 0..3 {
            worst_eip = worst_eip.max((eip[d] - qp.eip[d]).abs());
            worst_x = worst_x.max((xp[d] - qp.x[d]).abs());
        }
    }
    println!(
        "pre-fix chord route vs MFEM (curved tet): max|Δeip|={worst_eip:.3e} \
         max|Δx|={worst_x:.3e} max rel|Δnor|={worst_nor:.3e}"
    );
    assert!(worst_x > 1e-3, "physical-point witness has no teeth: {worst_x:.3e}");
    assert!(worst_nor > 1e-2, "normal witness has no teeth: {worst_nor:.3e}");
    // Registration correction (round 78): the **reference-point inversion** —
    // the third leg D810-1's registration names — is provably inert on a
    // *simplex* face.  The pre-fix `local_phys_to_ref` inverts the element's
    // affine vertex map at the corner-interpolated physical point, and for an
    // affine `X` with `xp = Σ λᵢ X(vᵢ) = X(Σ λᵢ ξ(vᵢ))` that recovers
    // `Σ λᵢ ξ(vᵢ)` exactly — which is precisely MFEM's `Loc1` composition
    // (`face_point_geom`'s `eip`), a purely combinatorial affine map that never
    // sees the curvature.  So on curved simplex faces the inversion is *not* a
    // source of error here; what the chord route gets wrong is the face measure
    // and the face physical point.  (For the D799-3 quad case it *would* be:
    // a bilinear map's inverse is not affine.)
    assert!(
        worst_eip < 1e-13,
        "the inversion leg was measured inert ({worst_eip:.3e}), which the registration \
         calls a defect — re-derive the registration if this fires"
    );
}


/// The wg **Poisson** stabilizer on a curved mesh is exactly the independent
/// assembly through `face_point_geom` — and the chord route it replaced is
/// `O(1e-1)` off.  Also pins the straight-mesh relation to the pre-fix route.
fn wg_poisson_pins<const D: usize>(curved: &Mesh<D>, straight: &Mesh<D>, name: &str) {
    let qo = 3;
    let sp_c = L2Space::new(curved.clone(), 1);
    let sp_s = L2Space::new(straight.clone(), 1);

    // Curved: the wg face block IS the isoparametric one; the chord route is not.
    let wg_c = wg_face_diff(curved, &sp_c, qo);
    let iso_c = wg_face_block(curved, &sp_c, qo, 1.0, Route::Isoparametric);
    let chord_c = wg_face_block(curved, &sp_c, qo, 1.0, Route::Chord);
    let rel_iso = max_rel_diff(&wg_c, &iso_c);
    let rel_chord = max_rel_diff(&wg_c, &chord_c);
    println!(
        "{name} curved: wg face block vs isoparametric={rel_iso:.3e}, \
         vs pre-fix chord route={rel_chord:.3e}"
    );
    assert!(rel_iso < 1e-12, "{name}: wg face block != isoparametric ({rel_iso:.3e})");
    assert!(rel_chord > 1e-2, "{name}: the chord witness has no teeth ({rel_chord:.3e})");

    // Straight: the pre-fix route is reproduced by `Chord` (same measure, same
    // point — the only difference left is the rule).
    let wg_s = wg_face_diff(straight, &sp_s, qo);
    let iso_s = wg_face_block(straight, &sp_s, qo, 1.0, Route::Isoparametric);
    let chord_s = wg_face_block(straight, &sp_s, qo, 1.0, Route::Chord);
    let rel_iso_s = max_rel_diff(&wg_s, &iso_s);
    let rel_chord_s = max_rel_diff(&wg_s, &chord_s);
    println!(
        "{name} straight: wg face block vs isoparametric={rel_iso_s:.3e}, \
         vs chord route={rel_chord_s:.3e}"
    );
    assert!(rel_iso_s < 1e-12, "{name} straight: wg face block != isoparametric");
    if name == "tet" {
        // 3-D: the chord/corner-triangle measure is exactly half the reference
        // measure (`tri_rule` sums to 1/2, `|nor|` is twice the triangle area),
        // and the straight elements' composition and corner points coincide —
        // so the new block is exactly twice the pre-fix one.
        let doubled: Vec<Vec<f64>> =
            chord_s.iter().map(|r| r.iter().map(|v| 2.0 * v).collect()).collect();
        let rel = max_rel_diff(&wg_s, &doubled);
        println!("{name} straight: ||wg − 2·chord|| = {rel:.3e}");
        assert!(rel < 1e-12, "{name} straight: the measure normalization is not exactly 2x ({rel:.3e})");
    } else {
        // 2-D: the chord length IS the face measure exactly (so `h` and the
        // point did not move), the change is the rule — `seg_rule` (Σw = 1,
        // MFEM's face rule) instead of a triangle rule read along one axis
        // (Σw = 1/2, and its `ξ₀` values are not a 1-D quadrature at all), so
        // the pre-fix block is off by more than the measure factor alone.
        let doubled: Vec<Vec<f64>> =
            chord_s.iter().map(|r| r.iter().map(|v| 2.0 * v).collect()).collect();
        let beyond = max_rel_diff(&wg_s, &doubled);
        println!("{name} straight: ||wg − 2·chord|| = {beyond:.3e} (rule error, not just the factor)");
        assert!(
            rel_chord_s > 1e-2,
            "2-D straight: the pre-fix rule witness has no teeth ({rel_chord_s:.3e})"
        );
        assert!(
            beyond > 1e-2,
            "2-D straight: the pre-fix rule error beyond the measure factor is only {beyond:.3e}"
        );
    }
}

#[test]
fn d810_1_wg_poisson_face_block_is_the_isoparametric_one_2d() {
    wg_poisson_pins(&curved_tri_mesh(), &straight_tri_mesh(), "tri");
}

#[test]
fn d810_1_wg_poisson_face_block_is_the_isoparametric_one_3d() {
    wg_poisson_pins(&curved_tet_mesh(), &straight_tet_mesh(), "tet");
}

/// The wg **Maxwell** stabilizer uses the same face path (2-D HCurl fixture).
#[test]
fn d810_1_wg_maxwell_face_block_is_the_isoparametric_one() {
    let qo = 3;
    let mesh = curved_tri_mesh();
    let hcurl = HCurlSpace::new(mesh.clone(), 1);
    let n = hcurl.n_dofs();
    let k1 = assemble_wg_maxwell(&hcurl, qo, 1.0, &[]).0;
    let k0 = assemble_wg_maxwell(&hcurl, qo, 0.0, &[]).0;
    let mut d = vec![vec![0.0_f64; n]; n];
    for i in 0..n {
        for p in k0.row_ptr[i]..k0.row_ptr[i + 1] {
            d[i][k0.col_idx[p] as usize] -= k0.values[p];
        }
        for p in k1.row_ptr[i]..k1.row_ptr[i + 1] {
            d[i][k1.col_idx[p] as usize] += k1.values[p];
        }
    }
    let reference = wg_maxwell_face_block(&mesh, &hcurl, qo, 1.0);
    let rel = max_rel_diff(&d, &reference);
    println!("maxwell curved: wg face block vs isoparametric={rel:.3e}");
    assert!(rel < 1e-12, "wg maxwell face block != isoparametric ({rel:.3e})");
}

/// Independent assembly of the HCurl tangential-jump stabilizer through
/// `face_point_geom`.
fn wg_maxwell_face_block<const D: usize>(
    mesh: &Mesh<D>,
    hcurl: &HCurlSpace<Mesh<D>>,
    quad_order: u8,
    penalty: f64,
) -> Vec<Vec<f64>> {
    let dim = mesh.dim() as usize;
    let nd: Box<dyn VectorReferenceElement> = Box::new(TriNDk::new(1));
    let ne = nd.n_dofs();
    let n = hcurl.n_dofs();
    let mut k = vec![vec![0.0_f64; n]; n];

    let mut add = |el: u32, er: u32, fnodes: &[u32]| {
        let h = face_measure(mesh, el, fnodes, quad_order);
        let alpha = penalty / h.max(1e-14);
        let qf = face_rule(dim, quad_order);
        let dofs_l: Vec<usize> = hcurl.element_dofs(el).iter().map(|&d| d as usize).collect();
        let dofs_r: Vec<usize> = hcurl.element_dofs(er).iter().map(|&d| d as usize).collect();
        for (qi, xi) in qf.points.iter().enumerate() {
            for (es, dofs) in [(el, &dofs_l), (er, &dofs_r)] {
                let g = rs_face(mesh, es, fnodes, xi);
                let w = qf.weights[qi] * g.nor.iter().map(|v| v * v).sum::<f64>().sqrt();
                let mut pb = vec![0.0_f64; ne * dim];
                nd.eval_basis_vec(&g.eip, &mut pb);
                for i in 0..ne {
                    for j in 0..ne {
                        let v: f64 =
                            alpha * w * (0..dim).map(|d| pb[i * dim + d] * pb[j * dim + d]).sum::<f64>();
                        if v.abs() > 1e-30 {
                            k[dofs[i]][dofs[j]] += v;
                        }
                    }
                }
                if el == er {
                    break;
                }
            }
        }
    };

    for f in &InteriorFaceList::build(mesh).faces {
        add(f.elem_left, f.elem_right, &f.face_nodes);
    }
    let bmap = fem_assembly::dg::dg_base::build_face_elem_map(mesh, dim);
    for bf in mesh.face_iter() {
        if let Some(&el) = bmap.get(&bf) {
            let fnodes: Vec<u32> = mesh.face_nodes(bf).to_vec();
            add(el, el, &fnodes);
        }
    }
    k
}
