pub mod dpg;
pub mod dpg_2d;
pub mod dpg_3d;
pub mod dpg_framework;
pub mod dpg_stokes;
pub mod dpg_maxwell;
pub mod dpg_elasticity;
pub mod sinv;
pub mod trace_jump;
pub mod dpg_operator;

pub use dpg::*;
pub use dpg_2d::*;
pub use dpg_3d::*;
pub use dpg_framework::*;
pub use dpg_stokes::*;
pub use dpg_maxwell::*;
pub use dpg_elasticity::*;
pub use sinv::SinvBuilder;
pub use trace_jump::assemble_bhat;
pub use dpg_operator::{DpgNormalOperator, build_shat, compute_dpg_residual};
