//! Legacy (non-XML) VTK `.vtk` writer — 1:1 port of MFEM `Mesh::PrintVTK`.
//!
//! Output layout (ASCII, `UNSTRUCTURED_GRID`):
//!
//! ```text
//! # vtk DataFile Version 3.0
//! Generated by MFEM
//! ASCII
//! DATASET UNSTRUCTURED_GRID
//! POINTS <n_vertices> double
//! ...  (x y z per line, zero-padded to 3 columns)
//! CELLS <n_elems> <size>
//! <npe> v0 v1 ...         (Prism6 nodes permuted: 0 2 1 3 5 4)
//! CELL_TYPES <n_elems>
//! <vtk cell type per element>
//! CELL_DATA <n_elems>
//! SCALARS material int
//! LOOKUP_TABLE default
//! <attribute per element>
//! ```
//!
//! Only linear geometry is written (MFEM's `Nodes == NULL` branch); curved
//! meshes are rejected, mirroring MFEM's error for unsupported FECs.

use std::io::Write;

use fem_core::{FemError, FemResult};
use fem_mesh::element_type::ElementType;
use fem_mesh::simplex::Mesh;

/// Write a mesh in legacy VTK format to a stream.
pub fn write_vtk<const D: usize>(mesh: &Mesh<D>, mut writer: impl Write) -> FemResult<()> {
    if mesh.geometry.is_some() {
        return Err(vtk_err(
            "legacy VTK output requires a linear mesh (MFEM PrintVTK only supports \
             linear/ quadratic nodal grids)",
        ));
    }

    writeln!(writer, "# vtk DataFile Version 3.0")?;
    writeln!(writer, "Generated by MFEM")?;
    writeln!(writer, "ASCII")?;
    writeln!(writer, "DATASET UNSTRUCTURED_GRID")?;

    // POINTS
    let n_nodes = mesh.n_nodes();
    writeln!(writer, "POINTS {n_nodes} double")?;
    for i in 0..n_nodes {
        let c = mesh.coords_of(i as u32);
        for j in 0..3 {
            if j > 0 {
                write!(writer, " ")?;
            }
            write!(writer, "{}", cpp_float(if j < D { c[j] } else { 0.0 }))?;
        }
        writeln!(writer)?;
    }

    // CELLS (with the MFEM/VTK vertex permutation for prisms)
    let n_elems = mesh.n_elems();
    let mut total = 0_usize;
    for e in 0..n_elems {
        total += element_nodes(mesh, e as u32).len() + 1;
    }
    writeln!(writer, "CELLS {n_elems} {total}")?;
    for e in 0..n_elems {
        let eid = e as u32;
        let nodes = element_nodes(mesh, eid);
        write!(writer, "{}", nodes.len())?;
        let perm = vertex_permutation(mesh.element_type_at(eid));
        for (j, _) in nodes.iter().enumerate() {
            let idx = match perm {
                Some(p) => p[j],
                None => j,
            };
            write!(writer, " {}", nodes[idx])?;
        }
        writeln!(writer)?;
    }

    // CELL_TYPES
    writeln!(writer, "CELL_TYPES {n_elems}")?;
    for e in 0..n_elems {
        let et = mesh.element_type_at(e as u32);
        writeln!(writer, "{}", vtk_cell_type(et)?)?;
    }

    // Attributes (material scalars).
    writeln!(writer, "CELL_DATA {n_elems}")?;
    writeln!(writer, "SCALARS material int")?;
    writeln!(writer, "LOOKUP_TABLE default")?;
    for e in 0..n_elems {
        let attr = mesh.elem_tags.get(e).copied().unwrap_or(0);
        writeln!(writer, "{attr}")?;
    }
    Ok(())
}

/// Convenience wrapper: write a legacy `.vtk` file by path.
pub fn write_vtk_file<const D: usize>(
    mesh: &Mesh<D>,
    path: impl AsRef<std::path::Path>,
) -> FemResult<()> {
    let f = std::fs::File::create(path)?;
    write_vtk(mesh, std::io::BufWriter::new(f))
}

/// Connectivity of element `e`, honoring mixed-element meshes.
fn element_nodes<const D: usize>(mesh: &Mesh<D>, e: u32) -> &[fem_core::NodeId] {
    if let Some(ref offsets) = mesh.elem_offsets {
        let e = e as usize;
        &mesh.conn[offsets[e]..offsets[e + 1]]
    } else {
        let npe = mesh.elem_type.nodes_per_element();
        let e = e as usize;
        &mesh.conn[npe * e..npe * (e + 1)]
    }
}

/// `VTKGeometry::Map` — MFEM geometry to linear VTK cell type.
fn vtk_cell_type(et: ElementType) -> FemResult<i32> {
    Ok(match et {
        ElementType::Point1 => 1,
        ElementType::Line2 | ElementType::Line3 => 3,
        ElementType::Tri3 | ElementType::Tri6 => 5,
        ElementType::Quad4 | ElementType::Quad8 | ElementType::Quad9 => 9,
        ElementType::Tet4 | ElementType::Tet10 => 10,
        ElementType::Hex8 | ElementType::Hex20 | ElementType::Hex27 => 12,
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => 13,
        ElementType::Pyramid5 | ElementType::Pyramid13 => 14,
        other => {
            return Err(vtk_err(format!(
                "legacy VTK: unsupported element type {other:?}"
            )))
        }
    })
}

/// `VTKGeometry::VertexPermutation` — only prisms are permuted (`PrismMap`).
fn vertex_permutation(et: ElementType) -> Option<&'static [usize]> {
    match et {
        ElementType::Prism6 | ElementType::Prism15 | ElementType::Prism18 => {
            Some(&[0, 2, 1, 3, 5, 4])
        }
        _ => None,
    }
}

/// Format a float the way C++ `ostream` with default settings does
/// (`%g`-style with 6 significant digits).
fn cpp_float(v: f64) -> String {
    if v == 0.0 {
        return "0".to_string();
    }
    let a = v.abs();
    let exp = a.log10().floor() as i32;
    if exp < -4 || exp >= 6 {
        // Scientific with 6 significant digits, exponent with sign, 2+ digits.
        let s = format!("{:.5e}", v); // "1.23450e7"
        let (mantissa, exp_str) = s.split_once('e').unwrap();
        let mantissa = strip_trailing_zeros(mantissa);
        let e: i32 = exp_str.parse().unwrap();
        format!("{mantissa}e{:+03}", e)
    } else {
        let decimals = (5 - exp).max(0) as usize;
        let s = format!("{:.*}", decimals, v);
        strip_trailing_zeros(&s)
    }
}

fn strip_trailing_zeros(s: &str) -> String {
    if let Some(dot) = s.find('.') {
        let trimmed = s.trim_end_matches('0').trim_end_matches('.');
        if trimmed == "-" || trimmed.is_empty() {
            return "0".to_string();
        }
        let _ = dot;
        trimmed.to_string()
    } else {
        s.to_string()
    }
}

fn vtk_err(msg: impl Into<String>) -> FemError {
    FemError::Mesh(msg.into())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The TrueGrid sample also used for the C++ cross-check (2 hexes, 1
    /// boundary quad, material tags 7 and 9), parsed as a body string.
    fn sample_mesh() -> Mesh<3> {
        let body = "\
            0 12 2\n\
            this line is skipped\n\
            0 0 1\n\
            skipped\n\
            skipped\n\
            1 0.0 0.0 0.0 0.0\n\
            2 0.0 0.0 0.0 1.0\n\
            3 0.0 1.0 0.0 0.0\n\
            4 0.0 1.0 0.0 1.0\n\
            5 0.0 2.0 0.0 0.0\n\
            6 0.0 2.0 0.0 1.0\n\
            7 0.0 0.0 1.0 0.0\n\
            8 0.0 0.0 1.0 1.0\n\
            9 0.0 1.0 1.0 0.0\n\
            10 0.0 1.0 1.0 1.0\n\
            11 0.0 2.0 1.0 0.0\n\
            12 0.0 2.0 1.0 1.0\n\
            1 7 1 3 9 7 2 4 10 8\n\
            2 9 3 5 11 9 4 6 12 10\n\
            7 5 11 12 6\n";
        crate::truegrid::read_truegrid(body.as_bytes()).expect("failed to parse sample")
    }

    #[test]
    fn matches_mfem_printvtk_reference() {
        let mesh = sample_mesh();
        let mut buf: Vec<u8> = Vec::new();
        write_vtk(&mesh, &mut buf).expect("write failed");
        let out = String::from_utf8(buf).unwrap();

        // Reference produced by MFEM 4.10 `Mesh::PrintVTK` on the same mesh:
        //   ./vtk_dump sample.fgrid sample_cpp.vtk
        let expected = "# vtk DataFile Version 3.0\n\
Generated by MFEM\n\
ASCII\n\
DATASET UNSTRUCTURED_GRID\n\
POINTS 12 double\n\
0 0 0\n\
0 0 1\n\
1 0 0\n\
1 0 1\n\
2 0 0\n\
2 0 1\n\
0 1 0\n\
0 1 1\n\
1 1 0\n\
1 1 1\n\
2 1 0\n\
2 1 1\n\
CELLS 2 18\n\
8 0 2 8 6 1 3 9 7\n\
8 2 4 10 8 3 5 11 9\n\
CELL_TYPES 2\n\
12\n\
12\n\
CELL_DATA 2\n\
SCALARS material int\n\
LOOKUP_TABLE default\n\
7\n\
9\n";
        assert_eq!(out, expected);
    }

    #[test]
    fn cpp_float_matches_g_format() {
        assert_eq!(cpp_float(0.0), "0");
        assert_eq!(cpp_float(1.0), "1");
        assert_eq!(cpp_float(-2.5), "-2.5");
        assert_eq!(cpp_float(1.0 / 3.0), "0.333333");
        assert_eq!(cpp_float(1234567.0), "1.23457e+06");
        assert_eq!(cpp_float(0.000012345), "1.2345e-05");
        assert_eq!(cpp_float(1500.0), "1500");
    }

    /// One-off cross-check vs MFEM 4.10 dumps of the stock beam meshes
    /// (kept in tmp/rounde; skipped when the files are not present).
    #[test]
    fn cross_check_beam_tet_and_wedge() {
        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tmp/rounde");
        for (mesh_name, ref_name) in
            [("beam-tet.mesh", "ref_tet.vtk"), ("beam-wedge.mesh", "ref_wedge.vtk")]
        {
            let mesh_path = format!("{dir}/{mesh_name}");
            let ref_path = format!("{dir}/{ref_name}");
            let (Ok(mesh_txt), Ok(ref_txt)) = (
                std::fs::read_to_string(&mesh_path),
                std::fs::read_to_string(&ref_path),
            ) else {
                // Fixtures not present (tmp/ cleaned) — nothing to compare.
                continue;
            };
            let file = crate::mfem::read_mfem(mesh_txt.as_bytes()).expect("mfem parse failed");
            let mesh = file.mesh3d.as_ref().expect("expected 3-D mesh");
            let mut buf: Vec<u8> = Vec::new();
            write_vtk(mesh, &mut buf).expect("write failed");
            let out = String::from_utf8(buf).unwrap();
            assert_eq!(
                out,
                ref_txt,
                "legacy VTK output differs from MFEM PrintVTK for {mesh_name}"
            );
        }
    }
}
